//
//  CrossCheck68kTests.swift
//  RBFHammerScenarioTests
//
//  Runs the two 6809 fault scenarios against os9exec's OWN RBF (68k), to see
//  whether the same defects are present here. Reporting probes, not assertions:
//  the point is to observe what os9exec does, not to enforce a verdict.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-22-2026
//

import XCTest
@testable import RBFHammerCore

final class CrossCheck68kTests: XCTestCase {

    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent().deletingLastPathComponent()

    private func report(_ s: String) {
        FileHandle.standardError.write(Data("CROSSCHECK \(s)\n".utf8))
    }

    /// Bug 2 (lost update): concurrent binary read-modify-write of one counter.
    /// On 6809/NitrOS-9 this loses updates; os9exec is expected to keep them all
    /// (its record lock serializes — no register-clobber retry bug here).
    ///
    /// NOTE: 68k BASIC09 INTEGER is 32-bit, so `rec(1)` is the first FOUR bytes,
    /// big-endian (68k), not two.
    func testLostUpdateBinaryRmwOn68k() throws {
        let file = "/h9/lu.dat"
        let workers = 4, increments = 200
        var roster = [WorkerSpec(id: 99, role: .seedbin, file: file, count: 1)]
        roster += (1...workers).map {
            WorkerSpec(id: $0, role: .rmwbin, file: file, count: increments, nap: 0, napMode: .nilWrites)
        }
        let scenario = Scenario(name: "lu-68k", backend: .rbfImage, workers: roster, timeout: 120)
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)

        let expected = workers * increments
        guard let data = result.produced[file], data.count >= 4 else {
            return report("lost-update: NO COUNTER FILE\n\(result.transcript.suffix(1500))")
        }
        let b = [UInt8](data)
        let counter = Int(b[0]) << 24 | Int(b[1]) << 16 | Int(b[2]) << 8 | Int(b[3])
        report("lost-update on 68k: counter=\(counter) of \(expected) expected, lost=\(expected - counter)")
    }

    /// Bug 1 (write-only lock): a slow write-only producer, a read-only follower.
    /// A write-only path should take NO lock, so the follower should stop at the
    /// end that exists. If os9exec (like stock NitrOS-9) locks regardless of open
    /// mode, the follower will TRAIL the producer to its full count instead.
    func testWriteOnlyFollowOn68k() throws {
        let file = "/h9/wo.dat"
        let records = 8
        let roster = [
            WorkerSpec(id: 1, role: .writeonly, file: file, count: records, nap: 40, napMode: .sleep),
            WorkerSpec(id: 2, role: .follow, file: file, count: 1, nap: 100, napMode: .sleep),
        ]
        let scenario = Scenario(name: "follow-68k", backend: .rbfImage, workers: roster, timeout: 120)
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)

        let count = result.transcript.split(whereSeparator: \.isNewline)
            .first { $0.contains("follow done") }?
            .split(separator: " ").last.flatMap { Int($0) }
        report("write-only follow on 68k: follower read \(count.map(String.init) ?? "?") of \(records) "
             + "(stops small => os9exec correct; ~\(records) => os9exec follows, bug present)")
    }

    /// The CONTROL: same slow producer but opened UPDATE. A follower *should*
    /// trail an update-mode producer (that is the legitimate slow-writer/reader
    /// coordination). If this follows but the write-only case above does not,
    /// os9exec is correct. If BOTH read ~0, os9exec's reader never follows a live
    /// writer at all — a coherence gap, not the lock bug.
    func testUpdateProducerFollowOn68k() throws {
        let file = "/h9/wu.dat"
        let records = 8
        let roster = [
            WorkerSpec(id: 1, role: .updproducer, file: file, count: records, nap: 40, napMode: .sleep),
            WorkerSpec(id: 2, role: .follow, file: file, count: 1, nap: 100, napMode: .sleep),
        ]
        let scenario = Scenario(name: "updfollow-68k", backend: .rbfImage, workers: roster, timeout: 120)
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        let count = result.transcript.split(whereSeparator: \.isNewline)
            .first { $0.contains("follow done") }?
            .split(separator: " ").last.flatMap { Int($0) }
        report("UPDATE-producer follow on 68k (control): follower read \(count.map(String.init) ?? "?") "
             + "of \(records) (~\(records) => os9exec's follow works; ~0 => reader never follows at all)")
    }

    /// The decisive lock test: force interleave with a hold between GET and PUT,
    /// and compare the LOCKED path (`rmw`, update mode — auto-lock) against the
    /// UNLOCKED control (`rmwfree`, separate read/write paths — no lock). If
    /// os9exec's record lock is solid, unlocked loses updates and locked keeps
    /// them all. If locked ALSO loses, the auto-lock is not holding.
    private func rmwCounter(role: WorkerSpec.Role, workers: Int, inc: Int, nap: Int) throws -> Int {
        let file = "/h9/lock.dat"
        var roster = [WorkerSpec(id: 99, role: .seed, file: file, count: 1)]
        roster += (1...workers).map {
            WorkerSpec(id: $0, role: role, file: file, count: inc, nap: nap, napMode: .sleep)
        }
        let scenario = Scenario(name: "lock-68k", backend: .rbfImage, workers: roster, timeout: 180)
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        guard let data = result.produced[file],
              let text = String(bytes: data.prefix(9), encoding: .ascii),
              text.hasPrefix("T"), let n = Int(text.dropFirst()) else { return -1 }
        return n
    }

    func testLockedVsUnlockedRmwWithForcedInterleaveOn68k() throws {
        let workers = 4, inc = 60, nap = 8   // ~0.08s hold between GET and PUT
        let expected = workers * inc
        let unlocked = try rmwCounter(role: .rmwfree, workers: workers, inc: inc, nap: nap)
        let locked   = try rmwCounter(role: .rmw,     workers: workers, inc: inc, nap: nap)
        report("forced-interleave on 68k (expected \(expected)):")
        report("  UNLOCKED (rmwfree): \(unlocked)  (should be < \(expected) — proves interleave)")
        report("  LOCKED   (rmw):     \(locked)  (should be \(expected) if the auto-lock holds)")
    }
}
