//
//  DestructiveTests.swift
//  RBFHammerScenarioTests
//
//  Deliberately violent scenarios on a throwaway RBF image, each asking one
//  question: after this, is the FILESYSTEM still consistent? The content of any
//  one file may legitimately be incomplete (a killed writer, an exhausted disk),
//  so these do NOT assert completeness -- they assert that `dcheck` still
//  certifies the device and that RBF reported the condition cleanly rather than
//  corrupting the disk. All run on `.rbfImage`, the only backend that is a real
//  RBF allocator on a real image.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import XCTest
@testable import RBFHammerCore

final class DestructiveTests: XCTestCase {

    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammerScenarioTests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// Prints the relevant guest lines of a run when `RBF_DUMP` is set, so a
    /// destructive scenario's actual behaviour can be inspected without a
    /// deliberate failure.
    private func dump(_ result: RunResult) {
        guard ProcessInfo.processInfo.environment["RBF_DUMP"] != nil else { return }
        let keep = ["hammer:", "Error #", "E_FULL", "intact", "not in", "free sector",
                    "Capacity", "cluster", "Media Full"]
        let lines = result.transcript.split(whereSeparator: \.isNewline)
            .filter { line in keep.contains { line.contains($0) } }
        print("── RBF_DUMP ──\n" + lines.joined(separator: "\n") + "\n──────────────")
    }

    /// OS-9 `E_FULL`, the error RBF raises when the media has no free clusters.
    /// Verified live: `build` on a filled `mount -k=16K` image reported
    /// `Error #000:248 (E_FULL) Media Full`.
    private static let mediaFull = 248

    // ── Disk full ─────────────────────────────────────────────────────────────

    /// One worker writes far more than a tiny device can hold. RBF must run out
    /// of space with a clean `E_FULL`, and the image must stay structurally
    /// intact -- no half-allocated cluster, no bitmap left disagreeing with the
    /// file structure.
    func testExhaustingFreeSpaceLeavesTheImageIntact() throws {
        let file = "/h9/big.dat"
        let scenario = Scenario(name: "disk-full",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file, count: 500)],
                                deviceKB: 16)
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut, "disk-full run hung:\n\(result.transcript)")

        // The scenario only means something if it actually ran out of space.
        // A worker that quietly fit would make the intact check vacuous.
        XCTAssertTrue(result.transcript.contains("ERROR err \(Self.mediaFull)")
                   || result.transcript.contains("E_FULL"),
                      "the device was never exhausted -- disk-full proved nothing:\n"
                    + result.transcript)

        // The whole point: RBF hit the wall without corrupting the disk.
        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "disk-full left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }

    // ── Delete a file out from under processes holding it open ─────────────────

    /// A file is pre-extended, two readers open it and start walking it slowly,
    /// and then it is deleted while they still hold it open. RBF must resolve the
    /// contention -- refuse the delete, defer it, or let the readers finish on
    /// the doomed file -- and whatever it chooses, the DEVICE must end
    /// structurally intact, with the file's clusters accounted for either way.
    func testDeletingAFileHeldOpenLeavesTheImageIntact() throws {
        let file = "/h9/held.dat"
        var roster = [WorkerSpec(id: 99, role: .create, file: file, count: 40)]
        roster += (1...2).map {
            WorkerSpec(id: $0, role: .read, file: file, count: 40, nap: 3, napMode: .sleep)
        }
        let scenario = Scenario(name: "delete-held-open",
                                backend: .rbfImage, workers: roster, timeout: 120,
                                midFlight: ["sleep 40", "del \(file)"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut,
                       "delete-held-open hung -- a reader parked on a doomed file:\n"
                     + result.transcript)

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "deleting a held-open file left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")

        // The deleted file's clusters must return. A delete-while-open that
        // freed nothing (or freed twice) would leave the free count well off the
        // pristine baseline -- only the bitmap and root dir stay allocated.
        guard let free = StructuralOracle.freeSectors(in: result.transcript),
              let capacity = StructuralOracle.capacitySectors(in: result.transcript) else {
            return XCTFail("no free/capacity to judge reclamation:\n\(result.transcript)")
        }
        XCTAssertGreaterThanOrEqual(free, capacity - 8,
                       "delete-while-open leaked clusters: only \(free)/\(capacity) sectors "
                     + "free, expected all but the bitmap/root reclaimed")
    }

    // ── Kill a writer mid-write ────────────────────────────────────────────────

    /// A lone writer extends a file slowly; part way through, its process is
    /// killed with the file still open. The kernel's process-death cleanup
    /// (`F$Exit` closing the dying process's paths) must leave the filesystem
    /// consistent -- a half-written file is fine, a cross-linked or half-freed
    /// cluster is not.
    ///
    /// The writer is the only backgrounded process, so it is proc 3 (`Live`: the
    /// shell's `&` reply is `+3`); `kill 3` after a short sleep lands mid-write.
    func testKillingAWriterMidWriteLeavesTheImageIntact() throws {
        let file = "/h9/victim.dat"
        let scenario = Scenario(name: "kill-mid-write",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file,
                                                     count: 100, nap: 3, napMode: .sleep)],
                                timeout: 60,
                                midFlight: ["sleep 40", "kill 3"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut,
                       "kill-mid-write hung -- the dead writer's path was never reaped:\n"
                     + result.transcript)

        // It must really have died mid-write: a writer that finished all 100
        // records before the kill proves nothing about interrupted writes.
        XCTAssertFalse(result.transcript.contains("worker 1 wrote 100"),
                       "writer finished before the kill -- it was not interrupted:\n"
                     + result.transcript)

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "killing a writer mid-write left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }

    // ── Delete several growing files at once ───────────────────────────────────

    /// ★ Was a REAL FINDING (2026-07-21), now FIXED: deleting a file still open
    /// for WRITE leaked every cluster allocated after the delete, because
    /// `DeallocateBlocks` runs once at delete time and no later close frees what
    /// the still-open writer keeps adding. The fix matches canonical OS-9 -- RBF
    /// now refuses the delete with `E$Share` (253) while any other path holds the
    /// file open for write, exactly as real NitrOS-9 does (which is why that
    /// reference never had the leak). This test guards the fix: four workers grow
    /// their own files, all four are `del`eted mid-write, and each delete must be
    /// REFUSED while the device stays structurally intact. A regression that
    /// allowed the delete again would drop the E_SHARE refusals AND make the
    /// orphaned-cluster oracle fire -- both loud. See FAILABILITY.md.
    func testDeletingFilesOpenForWriteIsRefusedWithShare() throws {
        let files = (1...4).map { "/h9/churn\($0).dat" }
        let roster = files.enumerated().map { index, file in
            WorkerSpec(id: index + 1, role: .append, file: file,
                       count: 40, nap: 2, napMode: .sleep)
        }
        let scenario = Scenario(name: "delete-during-write",
                                backend: .rbfImage, workers: roster, timeout: 120,
                                midFlight: ["sleep 40"] + files.map { "del \($0)" })
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut, "delete-during-write hung:\n\(result.transcript)")

        // The del must land mid-write: each worker finishing its 40 records proves
        // it held the file open for write across the delete attempt, so a refusal
        // here is a refusal of a genuinely-busy file, not of an idle one.
        for id in 1...4 {
            XCTAssertTrue(result.transcript.contains("worker \(id) wrote 40"),
                          "worker \(id) did not finish -- the del may not have raced a live writer:\n"
                        + result.transcript)
        }

        // Canonical OS-9: every delete of a file open for write is refused. The
        // `E$Share` code proves it is the busy-file refusal specifically, not some
        // unrelated error standing in for it.
        XCTAssertTrue(result.transcript.contains("E_SHARE"),
                      "no E_SHARE refusal -- the busy-file delete was not rejected:\n"
                    + result.transcript)
        for file in files {
            XCTAssertTrue(result.transcript.contains("can't delete '\(file)'"),
                          "delete of open-for-write '\(file)' was not refused:\n"
                        + result.transcript)
        }

        // The integrity guarantee the leak violated: no orphaned clusters.
        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "delete-during-write left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }

    /// Isolation for the finding above: one writer, but the `del` waits until the
    /// writer has FINISHED and CLOSED. This reclaims cleanly -- proving the leak
    /// is writing-to-a-deleted-file, not delete itself.
    func testLeakIsolation_deleteAfterClose() throws {
        let file = "/h9/isolate.dat"
        let scenario = Scenario(name: "delete-after-close",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file, count: 20)],
                                timeout: 60,
                                midFlight: ["w", "del \(file)"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)
        XCTAssertTrue(result.transcript.contains("worker 1 wrote 20"),
                      "precondition: the writer should finish before the del:\n\(result.transcript)")
        guard let free = StructuralOracle.freeSectors(in: result.transcript),
              let capacity = StructuralOracle.capacitySectors(in: result.transcript) else {
            return XCTFail("no free/capacity:\n\(result.transcript)")
        }
        XCTAssertGreaterThanOrEqual(free, capacity - 8,
                       "delete-after-close should reclaim cleanly but leaked: \(free)/\(capacity)")
        XCTAssertEqual(StructuralOracle.structuralViolations(dcheck: result.transcript), [],
                       "delete-after-close left the image damaged:\n\(result.transcript)")
    }

    // ── Truncate ───────────────────────────────────────────────────────────────

    /// A file is pre-extended to 200 records (~50 sectors), then shrunk to 320
    /// bytes with `SS.Size` (the `trunc` helper) and closed WITHOUT seeking to
    /// the new EOF. The file really shrinks, the device stays consistent, and
    /// the tail clusters are deliberately KEPT -- which is faithful OS-9, not a
    /// leak.
    ///
    /// `trunc` leaves the file pointer at 0, so on close it is in update mode and
    /// not at EOF -- exactly the case the file-manager spec preserves for
    /// random-access/database files ("unused sectors normally deallocated on
    /// close, EXCEPT when closed in write/update mode while not at EOF"). So os9exec
    /// keeping the tail here is correct; `pRclose` only runs `ReleaseBlocks` when
    /// `currPos == lastPos`. The companion `testSetSizeShrinkReclaimsTailWhenClosedAtEOF`
    /// proves the tail IS reclaimed once the pointer is at EOF (owner-consulted +
    /// skill-confirmed; an earlier read of this as a `pRsetsz` leak was wrong --
    /// the test was simply positioned in the preserved case).
    func testTruncatingAFileShrinksItAndStaysIntact() throws {
        let file = "/h9/tr.dat"
        // os9exec cannot fork a binary straight from the host-directory scratch,
        // so the helper is copied onto the RBF image, run there, then removed --
        // leaving only the truncated file, so the free count reflects just it.
        let scenario = Scenario(name: "truncate",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 99, role: .create, file: file, count: 200)],
                                midFlight: ["copy /h5/trunc /h9/trunc",
                                            "/h9/trunc \(file) 320",
                                            "del /h9/trunc"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut, "truncate run hung:\n\(result.transcript)")

        // The truncate really happened: the file now reads back at 320 bytes,
        // not the ~25600 it held after pre-extension. Without this the whole
        // test could pass on a trunc that silently did nothing.
        guard let data = result.produced[file] else {
            return XCTFail("tr.dat was not retrieved:\n\(result.transcript)")
        }
        XCTAssertEqual(data.count, 320,
                       "trunc should have set the size to 320 bytes, got \(data.count)")

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "truncate left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")

        // Faithful behaviour: the tail is PRESERVED (update-mode, pointer not at
        // EOF), so free stays well short of capacity -- the ~48 tail sectors are
        // still the file's, to be released on a close-at-EOF or a delete. A run
        // that reclaimed here would mean os9exec had DROPPED the random-access
        // preservation, which is what would deserve a look.
        guard let free = StructuralOracle.freeSectors(in: result.transcript),
              let capacity = StructuralOracle.capacitySectors(in: result.transcript) else {
            return XCTFail("no free/capacity to judge the truncate:\n\(result.transcript)")
        }
        XCTAssertLessThan(free, capacity - 8,
                       "the tail was reclaimed (\(free)/\(capacity)) despite the file being "
                     + "closed update-mode not-at-EOF -- os9exec dropped the random-access "
                     + "preservation the spec calls for")
    }

    /// The companion to the above: when the shrunk file IS closed with the
    /// pointer at the new EOF, RBF's close-time truncation runs and the tail
    /// clusters ARE returned to the free map. `truncsk` seeks to the new size
    /// before closing (unlike `trunc`), so `pRclose`'s `crp == lsp` release path
    /// fires. This is the other half of the skill's rule, and it proves os9exec
    /// reclaims the tail whenever it is supposed to -- so the preserved case
    /// above is a deliberate feature, not a leak.
    func testSetSizeShrinkReclaimsTailWhenClosedAtEOF() throws {
        let file = "/h9/trs.dat"
        let scenario = Scenario(name: "truncate-seek",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 99, role: .create, file: file, count: 200)],
                                midFlight: ["copy /h5/truncsk /h9/truncsk",
                                            "/h9/truncsk \(file) 320",
                                            "del /h9/truncsk"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)
        XCTAssertFalse(result.timedOut, "truncate-seek run hung:\n\(result.transcript)")

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [], structural.map(\.detail).joined(separator: "\n"))

        guard let free = StructuralOracle.freeSectors(in: result.transcript),
              let capacity = StructuralOracle.capacitySectors(in: result.transcript) else {
            return XCTFail("no free/capacity to judge the truncate:\n\(result.transcript)")
        }
        XCTAssertGreaterThanOrEqual(free, capacity - 8,
                       "seek-to-EOF truncate did NOT reclaim the tail: \(free)/\(capacity) free "
                     + "-- close-time truncation should have released it. Scratch \(result.scratchPath)")
    }

    // ── Stale-sector disclosure ──────────────────────────────────────────────────

    /// Growing a file with `SS.Size` must not hand back another file's freed
    /// contents. Fill a tiny device with a recognisable filler pattern, delete
    /// it (freeing those clusters with the pattern still physically on the
    /// media), then create a one-line victim file and `SS.Size`-GROW it into the
    /// just-freed space. Whatever the grow exposes must read back as zeros, or
    /// the read must stop at the real allocated end -- it must NEVER surface the
    /// deleted filler's bytes.
    ///
    /// `SS.Size` grow exposes RAW reclaimed disk -- and that is CORRECT, faithful
    /// OS-9 behaviour, confirmed by the owner (a firsthand OS-9 author): "no
    /// zeroing; if you open a file and setsize big, you get to read the garbage
    /// data, noproblemo" -- and `/h0@` reads the raw device anyway. OS-9 security
    /// is relaxed-but-present, and unzeroed grown space is by design, not a leak.
    ///
    /// So this is a FAITHFULNESS guard, not a bug: growing a file must expose the
    /// raw reclaimed clusters exactly as real OS-9 does. Fill a 16K image to
    /// `E_FULL` (every cluster stamped `unwritten slot`), delete it, grow a tiny
    /// victim into the freed space; the grown region must read back that raw
    /// content. If os9exec ever started ZEROING grown space it would diverge from
    /// OS-9, and this test would catch it. `pRsetsz` (file_rbf.c ~3995) sets the
    /// logical size without touching the block list, which is what produces this.
    func testSetSizeGrowExposesRawReclaimedDiskAsRealOS9Does() throws {
        let filler = "/h9/filler.dat", victim = "/h9/victim.dat"
        // 400 x 64B far exceeds a 16K image, so the create worker fills it to
        // E_FULL, stamping "unwritten slot" across every cluster. Deleting it
        // frees them all; the victim's grow can then only draw from that pool.
        let scenario = Scenario(name: "disclosure",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 99, role: .create, file: filler, count: 400)],
                                deviceKB: 16,
                                midFlight: ["del \(filler)",
                                            "copy /h5/trunc /h9/trunc",
                                            "echo VICTIMHDR >\(victim)",
                                            "/h9/trunc \(victim) 12000",
                                            "del /h9/trunc",
                                            "copy \(victim) /h5/victim.dat"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)
        XCTAssertFalse(result.timedOut, "disclosure run hung:\n\(result.transcript)")

        let victimHost = URL(fileURLWithPath: result.scratchPath)
            .appendingPathComponent("victim.dat")
        guard let data = try? Data(contentsOf: victimHost) else {
            return XCTFail("victim.dat was not produced -- did the grow/copy run?\n"
                         + result.transcript)
        }
        // The filler stamped "unwritten slot" into every cluster it touched. If
        // any of that survives in the grown victim, the grow disclosed a deleted
        // file's contents.
        let bytes = [UInt8](data)
        let needle = [UInt8]("unwritten slot".utf8)
        let rawDataExposed = bytes.indices.contains { start in
            start + needle.count <= bytes.count
                && Array(bytes[start ..< start + needle.count]) == needle
        }
        // Faithful to OS-9: the grown region reads back the raw reclaimed
        // clusters, filler and all. A zeroed (or E$EOF-bounded) result would be
        // a divergence from real OS-9, and THAT is what would deserve a flag.
        XCTAssertTrue(rawDataExposed,
                      "SS.Size grow did NOT expose the raw reclaimed clusters in the "
                    + "\(data.count)-byte victim -- os9exec diverged from OS-9, which does "
                    + "not zero grown space. Scratch kept at \(result.scratchPath)")
    }

    // ── Shrink under a live reader ───────────────────────────────────────────────

    /// A file of 50 records is walked by a slow reader; part way through, another
    /// process `SS.Size`-shrinks it to 10 records. RBF must make the shrink
    /// visible to the reader (it calls `RingSetLastPos` on the other open paths),
    /// so the reader stops at the new end. A reader that runs on to 50 would be
    /// reading the preserved tail past the file's new logical EOF -- a stale read
    /// the shrink was supposed to hide.
    func testShrinkingAFileUnderAReaderStopsItAtTheNewEnd() throws {
        let file = "/h9/shrink.dat"
        let scenario = Scenario(name: "shrink-under-reader",
                                backend: .rbfImage,
                                workers: [
                                    WorkerSpec(id: 99, role: .create, file: file, count: 50),
                                    WorkerSpec(id: 1, role: .read, file: file, count: 50,
                                               nap: 20, napMode: .sleep),
                                ],
                                midFlight: ["sleep 10",
                                            "copy /h5/trunc /h9/trunc",
                                            "/h9/trunc \(file) 640",
                                            "del /h9/trunc"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)
        XCTAssertFalse(result.timedOut, "shrink-under-reader hung:\n\(result.transcript)")

        // The reader's own tally: "worker 1 read done N".
        guard let line = result.transcript.split(whereSeparator: \.isNewline)
                .first(where: { $0.contains("read done") }),
              let count = line.split(separator: " ").last.flatMap({ Int($0) }) else {
            return XCTFail("reader never reported a count:\n\(result.transcript)")
        }

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [], structural.map(\.detail).joined(separator: "\n"))

        // 640 bytes = 10 records. The reader should stop at the new end, not run
        // to the original 50 off the preserved tail.
        XCTAssertLessThan(count, 20,
                          "reader read \(count) of 50 records after the file was shrunk to 10 "
                        + "-- it ran off the preserved tail past the new EOF. Scratch \(result.scratchPath)")
    }

    // ── Directory storm ──────────────────────────────────────────────────────────

    /// Four workers rapidly create, write and delete 30 files each in ONE shared
    /// directory, all at once -- 120 create/delete cycles churning the directory's
    /// entries and the allocation bitmap. The directory grows past a single sector
    /// and its entries are freed and reused throughout. Afterwards every file is
    /// gone and `dcheck` must certify the device intact: no orphaned file
    /// descriptor, no torn directory entry, no cluster cross-linked between a
    /// freed FD and a live file.
    func testConcurrentDirectoryStormLeavesTheDeviceIntact() throws {
        let workers = 4, files = 40
        let scenario = Scenario(name: "dir-storm",
                                backend: .rbfImage,
                                workers: (1...workers).map {
                                    WorkerSpec(id: $0, role: .dirstorm, file: "/h9", count: files)
                                })
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)
        XCTAssertFalse(result.timedOut, "directory storm hung:\n\(result.transcript)")

        // Non-vacuous: every worker must actually have finished its churn.
        for id in 1...workers {
            XCTAssertTrue(result.transcript.contains("worker \(id) dirstorm done"),
                          "worker \(id) never finished the storm:\n\(result.transcript)")
        }
        XCTAssertFalse(result.transcript.contains("ERROR err"),
                       "a storm worker hit an uncaught error:\n\(result.transcript)")

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "the directory storm corrupted the filesystem:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }
}
