//
//  DestructiveTests.swift
//  RBFHammerScenarioTests
//
//  Deliberately violent scenarios on a throwaway RBF image, each asking one
//  question: after this, is the FILESYSTEM still consistent? The content of any
//  one file may legitimately be incomplete (a killed writer, an exhausted disk),
//  so these do NOT assert completeness -- they assert that `dcheck` still
//  certifies the device and that RBF reported the condition cleanly rather than
//  corrupting the disk. All run on `.rbfImage`, the only backend that is a real
//  RBF allocator on a real image.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import XCTest
@testable import RBFHammerCore

final class DestructiveTests: XCTestCase {

    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammerScenarioTests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// Prints the relevant guest lines of a run when `RBF_DUMP` is set, so a
    /// destructive scenario's actual behaviour can be inspected without a
    /// deliberate failure.
    private func dump(_ result: RunResult) {
        guard ProcessInfo.processInfo.environment["RBF_DUMP"] != nil else { return }
        let keep = ["hammer:", "Error #", "E_FULL", "intact", "not in", "free sector",
                    "Capacity", "cluster", "Media Full"]
        let lines = result.transcript.split(whereSeparator: \.isNewline)
            .filter { line in keep.contains { line.contains($0) } }
        print("── RBF_DUMP ──\n" + lines.joined(separator: "\n") + "\n──────────────")
    }

    /// OS-9 `E_FULL`, the error RBF raises when the media has no free clusters.
    /// Verified live: `build` on a filled `mount -k=16K` image reported
    /// `Error #000:248 (E_FULL) Media Full`.
    private static let mediaFull = 248

    // ── Disk full ─────────────────────────────────────────────────────────────

    /// One worker writes far more than a tiny device can hold. RBF must run out
    /// of space with a clean `E_FULL`, and the image must stay structurally
    /// intact -- no half-allocated cluster, no bitmap left disagreeing with the
    /// file structure.
    func testExhaustingFreeSpaceLeavesTheImageIntact() throws {
        let file = "/h9/big.dat"
        let scenario = Scenario(name: "disk-full",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file, count: 500)],
                                deviceKB: 16)
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut, "disk-full run hung:\n\(result.transcript)")

        // The scenario only means something if it actually ran out of space.
        // A worker that quietly fit would make the intact check vacuous.
        XCTAssertTrue(result.transcript.contains("ERROR err \(Self.mediaFull)")
                   || result.transcript.contains("E_FULL"),
                      "the device was never exhausted -- disk-full proved nothing:\n"
                    + result.transcript)

        // The whole point: RBF hit the wall without corrupting the disk.
        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "disk-full left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }
}
