//
//  DestructiveTests.swift
//  RBFHammerScenarioTests
//
//  Deliberately violent scenarios on a throwaway RBF image, each asking one
//  question: after this, is the FILESYSTEM still consistent? The content of any
//  one file may legitimately be incomplete (a killed writer, an exhausted disk),
//  so these do NOT assert completeness -- they assert that `dcheck` still
//  certifies the device and that RBF reported the condition cleanly rather than
//  corrupting the disk. All run on `.rbfImage`, the only backend that is a real
//  RBF allocator on a real image.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import XCTest
@testable import RBFHammerCore

final class DestructiveTests: XCTestCase {

    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammerScenarioTests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// Prints the relevant guest lines of a run when `RBF_DUMP` is set, so a
    /// destructive scenario's actual behaviour can be inspected without a
    /// deliberate failure.
    private func dump(_ result: RunResult) {
        guard ProcessInfo.processInfo.environment["RBF_DUMP"] != nil else { return }
        let keep = ["hammer:", "Error #", "E_FULL", "intact", "not in", "free sector",
                    "Capacity", "cluster", "Media Full"]
        let lines = result.transcript.split(whereSeparator: \.isNewline)
            .filter { line in keep.contains { line.contains($0) } }
        print("── RBF_DUMP ──\n" + lines.joined(separator: "\n") + "\n──────────────")
    }

    /// OS-9 `E_FULL`, the error RBF raises when the media has no free clusters.
    /// Verified live: `build` on a filled `mount -k=16K` image reported
    /// `Error #000:248 (E_FULL) Media Full`.
    private static let mediaFull = 248

    // ── Disk full ─────────────────────────────────────────────────────────────

    /// One worker writes far more than a tiny device can hold. RBF must run out
    /// of space with a clean `E_FULL`, and the image must stay structurally
    /// intact -- no half-allocated cluster, no bitmap left disagreeing with the
    /// file structure.
    func testExhaustingFreeSpaceLeavesTheImageIntact() throws {
        let file = "/h9/big.dat"
        let scenario = Scenario(name: "disk-full",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file, count: 500)],
                                deviceKB: 16)
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut, "disk-full run hung:\n\(result.transcript)")

        // The scenario only means something if it actually ran out of space.
        // A worker that quietly fit would make the intact check vacuous.
        XCTAssertTrue(result.transcript.contains("ERROR err \(Self.mediaFull)")
                   || result.transcript.contains("E_FULL"),
                      "the device was never exhausted -- disk-full proved nothing:\n"
                    + result.transcript)

        // The whole point: RBF hit the wall without corrupting the disk.
        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "disk-full left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }

    // ── Delete a file out from under processes holding it open ─────────────────

    /// A file is pre-extended, two readers open it and start walking it slowly,
    /// and then it is deleted while they still hold it open. RBF must resolve the
    /// contention -- refuse the delete, defer it, or let the readers finish on
    /// the doomed file -- and whatever it chooses, the DEVICE must end
    /// structurally intact, with the file's clusters accounted for either way.
    func testDeletingAFileHeldOpenLeavesTheImageIntact() throws {
        let file = "/h9/held.dat"
        var roster = [WorkerSpec(id: 99, role: .create, file: file, count: 40)]
        roster += (1...2).map {
            WorkerSpec(id: $0, role: .read, file: file, count: 40, nap: 3, napMode: .sleep)
        }
        let scenario = Scenario(name: "delete-held-open",
                                backend: .rbfImage, workers: roster, timeout: 120,
                                midFlight: ["sleep 40", "del \(file)"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut,
                       "delete-held-open hung -- a reader parked on a doomed file:\n"
                     + result.transcript)

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "deleting a held-open file left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")

        // The deleted file's clusters must return. A delete-while-open that
        // freed nothing (or freed twice) would leave the free count well off the
        // pristine baseline -- only the bitmap and root dir stay allocated.
        guard let free = StructuralOracle.freeSectors(in: result.transcript),
              let capacity = StructuralOracle.capacitySectors(in: result.transcript) else {
            return XCTFail("no free/capacity to judge reclamation:\n\(result.transcript)")
        }
        XCTAssertGreaterThanOrEqual(free, capacity - 8,
                       "delete-while-open leaked clusters: only \(free)/\(capacity) sectors "
                     + "free, expected all but the bitmap/root reclaimed")
    }

    // ── Kill a writer mid-write ────────────────────────────────────────────────

    /// A lone writer extends a file slowly; part way through, its process is
    /// killed with the file still open. The kernel's process-death cleanup
    /// (`F$Exit` closing the dying process's paths) must leave the filesystem
    /// consistent -- a half-written file is fine, a cross-linked or half-freed
    /// cluster is not.
    ///
    /// The writer is the only backgrounded process, so it is proc 3 (`Live`: the
    /// shell's `&` reply is `+3`); `kill 3` after a short sleep lands mid-write.
    func testKillingAWriterMidWriteLeavesTheImageIntact() throws {
        let file = "/h9/victim.dat"
        let scenario = Scenario(name: "kill-mid-write",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file,
                                                     count: 100, nap: 3, napMode: .sleep)],
                                timeout: 60,
                                midFlight: ["sleep 40", "kill 3"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut,
                       "kill-mid-write hung -- the dead writer's path was never reaped:\n"
                     + result.transcript)

        // It must really have died mid-write: a writer that finished all 100
        // records before the kill proves nothing about interrupted writes.
        XCTAssertFalse(result.transcript.contains("worker 1 wrote 100"),
                       "writer finished before the kill -- it was not interrupted:\n"
                     + result.transcript)

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "killing a writer mid-write left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }

    // ── Delete several growing files at once ───────────────────────────────────

    /// ★ Was a REAL FINDING (2026-07-21), now FIXED: deleting a file still open
    /// for WRITE leaked every cluster allocated after the delete, because
    /// `DeallocateBlocks` runs once at delete time and no later close frees what
    /// the still-open writer keeps adding. The fix matches canonical OS-9 -- RBF
    /// now refuses the delete with `E$Share` (253) while any other path holds the
    /// file open for write, exactly as real NitrOS-9 does (which is why that
    /// reference never had the leak). This test guards the fix: four workers grow
    /// their own files, all four are `del`eted mid-write, and each delete must be
    /// REFUSED while the device stays structurally intact. A regression that
    /// allowed the delete again would drop the E_SHARE refusals AND make the
    /// orphaned-cluster oracle fire -- both loud. See FAILABILITY.md.
    func testDeletingFilesOpenForWriteIsRefusedWithShare() throws {
        let files = (1...4).map { "/h9/churn\($0).dat" }
        let roster = files.enumerated().map { index, file in
            WorkerSpec(id: index + 1, role: .append, file: file,
                       count: 40, nap: 2, napMode: .sleep)
        }
        let scenario = Scenario(name: "delete-during-write",
                                backend: .rbfImage, workers: roster, timeout: 120,
                                midFlight: ["sleep 40"] + files.map { "del \($0)" })
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut, "delete-during-write hung:\n\(result.transcript)")

        // The del must land mid-write: each worker finishing its 40 records proves
        // it held the file open for write across the delete attempt, so a refusal
        // here is a refusal of a genuinely-busy file, not of an idle one.
        for id in 1...4 {
            XCTAssertTrue(result.transcript.contains("worker \(id) wrote 40"),
                          "worker \(id) did not finish -- the del may not have raced a live writer:\n"
                        + result.transcript)
        }

        // Canonical OS-9: every delete of a file open for write is refused. The
        // `E$Share` code proves it is the busy-file refusal specifically, not some
        // unrelated error standing in for it.
        XCTAssertTrue(result.transcript.contains("E_SHARE"),
                      "no E_SHARE refusal -- the busy-file delete was not rejected:\n"
                    + result.transcript)
        for file in files {
            XCTAssertTrue(result.transcript.contains("can't delete '\(file)'"),
                          "delete of open-for-write '\(file)' was not refused:\n"
                        + result.transcript)
        }

        // The integrity guarantee the leak violated: no orphaned clusters.
        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "delete-during-write left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")
    }

    /// Isolation for the finding above: one writer, but the `del` waits until the
    /// writer has FINISHED and CLOSED. This reclaims cleanly -- proving the leak
    /// is writing-to-a-deleted-file, not delete itself.
    func testLeakIsolation_deleteAfterClose() throws {
        let file = "/h9/isolate.dat"
        let scenario = Scenario(name: "delete-after-close",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file, count: 20)],
                                timeout: 60,
                                midFlight: ["w", "del \(file)"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)
        XCTAssertTrue(result.transcript.contains("worker 1 wrote 20"),
                      "precondition: the writer should finish before the del:\n\(result.transcript)")
        guard let free = StructuralOracle.freeSectors(in: result.transcript),
              let capacity = StructuralOracle.capacitySectors(in: result.transcript) else {
            return XCTFail("no free/capacity:\n\(result.transcript)")
        }
        XCTAssertGreaterThanOrEqual(free, capacity - 8,
                       "delete-after-close should reclaim cleanly but leaked: \(free)/\(capacity)")
        XCTAssertEqual(StructuralOracle.structuralViolations(dcheck: result.transcript), [],
                       "delete-after-close left the image damaged:\n\(result.transcript)")
    }

    // ── Truncate ───────────────────────────────────────────────────────────────

    /// A file is pre-extended to 200 records (~50 sectors), then truncated to
    /// 320 bytes with `SS.Size` (the `trunc` helper, since the shell has no
    /// truncate). Two things must hold: the file really shrinks (it reads back
    /// at the new length), and the device stays structurally consistent.
    ///
    /// It also documents a live FINDING: os9exec's `SS.Size` shrink sets the
    /// logical size but does NOT release the truncated tail's clusters. The
    /// handler `pRsetsz` (file_rbf.c ~3995) calls `Set_FDSize`/`RingSetLastPos`
    /// but never `ReleaseBlocks`, so the ~48 tail sectors stay allocated to the
    /// file -- reclaimed only when it is deleted, not on the truncate. `dcheck`
    /// stays intact precisely because the clusters remain in the file's own
    /// segment list (not orphaned), so this is un-reclaimed space, not a tear.
    /// Standard OS-9 RBF frees the tail on shrink; the reclamation assertion is
    /// therefore wrapped in `XCTExpectFailure` so the suite is green today and
    /// flips to failing the moment `pRsetsz` is fixed -- a reminder to delete
    /// the wrapper then. (A 6809/NitrOS-9 cross-check to nail the divergence is
    /// noted in FAILABILITY.md.)
    func testTruncatingAFileShrinksItAndStaysIntact() throws {
        let file = "/h9/tr.dat"
        // os9exec cannot fork a binary straight from the host-directory scratch,
        // so the helper is copied onto the RBF image, run there, then removed --
        // leaving only the truncated file, so the free count reflects just it.
        let scenario = Scenario(name: "truncate",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 99, role: .create, file: file, count: 200)],
                                midFlight: ["copy /h5/trunc /h9/trunc",
                                            "/h9/trunc \(file) 320",
                                            "del /h9/trunc"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)

        XCTAssertFalse(result.timedOut, "truncate run hung:\n\(result.transcript)")

        // The truncate really happened: the file now reads back at 320 bytes,
        // not the ~25600 it held after pre-extension. Without this the whole
        // test could pass on a trunc that silently did nothing.
        guard let data = result.produced[file] else {
            return XCTFail("tr.dat was not retrieved:\n\(result.transcript)")
        }
        XCTAssertEqual(data.count, 320,
                       "trunc should have set the size to 320 bytes, got \(data.count)")

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "truncate left the image damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nScratch kept at \(result.scratchPath)")

        // FINDING (see the doc comment): the tail's ~48 sectors are NOT freed on
        // truncate, so free stays well short of capacity. When pRsetsz learns to
        // release the tail, this block will pass and XCTExpectFailure will flag
        // the stale wrapper for removal.
        XCTExpectFailure("os9exec SS.Size truncate does not reclaim the tail (pRsetsz: no ReleaseBlocks)") {
            guard let free = StructuralOracle.freeSectors(in: result.transcript),
                  let capacity = StructuralOracle.capacitySectors(in: result.transcript) else {
                return XCTFail("no free/capacity to judge the truncate:\n\(result.transcript)")
            }
            XCTAssertGreaterThanOrEqual(free, capacity - 8,
                           "truncate did not free the tail: only \(free)/\(capacity) sectors free "
                         + "-- the file should be down to a couple of sectors")
        }
    }

    // ── Stale-sector disclosure ──────────────────────────────────────────────────

    /// Growing a file with `SS.Size` must not hand back another file's freed
    /// contents. Fill a tiny device with a recognisable filler pattern, delete
    /// it (freeing those clusters with the pattern still physically on the
    /// media), then create a one-line victim file and `SS.Size`-GROW it into the
    /// just-freed space. Whatever the grow exposes must read back as zeros, or
    /// the read must stop at the real allocated end -- it must NEVER surface the
    /// deleted filler's bytes.
    ///
    /// `pRsetsz` (file_rbf.c ~3995) sets the logical size without allocating or
    /// zeroing, so this probes directly whether a grown region can disclose a
    /// deleted file.
    ///
    /// ★ FINDING (reproduced, CANDIDATE): it CAN. The grown victim reads back
    /// the deleted filler's `unwritten slot` records verbatim -- a confidentiality
    /// leak of another file's freed data. Pinned with `XCTExpectFailure` (the
    /// assertion is the safe invariant, so it fails and is cataloged) rather than
    /// asserted clean, because this may be faithful to real OS-9 RBF, which does
    /// not zero space grown via `SS.Size` -- the owner (a firsthand OS-9 author)
    /// can say whether os9exec should diverge and zero it. Either way the suite
    /// now records the disclosure. See FAILABILITY.md and the truncate finding
    /// (same `pRsetsz` block-list mishandling).
    func testGrowingAFileViaSetSizeDoesNotDiscloseDeletedData() throws {
        let filler = "/h9/filler.dat", victim = "/h9/victim.dat"
        // 400 x 64B far exceeds a 16K image, so the create worker fills it to
        // E_FULL, stamping "unwritten slot" across every cluster. Deleting it
        // frees them all; the victim's grow can then only draw from that pool.
        let scenario = Scenario(name: "disclosure",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 99, role: .create, file: filler, count: 400)],
                                deviceKB: 16,
                                midFlight: ["del \(filler)",
                                            "copy /h5/trunc /h9/trunc",
                                            "echo VICTIMHDR >\(victim)",
                                            "/h9/trunc \(victim) 12000",
                                            "del /h9/trunc",
                                            "copy \(victim) /h5/victim.dat"])
        let result = try Adapter68k(repoRoot: Self.repoRoot).run(scenario)
        dump(result)
        XCTAssertFalse(result.timedOut, "disclosure run hung:\n\(result.transcript)")

        let victimHost = URL(fileURLWithPath: result.scratchPath)
            .appendingPathComponent("victim.dat")
        guard let data = try? Data(contentsOf: victimHost) else {
            return XCTFail("victim.dat was not produced -- did the grow/copy run?\n"
                         + result.transcript)
        }
        // The filler stamped "unwritten slot" into every cluster it touched. If
        // any of that survives in the grown victim, the grow disclosed a deleted
        // file's contents.
        let bytes = [UInt8](data)
        let needle = [UInt8]("unwritten slot".utf8)
        let leaked = bytes.indices.contains { start in
            start + needle.count <= bytes.count
                && Array(bytes[start ..< start + needle.count]) == needle
        }
        XCTExpectFailure("SS.Size grow discloses a deleted file's data -- confidentiality leak") {
            XCTAssertFalse(leaked,
                           "SS.Size grow DISCLOSED deleted filler in the \(data.count)-byte victim "
                         + "-- a confidentiality leak. Scratch kept at \(result.scratchPath)")
        }
    }
}
