//
//  ScenarioTests.swift
//  RBFHammerScenarioTests
//
//  Hammer scenarios, each runnable standalone like any unit test:
//
//      swift test --package-path test --filter testFourWorkersAppendOnRAMDisk
//
//  These drive the real os9exec binary, so they are slower than the pure
//  RBFHammerCore tests and live in their own target to keep that separation
//  obvious. Everything they assert is checked by the same host-side oracles
//  the soak driver uses.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import XCTest
@testable import RBFHammerCore

final class ScenarioTests: XCTestCase {

    /// Repository root, four levels up from this file.
    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammerScenarioTests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// How many records each worker writes. Raise for a soak run:
    ///
    ///     RBF_HAMMER_RECORDS=200 swift test --filter ScenarioTests
    private static var records: Int {
        Int(ProcessInfo.processInfo.environment["RBF_HAMMER_RECORDS"] ?? "") ?? 8
    }

    /// Runs a scenario and applies every oracle to it.
    ///
    /// Fails the test on the first oracle that objects, naming which one, so a
    /// red result says what kind of damage occurred rather than just "not
    /// equal".
    private func hammer(_ scenario: Scenario,
                        file: StaticString = #filePath, line: UInt = #line) throws {
        let adapter = try Adapter68k(repoRoot: Self.repoRoot)
        let result = try adapter.run(scenario)

        XCTAssertFalse(result.timedOut,
                       "scenario '\(scenario.name)' hung -- a parked worker never woke. "
                     + "Scratch kept at \(result.scratchPath)", file: file, line: line)

        for expected in scenario.files {
            guard let data = result.produced[expected] else {
                XCTFail("scenario '\(scenario.name)': \(expected) was never produced. "
                      + "Transcript:\n\(result.transcript)", file: file, line: line)
                continue
            }
            let violations = Verifier.verify(data: data,
                                             expecting: scenario.expectations(forFile: expected))
            XCTAssertEqual(violations, [],
                           "scenario '\(scenario.name)' content violations in \(expected):\n"
                         + violations.map(\.detail).joined(separator: "\n"),
                           file: file, line: line)
        }

        XCTAssertFalse(result.transcript.contains("FAIL"),
                       "a worker reported failure:\n\(result.transcript)",
                       file: file, line: line)
    }

    // ── Single worker, one per backend ────────────────────────────────────────
    // The floor. If these do not pass, nothing about contention means anything.

    func testOneWorkerAppendsOnHostDirectory() throws {
        try hammer(Scenario(
            name: "one-worker-host",
            backend: .hostDirectory,
            workers: [WorkerSpec(id: 1, role: .append, file: "/h5/hammer.dat",
                                 count: Self.records)]))
    }

    func testOneWorkerAppendsOnRAMDisk() throws {
        try hammer(Scenario(
            name: "one-worker-ramdisk",
            backend: .ramDisk,
            workers: [WorkerSpec(id: 1, role: .append, file: "/ram9/hammer.dat",
                                 count: Self.records)]))
    }

    func testOneWorkerAppendsOnRBFImage() throws {
        try hammer(Scenario(
            name: "one-worker-rbfimage",
            backend: .rbfImage,
            workers: [WorkerSpec(id: 1, role: .append, file: "/h9/hammer.dat",
                                 count: Self.records)]))
    }

    // ── Several workers, separate files ───────────────────────────────────────
    // Contention for the DEVICE and its allocator, not for one file's records.
    // This is where a broken free-list or a cross-linked sector shows up.

    func testFourWorkersAppendSeparateFilesOnRBFImage() throws {
        let workers = (1...4).map {
            WorkerSpec(id: $0, role: .append, file: "/h9/w\($0).dat",
                       count: Self.records, nap: 1)
        }
        try hammer(Scenario(name: "four-workers-separate-rbfimage",
                            backend: .rbfImage, workers: workers))
    }

    func testFourWorkersAppendSeparateFilesOnRAMDisk() throws {
        let workers = (1...4).map {
            WorkerSpec(id: $0, role: .append, file: "/ram9/w\($0).dat",
                       count: Self.records, nap: 1)
        }
        try hammer(Scenario(name: "four-workers-separate-ramdisk",
                            backend: .ramDisk, workers: workers))
    }

    // ── The same roster with the tick OFF ─────────────────────────────────────
    // `-q` is the documented fallback, and a task essentially runs to
    // completion there, so interleaving has to come from the voluntary naps.
    // Running the identical roster both ways is what makes the tick the only
    // variable.

    // ── Many workers, ONE file ────────────────────────────────────────────────
    // The main event. Every worker holds its own path onto the same file, so
    // this is where the FD-sharing ring, the shared sector buffers, the segment
    // list and the published size are all exercised at once. Separate-file
    // scenarios cannot reach any of that.

    /// Builds a roster of `count` slot-writers plus the provisioning worker.
    private func sharedRoster(_ population: Int, file: String, nap: Int) -> [WorkerSpec] {
        // The provisioning worker's count is the file's FULL final slot count,
        // because it pre-extends the file. OS-9 cannot write into a hole: a
        // slot worker seeking past the current end of file dies with E$EOF,
        // which reads back as that worker's whole range missing.
        var roster = [WorkerSpec(id: 99, role: .create, file: file,
                                 count: population * Self.records)]
        roster += (1...population).map {
            WorkerSpec(id: $0, role: .slot, file: file, count: Self.records, nap: nap)
        }
        return roster
    }

    func testFourWorkersShareOneFileOnRBFImage() throws {
        try hammer(Scenario(name: "four-workers-shared-rbfimage",
                            backend: .rbfImage,
                            workers: sharedRoster(4, file: "/h9/shared.dat", nap: 1)))
    }

    func testFourWorkersShareOneFileOnRAMDisk() throws {
        try hammer(Scenario(name: "four-workers-shared-ramdisk",
                            backend: .ramDisk,
                            workers: sharedRoster(4, file: "/ram9/shared.dat", nap: 1)))
    }

    func testFourWorkersShareOneFileOnHostDirectory() throws {
        try hammer(Scenario(name: "four-workers-shared-host",
                            backend: .hostDirectory,
                            workers: sharedRoster(4, file: "/h5/shared.dat", nap: 1)))
    }

    /// Twelve workers on one file. "Some can go crazy" -- the population is the
    /// variable most likely to expose an allocator or ring defect that four
    /// workers never reach.
    func testTwelveWorkersShareOneFileOnRBFImage() throws {
        try hammer(Scenario(name: "twelve-workers-shared-rbfimage",
                            backend: .rbfImage,
                            workers: sharedRoster(12, file: "/h9/shared.dat", nap: 1),
                            timeout: 120))
    }

    func testFourWorkersShareOneFileTickOff() throws {
        try hammer(Scenario(name: "four-workers-shared-tickoff",
                            backend: .rbfImage,
                            workers: sharedRoster(4, file: "/h9/shared.dat", nap: 2),
                            tick: .disabled))
    }

    func testFourWorkersAppendSeparateFilesTickOff() throws {
        let workers = (1...4).map {
            WorkerSpec(id: $0, role: .append, file: "/h9/w\($0).dat",
                       count: Self.records, nap: 1)
        }
        try hammer(Scenario(name: "four-workers-separate-tickoff",
                            backend: .rbfImage, workers: workers, tick: .disabled))
    }
}
