//
//  Adapter68k.swift
//  RBFHammerCore
//
//  Runs a scenario against os9exec, the 68k target.
//
//  Isolation follows the pattern the existing suite already proved necessary:
//  a device root private to this run, and the emulator's working directory set
//  to it so `mount -k` images land there too. A shared scratch previously let
//  two suites delete each other's fixtures and produced failures that looked
//  exactly like regressions.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// What a scenario run produced.
public struct RunResult: Sendable {

    /// Everything the emulator wrote to stdout and stderr.
    public let transcript: String

    /// Files the workers produced, keyed by their OS-9 path.
    public let produced: [String: Data]

    /// True when the run had to be killed rather than finishing on its own.
    /// A hang is a defect in the wait/wake path, not a slow machine.
    public let timedOut: Bool

    /// Where the run's scratch device lives, kept when a run fails so the
    /// disk can be inspected.
    public let scratchPath: String
}

/// Anything that can run a scenario on some target.
public protocol Adapter {

    /// Runs one scenario to completion and collects what it produced.
    func run(_ scenario: Scenario) throws -> RunResult
}

/// Runs scenarios against the locally built os9exec binary.
public struct Adapter68k: Adapter {

    /// Repository root, containing `os9exec` and `h0`.
    private let repoRoot: URL

    /// The hammer worker template.
    private let template: String

    /// Creates an adapter.
    ///
    /// - Parameter repoRoot: Directory holding `os9exec`, `h0`, and
    ///   `test/rbf-hammer/hammer.bas`.
    public init(repoRoot: URL) throws {
        self.repoRoot = repoRoot
        let templateURL = repoRoot
            .appendingPathComponent("test/rbf-hammer/hammer.bas")
        self.template = try String(contentsOf: templateURL, encoding: .utf8)
    }

    /// Runs one scenario and returns what the workers produced.
    public func run(_ scenario: Scenario) throws -> RunResult {
        let scratch = try makeScratch()
        for worker in scenario.workers {
            try writeScript(for: worker, in: scratch)
        }
        // Stage the truncate helpers (OS-9/68k binaries) alongside the scripts,
        // so a scenario's midFlight can `/h5/trunc <file> <bytes>` -- the shell
        // has no way to shrink a file, so these small SS.Size programs are it.
        // `trunc` leaves the pointer at 0 (RBF preserves the tail for random
        // access); `truncsk` seeks to the new EOF so close-time truncation runs
        // and releases the tail.
        for helper in ["trunc", "truncsk"] {
            try? FileManager.default.copyItem(
                at: repoRoot.appendingPathComponent("test/rbf-hammer/\(helper)"),
                to: scratch.appendingPathComponent(helper))
        }
        let outcome = try launch(scenario, scratch: scratch)
        let produced = collect(scenario, from: scratch)
        let result = RunResult(transcript: outcome.transcript, produced: produced,
                               timedOut: outcome.timedOut, scratchPath: scratch.path)
        return result
    }

    // ── Scratch device ────────────────────────────────────────────────────────

    /// Creates a device root private to this run.
    private func makeScratch() throws -> URL {
        let scratch = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("rbfhammer-\(ProcessInfo.processInfo.processIdentifier)"
                                  + "-\(UUID().uuidString.prefix(8))")
        try FileManager.default.createDirectory(at: scratch, withIntermediateDirectories: true)
        try? FileManager.default.createSymbolicLink(
            atPath: scratch.appendingPathComponent("h0").path,
            withDestinationPath: repoRoot.appendingPathComponent("h0").path)
        return scratch
    }

    // ── Worker scripts ────────────────────────────────────────────────────────

    /// Writes one worker's BASIC09 command script into the scratch device.
    ///
    /// The script is CR-terminated, not LF: BASIC09 reading an LF-terminated
    /// script silently does nothing useful, which presents as an empty run
    /// rather than an error.
    private func writeScript(for worker: WorkerSpec, in scratch: URL) throws {
        let script = WorkerScript.render(worker, from: template)
        try Data(script.utf8).write(to: scratch.appendingPathComponent(scriptName(worker)))
    }

    /// Filename of one worker's script, on the host and inside OS-9 alike.
    private func scriptName(_ worker: WorkerSpec) -> String {
        "w\(worker.id).s"
    }

    // ── Running ───────────────────────────────────────────────────────────────

    /// Builds the shell command sequence for a scenario.
    private func commands(for scenario: Scenario) -> [String] {
        var lines = ["chx /dd/CMDS", "load math cio"]
        lines += Backend68k.setup(scenario.backend, deviceKB: scenario.deviceKB)

        // Provisioning workers run FIRST and in the foreground. A shared file
        // must exist before the racers open it, and two workers both CREATEing
        // it is itself an error that would mask whatever the race did.
        let (provision, racers) = scenario.workers.partitioned { $0.role == .create || $0.role == .seed }
        lines += provision.map { "basic #32k </h5/\(scriptName($0))" }

        // One combined line, not one per worker: sending each launch separately
        // has been found unreliable in this project's history -- dropped,
        // delayed, or interleaved with the previous process's output.
        lines.append(racers.map { "basic #32k </h5/\(scriptName($0))&" }.joined())

        // The destructive act, if any: fired while the racers are running and
        // still hold the file open (delete it, kill a writer, truncate it).
        lines += scenario.midFlight

        // `w` waits for exactly ONE child, so the roster needs one per racer.
        // Waiting for fewer reads the files while workers are still writing and
        // manufactures torn-record violations that are the harness's own fault.
        lines += Array(repeating: "w", count: racers.count)
        lines += Backend68k.retrieve(scenario)
        lines += Backend68k.inspect(scenario.backend)
        return lines
    }

    /// Starts os9exec, feeds it the scenario, and waits for it with a deadline.
    private func launch(_ scenario: Scenario,
                        scratch: URL) throws -> (transcript: String, timedOut: Bool) {
        let process = Process()
        process.executableURL = repoRoot.appendingPathComponent("os9exec")
        process.currentDirectoryURL = scratch
        process.arguments = (scenario.tick == .disabled ? ["-q"] : []) + ["-r", "shell"]
        process.environment = [
            "OS9DISK": repoRoot.appendingPathComponent("h0").path,
            "OS9H5": scratch.path
        ]

        let input = Pipe(), output = Pipe()
        process.standardInput = input
        process.standardOutput = output
        process.standardError = output

        try process.run()
        let script = commands(for: scenario).joined(separator: "\n") + "\n\u{1B}\n"
        input.fileHandleForWriting.write(Data(script.utf8))
        input.fileHandleForWriting.closeFile()

        let collected = DispatchQueue(label: "hammer.read")
        var transcript = Data()
        collected.async { transcript = output.fileHandleForReading.readDataToEndOfFile() }

        let deadline = Date().addingTimeInterval(scenario.timeout)
        while process.isRunning, Date() < deadline {
            Thread.sleep(forTimeInterval: 0.05)
        }
        let timedOut = process.isRunning
        if timedOut { process.terminate() }
        process.waitUntilExit()
        collected.sync { }
        // ISO Latin-1 maps every byte 1:1 and never fails, so an emulator
        // transcript survives intact. A lossy UTF-8 decode would replace
        // stray bytes with U+FFFD and quietly edit the evidence.
        return (String(bytes: transcript, encoding: .isoLatin1) ?? "", timedOut)
    }

    /// Reads back everything the workers produced.
    ///
    /// Files on a RAM disk or an RBF image are copied to the host-visible
    /// device by the scenario's own commands first, since the host cannot read
    /// either one directly.
    private func collect(_ scenario: Scenario, from scratch: URL) -> [String: Data] {
        var produced: [String: Data] = [:]
        for file in scenario.files {
            let hostName = (file as NSString).lastPathComponent
            let url = scratch.appendingPathComponent(hostName)
            if let data = try? Data(contentsOf: url) {
                produced[file] = data
            }
        }
        return produced
    }
}

private extension Array {

    /// Splits into the elements matching `predicate` and those that do not,
    /// preserving order in both.
    func partitioned(_ predicate: (Element) -> Bool) -> ([Element], [Element]) {
        (filter(predicate), filter { !predicate($0) })
    }
}
