//
//  Adapter6809.swift
//  RBFHammerCore
//
//  Runs a scenario against real NitrOS-9 on an emulated CoCo3 (XRoar).
//
//  The 68k adapter can hand os9exec a host directory and read the results back
//  directly. Nothing here is that convenient: the guest's world is a single
//  134MB IDE container, so worker scripts go IN and produced files come OUT by
//  editing the RBF filesystem host-side with ToolShed while the emulator is
//  stopped. The emulator is driven in between through tools/nitros9repl.sh.
//
//  Every run works on a THROWAWAY CLONE of the golden master, never the master
//  itself. On APFS that clone is copy-on-write and costs about five
//  milliseconds, so there is no reason to economise on it.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// Runs scenarios against NitrOS-9 under XRoar.
public struct Adapter6809: Adapter {

    /// Something the 6809 environment could not provide.
    public enum Failure: Error, CustomStringConvertible {

        /// A host tool the adapter shells out to is missing.
        case missingTool(String)

        /// The emulator booted against an image other than this run's clone.
        case wrongImageAttached(expected: String, actual: String)

        /// The emulator never reached a usable shell.
        case bootFailed(String)

        public var description: String {
            switch self {
            case .missingTool(let path):
                return "required tool not found: \(path)"
            case .wrongImageAttached(let expected, let actual):
                return "REFUSING TO RUN: XRoar has \(actual) open, not this run's clone "
                     + "\(expected). A scenario that ran here would write to a disk it does "
                     + "not own -- possibly the golden master."
            case .bootFailed(let detail):
                return "NitrOS-9 did not reach a shell prompt: \(detail)"
            }
        }
    }

    /// Repository root, holding `tools/nitros9repl.sh` and the hammer template.
    private let repoRoot: URL

    /// The pristine image directory. Read from, never written to.
    private let goldenMaster: URL

    /// ToolShed's `os9` binary, which edits the RBF filesystem host-side.
    private let toolShed: URL

    /// The hammer worker template.
    private let template: String

    /// Byte offset of the OS-9 partition inside the `.ide` container.
    ///
    /// Verified rather than assumed: at this offset the container holds an RBF
    /// LSN0 whose volume name is "NitrOS-9 EOU 6809", and the bytes match the
    /// separately extracted `partition.img` exactly. ToolShed cannot read the
    /// `.ide` container itself, only a raw partition.
    static let partitionOffset = 323_584

    /// Sector size the offset is expressed in for `dd`.
    private static let sectorSize = 512

    /// Marker the run procedure echoes when every worker has been waited for.
    private static let doneMarker = "HAMMER-DONE"

    /// Creates an adapter.
    ///
    /// - Parameters:
    ///   - repoRoot: Directory holding `tools/nitros9repl.sh` and
    ///     `test/rbf-hammer/hammer.bas`.
    ///   - goldenMaster: Image directory to clone. Defaults to the NitrOS-9
    ///     EOU disk the REPL normally boots.
    public init(repoRoot: URL, goldenMaster: URL? = nil) throws {
        self.repoRoot = repoRoot
        let nitros9 = repoRoot.deletingLastPathComponent()
            .appendingPathComponent("os9/nitros9")
        self.goldenMaster = goldenMaster ?? nitros9
            .appendingPathComponent("disk-images/eou_ide-v0.3-6809-xroar-dw-becker")
        self.toolShed = nitros9.appendingPathComponent("tools/toolshed/build/unix/os9/os9")
        self.template = try String(
            contentsOf: repoRoot.appendingPathComponent("test/rbf-hammer/hammer.bas"),
            encoding: .utf8)
        guard FileManager.default.isExecutableFile(atPath: toolShed.path) else {
            throw Failure.missingTool(toolShed.path)
        }
    }

    // ── The run ───────────────────────────────────────────────────────────────

    /// Runs one scenario to completion and collects what it produced.
    public func run(_ scenario: Scenario) throws -> RunResult {
        let device = try Backend6809.device(scenario.backend)
        let run = try Run(clone: makeClone(), session: "hammer-\(UUID().uuidString.prefix(8))")
        defer { teardown(run) }

        try inject(scenario, device: device, into: run)
        try boot(run)
        try assertAttachedImage(run)
        let outcome = execute(scenario, in: run)
        let produced = try collect(scenario, device: device, from: run)

        return RunResult(transcript: outcome.transcript, produced: produced,
                         timedOut: outcome.timedOut, scratchPath: run.clone.path)
    }

    /// One run's private emulator instance and disk.
    private struct Run {

        /// Directory holding this run's clone of the image and its ROM.
        let clone: URL

        /// tmux session name, unique so runs can proceed in parallel.
        let session: String

        /// XRoar's DriveWire becker port.
        let beckerPort: Int

        /// The port the `/N1` shell channel is re-exposed on.
        let chanPort: Int

        /// Where the partition is staged while ToolShed edits it.
        var partition: URL { clone.appendingPathComponent("partition.img") }

        /// The `.ide` container XRoar boots.
        var image: URL { clone.appendingPathComponent("68IDE.ide") }

        init(clone: URL, session: String) throws {
            self.clone = clone
            self.session = session
            // Ports must not collide with a plain interactive REPL (65504/6811)
            // or with another concurrent run.
            let offset = Int.random(in: 1...400)
            self.beckerPort = 65000 + offset
            self.chanPort = 7000 + offset
        }
    }

    // ── Cloning ───────────────────────────────────────────────────────────────

    /// Copies the golden master into a private directory for this run.
    ///
    /// `cp -c` asks APFS for a copy-on-write clone, so a 134MB image costs
    /// milliseconds and no disk space until written. XRoar needs the ROM
    /// alongside it because it loads the cartridge relative to its own working
    /// directory.
    private func makeClone() throws -> URL {
        let clone = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("rbfhammer6809-\(ProcessInfo.processInfo.processIdentifier)"
                                  + "-\(UUID().uuidString.prefix(8))")
        try FileManager.default.createDirectory(at: clone, withIntermediateDirectories: true)
        try shell("/bin/cp", ["-c", goldenMaster.appendingPathComponent("68IDE.ide").path,
                              clone.appendingPathComponent("68IDE.ide").path])
        try shell("/bin/cp", [goldenMaster.appendingPathComponent("hdblba.rom").path,
                              clone.appendingPathComponent("hdblba.rom").path])
        return clone
    }

    // ── Getting the workers onto the disk ─────────────────────────────────────

    /// Writes every worker script and the run procedure into the clone.
    private func inject(_ scenario: Scenario, device: String, into run: Run) throws {
        try extractPartition(run)

        var staged: [URL] = []
        let staging = run.clone.appendingPathComponent("staging")
        try FileManager.default.createDirectory(at: staging, withIntermediateDirectories: true)

        for worker in scenario.workers {
            let url = staging.appendingPathComponent(scriptName(worker))
            // Comments stripped: BASIC09 re-parses the whole template through
            // its editor, and comments cannot affect behaviour, only entry time.
            try Data(WorkerScript.render(worker, from: template,
                                         stripComments: true).utf8).write(to: url)
            staged.append(url)

            // Racers additionally get a PACK script: it builds the worker once
            // and packs it to module `hwork<id>`, so the racer can be launched
            // with `runb` (no editor at launch, so concurrent starts don't race
            // the editor). Provisioning stays a plain run -- it goes first, one
            // at a time, so it never races anything.
            if worker.role != .create && worker.role != .seed {
                let pack = staging.appendingPathComponent(packScriptName(worker))
                try Data(WorkerScript.renderPack(worker, from: template).utf8).write(to: pack)
                staged.append(pack)
            }
        }
        // The old-style single procedure file, staged so the diagnostic
        // `RBF_DRIVE=procfile` mode can drive the whole roster with one
        // `shell </DD/run.s`. Harmless when the default one-at-a-time driving
        // is used -- it just sits on the disk unread.
        let runProc = staging.appendingPathComponent("run.s")
        try Data(renderRunProcedure(scenario, device: device).utf8).write(to: runProc)
        staged.append(runProc)

        for file in staged {
            try shell(toolShed.path,
                      ["copy", file.path, "\(run.partition.path),/\(file.lastPathComponent)"])
        }
        try writePartitionBack(run)
    }

    /// Filename of one worker's run script.
    private func scriptName(_ worker: WorkerSpec) -> String { "w\(worker.id).s" }

    /// Filename of one racer's build-and-pack script.
    private func packScriptName(_ worker: WorkerSpec) -> String { "w\(worker.id)p.s" }

    /// Name of the packed module a racer is launched by (`runb`).
    private func moduleName(_ worker: WorkerSpec) -> String { "hwork\(worker.id)" }

    /// Renders the old-style procedure file that launches the whole roster.
    ///
    /// This is the driving that produced the `What?` flood. Kept only so the
    /// flood can be reproduced ON DEMAND (`RBF_DRIVE=procfile`) and its cause
    /// pinned down, rather than described from memory. Provisioning workers run
    /// foreground first; racers are backgrounded; one `w` per racer waits for
    /// them; then the done marker. Byte-for-byte the sequence the default
    /// driving issues one command at a time, but handed to the shell as a file.
    private func renderRunProcedure(_ scenario: Scenario, device: String) -> String {
        let (provision, racers) = scenario.workers
            .partitioned { $0.role == .create || $0.role == .seed }
        var lines = ["chd \(device)"]
        lines += provision.map { "basic09 #32k </DD/\(scriptName($0))" }
        lines += racers.map { "basic09 #32k </DD/\(scriptName($0))&" }
        lines += racers.map { _ in "w" }
        lines.append("echo \(Self.doneMarker)")
        return lines.joined(separator: "\r") + "\r"
    }

    // ── Partition plumbing ────────────────────────────────────────────────────

    /// Copies the OS-9 partition out of the `.ide` container so ToolShed can
    /// read it. ToolShed does not understand the container itself.
    private func extractPartition(_ run: Run) throws {
        try shell("/bin/dd", ["if=\(run.image.path)", "of=\(run.partition.path)",
                              "bs=\(Self.sectorSize)",
                              "skip=\(Self.partitionOffset / Self.sectorSize)"])
    }

    /// Writes the edited partition back into the container in place.
    private func writePartitionBack(_ run: Run) throws {
        try shell("/bin/dd", ["if=\(run.partition.path)", "of=\(run.image.path)",
                              "bs=\(Self.sectorSize)",
                              "seek=\(Self.partitionOffset / Self.sectorSize)",
                              "conv=notrunc"])
    }

    // ── Driving the emulator ──────────────────────────────────────────────────

    /// Environment that points the REPL at this run's private clone and ports.
    private func replEnvironment(_ run: Run) -> [String: String] {
        var environment = ProcessInfo.processInfo.environment
        environment["NITROS9REPL_DISKDIR"] = run.clone.path
        environment["NITROS9REPL_SESSION"] = run.session
        environment["NITROS9REPL_BECKER_PORT"] = String(run.beckerPort)
        environment["NITROS9REPL_CHAN_PORT"] = String(run.chanPort)
        // 2MB, not the stock 512K CoCo3. A 512K machine leaves only ~304K free
        // after the resident OS, and a roster of several `#32k` BASIC09 workers
        // each forking `SHELL "sleep"` exhausts it -- Error #237 (RAM Full),
        // which the guest surfaces as a debugger flood (see execute()). NitrOS-9
        // EOU detects and uses the expansion: `mfree` reports 1824K free here
        // versus ~304K at 512K. This lifts the memory ceiling so the hammer can
        // actually run many concurrent writers, which is the whole point of it.
        environment["NITROS9REPL_EXTRA_XROAR"] = "-no-ratelimit -ram 2048"
        return environment
    }

    /// Path to the REPL driver script.
    private var repl: String { repoRoot.appendingPathComponent("tools/nitros9repl.sh").path }

    /// Boots NitrOS-9 on this run's clone.
    private func boot(_ run: Run) throws {
        let output = try shell(repl, ["start"], environment: replEnvironment(run))
        guard output.contains("ready") else {
            throw Failure.bootFailed(output)
        }
    }

    /// Refuses to continue unless XRoar really has THIS run's clone open.
    ///
    /// Not defensive padding: during development a `stop` left an XRoar alive,
    /// a later boot reused it, and the run wrote to the GOLDEN MASTER while
    /// every host-side check still looked correct -- the injected scripts were
    /// in the clone, so the guest simply reported "path not found". The disk a
    /// run writes to is the one fact that cannot be inferred from the guest's
    /// own output, so it is verified against the kernel's open-file table.
    private func assertAttachedImage(_ run: Run) throws {
        let pids = try shell("/usr/bin/pgrep", ["-f", "xroar -rompath"])
            .split(separator: "\n").map(String.init)
        let expected = Self.canonical(run.image.path)

        for pid in pids {
            let open = try? shell("/usr/sbin/lsof", ["-p", pid])
            guard let open, open.contains(run.clone.lastPathComponent) else { continue }
            let attached = open.split(separator: "\n")
                .first { $0.hasSuffix(".ide") }
                .flatMap { $0.split(separator: " ").last.map(String.init) }
                .map(Self.canonical)
            guard let attached, attached == expected else {
                throw Failure.wrongImageAttached(expected: expected,
                                                 actual: attached ?? "unknown")
            }
            return
        }
        throw Failure.wrongImageAttached(expected: expected,
                                         actual: "no XRoar holding this run's clone")
    }

    /// Resolves a path to its canonical form for comparison.
    ///
    /// Both sides must be resolved, not just one: macOS makes `/var` a symlink
    /// to `/private/var`, and `lsof` reports the resolved path while a
    /// temporary-directory URL keeps the unresolved one. Comparing those
    /// directly made this guard reject the very clone it had just created.
    private static func canonical(_ path: String) -> String {
        URL(fileURLWithPath: path).resolvingSymlinksInPath().path
    }

    /// Launches the run procedure and waits for it to report completion.
    ///
    /// Polls for the marker rather than using the REPL's own prompt gate: that
    /// gate has a fixed short timeout meant for interactive commands, whereas a
    /// hammer roster legitimately runs for minutes.
    private func execute(_ scenario: Scenario,
                         in run: Run) -> (transcript: String, timedOut: Bool) {
        let environment = replEnvironment(run)
        let device = (try? Backend6809.device(scenario.backend)) ?? "/DD"
        let (provision, racers) = scenario.workers
            .partitioned { $0.role == .create || $0.role == .seed }
        let deadline = Date().addingTimeInterval(scenario.timeout)

        // A cleared pane makes the marker search cheap and unambiguous: without
        // it the boot banner and any previous command's output scroll past
        // forever and every poll re-scans them.
        _ = try? shell("/usr/bin/env", ["tmux", "clear-history", "-t", "\(run.session):chan"],
                       environment: environment)

        // Diagnostic: drive the whole roster the OLD way, as one procedure file,
        // to reproduce the `What?` flood on demand. Off by default.
        if ProcessInfo.processInfo.environment["RBF_DRIVE"] == "procfile" {
            type("shell #32k </DD/run.s", in: run)
            guard let transcript = waitFor(Self.doneMarker, in: run, until: deadline) else {
                return (capture(run), true)
            }
            return (transcript, false)
        }

        type("chd \(device)", in: run)

        // Commands are typed at the shell ONE AT A TIME rather than fed as a
        // procedure file (`shell <run.s`). The procedure-file form floods the
        // channel with `What?` and leaves the shared file unwritten -- which
        // reads exactly like RBF dropping every concurrent writer, and is
        // nothing of the kind. The cause is now CONFIRMED (reproduced on demand
        // via RBF_DRIVE=procfile, traced live -- see FAILABILITY.md):
        //
        //   1. Under procedure-file driving the racers launch nearly at once,
        //      and the outer `shell #32k </DD/run.s` is an EXTRA #32k process on
        //      top of the four #32k basic09 workers.
        //   2. A racer reaches hnap and its `SHELL "sleep"` fork fails with
        //      Error #237 (RAM Full) -- the CoCo3 is simply out of memory.
        //   3. hnap has no ON ERROR, so the uncaught error BREAKs into BASIC09's
        //      interactive DEBUGGER (the `D:` prompt -- THAT is what prints
        //      `What?`, not the shell). The worker's stdin is its redirected
        //      script file, now at EOF, so the debugger spins reading past EOF
        //      forever: the unbounded `D:What?` flood.
        //
        // So it is memory exhaustion surfacing as a debugger spin -- NOT channel
        // corruption, NOT rapid `key`, and NOT an RBF fault. One-at-a-time
        // driving avoids it by not adding the procedure-file shell and by
        // staggering the launches, which keeps peak RAM under the limit. Do not
        // restore the "channel corruption" or "shared-stdin" explanations that
        // once stood here; both were tested and are false.
        for worker in provision {
            let marker = "PROV\(worker.id)DONE"
            type("basic09 #32k </DD/\(scriptName(worker))", in: run)
            type("echo \(marker)", in: run)
            guard waitFor(marker, in: run, until: deadline) != nil else {
                return (capture(run), true)
            }
        }

        // SETUP: build and pack each racer ONE AT A TIME. Building drives the
        // BASIC09 editor from a script file; doing several at once races the
        // editors and one hangs spinning at its `E:` prompt. Done sequentially,
        // nothing races, and the output is a standalone module `hwork<id>`.
        for worker in racers {
            let marker = "PACKED\(worker.id)"
            type("basic09 #32k </DD/\(packScriptName(worker))", in: run)
            type("echo \(marker)", in: run)
            guard waitFor(marker, in: run, until: deadline) != nil else {
                return (capture(run), true)
            }
        }

        // LAUNCH: `runb` the packed modules concurrently. There is no editor
        // phase now, so simultaneous starts are safe -- yet the workers still
        // run at the same time, which is what the rmw lock race needs.
        for worker in racers {
            type("runb \(moduleName(worker))&", in: run)
        }
        // Wait for each racer's OWN completion line rather than a `w` per racer
        // plus one `echo HAMMER-DONE`. A worker prints its line only after it
        // closes its file (or from its ON ERROR handler), so this guarantees the
        // files are flushed, needs no trailing command a dropped key-send could
        // lose (which hung the roster after all the work was already done), and
        // names any worker that never finishes in the timeout.
        guard let transcript = waitForWorkers(racers, in: run, until: deadline) else {
            return (capture(run), true)
        }
        return (transcript, false)
    }

    /// Polls until every racer has printed its own completion line, or the
    /// deadline passes. Each worker prints `hammer: worker <id> ...` exactly once
    /// when it finishes -- on a clean close or from ON ERROR. The trailing space
    /// keeps `worker 1 ` from matching `worker 12 `.
    private func waitForWorkers(_ racers: [WorkerSpec], in run: Run,
                                until deadline: Date) -> String? {
        while Date() < deadline {
            let transcript = capture(run)
            if racers.allSatisfy({ transcript.contains("worker \($0.id) ") }) {
                return transcript
            }
            Thread.sleep(forTimeInterval: 1.0)
        }
        return nil
    }

    /// Types one command at the guest shell, followed by Enter.
    private func type(_ command: String, in run: Run) {
        _ = try? shell(repl, ["key", command, "Enter"], environment: replEnvironment(run))
    }

    /// Polls the channel until `marker` appears, or the deadline passes.
    ///
    /// - Returns: The transcript containing the marker, or nil on timeout.
    private func waitFor(_ marker: String, in run: Run, until deadline: Date) -> String? {
        while Date() < deadline {
            let transcript = capture(run)
            if transcript.contains(marker) { return transcript }
            Thread.sleep(forTimeInterval: 1.0)
        }
        return nil
    }

    /// Current contents of the channel pane.
    private func capture(_ run: Run) -> String {
        (try? shell("/usr/bin/env",
                    ["tmux", "capture-pane", "-t", "\(run.session):chan", "-p", "-J",
                     "-S", "-3000"],
                    environment: replEnvironment(run))) ?? ""
    }

    // ── Getting results back ──────────────────────────────────────────────────

    /// Reads the produced files back out of the clone.
    ///
    /// The emulator is stopped first: RBF caches dirty sectors, so a file read
    /// out from under a live guest can legitimately be short or stale, which
    /// would look exactly like the data loss this harness hunts for.
    private func collect(_ scenario: Scenario, device: String,
                         from run: Run) throws -> [String: Data] {
        _ = try? shell(repl, ["stop"], environment: replEnvironment(run))
        try waitForEmulatorExit(run)
        try extractPartition(run)

        var produced: [String: Data] = [:]
        let outbox = run.clone.appendingPathComponent("outbox")
        try FileManager.default.createDirectory(at: outbox, withIntermediateDirectories: true)

        for file in scenario.files {
            let name = (file as NSString).lastPathComponent
            let destination = outbox.appendingPathComponent(name)
            _ = try? shell(toolShed.path,
                           ["copy", "\(run.partition.path),/\(name)", destination.path])
            if let data = try? Data(contentsOf: destination) {
                produced[file] = data
            }
        }
        return produced
    }

    /// Waits for XRoar to actually exit before touching the image.
    ///
    /// `stop` is not reliably fatal to XRoar -- a survivor once kept the image
    /// open and later overwrote host-side edits -- so this kills any straggler
    /// holding this run's clone rather than trusting the script's teardown.
    private func waitForEmulatorExit(_ run: Run) throws {
        for _ in 0..<40 {
            let pids = (try? shell("/usr/bin/pgrep", ["-f", "xroar -rompath"])) ?? ""
            let holders = pids.split(separator: "\n").map(String.init).filter { pid in
                let open = (try? shell("/usr/sbin/lsof", ["-p", pid])) ?? ""
                return open.contains(run.clone.lastPathComponent)
            }
            if holders.isEmpty { return }
            for pid in holders { _ = try? shell("/bin/kill", [pid]) }
            Thread.sleep(forTimeInterval: 0.25)
        }
    }

    /// Tears down this run's emulator and tmux session.
    private func teardown(_ run: Run) {
        _ = try? shell(repl, ["stop"], environment: replEnvironment(run))
        try? waitForEmulatorExit(run)
    }

    // ── Host process helper ───────────────────────────────────────────────────

    /// Runs a host command and returns its combined output.
    @discardableResult
    private func shell(_ launchPath: String, _ arguments: [String],
                       environment: [String: String]? = nil) throws -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: launchPath)
        process.arguments = arguments
        process.currentDirectoryURL = repoRoot
        if let environment { process.environment = environment }

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        try process.run()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        return String(bytes: data, encoding: .isoLatin1) ?? ""
    }
}

private extension Array {

    /// Splits into the elements matching `predicate` and those that do not,
    /// preserving order in both.
    func partitioned(_ predicate: (Element) -> Bool) -> ([Element], [Element]) {
        (filter(predicate), filter { !predicate($0) })
    }
}
