//
//  Backend6809.swift
//  RBFHammerCore
//
//  Which storage backends exist on NitrOS-9, and which do not.
//
//  The 68k emulator can conjure a backend per scenario (`mount -r`, `mount -k`,
//  a host directory). Real NitrOS-9 under XRoar cannot: it has the devices its
//  boot disk was built with. That asymmetry is the whole reason this file
//  exists as its own type rather than as a branch inside the adapter -- an
//  unsupported backend must be REFUSED loudly, never quietly redirected to
//  `/DD`. A scenario that silently ran somewhere other than where it claimed
//  would report a green for a code path that was never entered, which is the
//  precise failure this harness exists to prevent.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// Storage backends as they exist on the 6809 target.
public enum Backend6809 {

    /// Why a scenario cannot run on this target.
    public enum Unsupported: Error, CustomStringConvertible {

        /// The backend has no equivalent on NitrOS-9.
        case backend(Backend)

        public var description: String {
            switch self {
            case .backend(.hostDirectory):
                return "backend .hostDirectory does not exist on 6809: NitrOS-9 under XRoar "
                     + "has no host-passthrough device. Tag such scenarios 68k-only rather "
                     + "than running them here -- silently redirecting to /DD would report a "
                     + "pass for a path that was never exercised."
            case .backend(let other):
                return "backend \(other) is not implemented on the 6809 adapter"
            }
        }
    }

    /// The OS-9 device a backend's files live on.
    ///
    /// - Throws: ``Unsupported`` when the backend has no 6809 equivalent.
    public static func device(_ backend: Backend) throws -> String {
        switch backend {
        case .rbfImage:
            // The IDE hard disk the system booted from -- a real RBF device
            // with a real allocator, which is what the hammer is aimed at.
            return "/DD"
        case .ramDisk:
            // `Rammer`/`R0` are present in the boot module directory, but
            // provisioning them (iniz + format) has NOT been verified live,
            // and an unverified provision that silently no-ops would leave the
            // scenario running on /DD while claiming to be a RAM disk.
            throw Unsupported.backend(.ramDisk)
        case .hostDirectory:
            throw Unsupported.backend(.hostDirectory)
        }
    }
}
