//
//  Backend68k.swift
//  RBFHammerCore
//
//  The shell commands that provision, retrieve from, and inspect each storage
//  backend on os9exec.
//
//  These are genuinely different code paths inside RBF rather than
//  configuration of one path, which is why every scenario runs against all
//  three: a defect can easily appear on an RBF image and not on a host
//  directory, since the latter bypasses RBF's allocator entirely.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// Shell fragments for driving one storage backend on os9exec.
enum Backend68k {

    /// The OS-9 device a backend's files live on.
    static func device(_ backend: Backend) -> String {
        switch backend {
        case .ramDisk: return "/ram9"
        case .rbfImage: return "/h9"
        case .hostDirectory: return "/h5"
        }
    }

    /// Commands that bring the backend into existence before workers start.
    ///
    /// The host directory needs none: it is mounted by the emulator itself
    /// through `OS9H5`, which is exactly what makes it the backend the host can
    /// read back directly.
    static func setup(_ backend: Backend, deviceKB: Int = 500) -> [String] {
        switch backend {
        case .ramDisk: return ["mount -r=400 /ram9"]
        case .rbfImage: return ["mount -k=\(deviceKB)K h9"]
        case .hostDirectory: return []
        }
    }

    /// Commands that copy produced files somewhere the host can read them.
    ///
    /// A RAM disk has no host file behind it at all, and an RBF image is a
    /// container the host would have to parse, so both are copied out to the
    /// host-visible device rather than read in place.
    static func retrieve(_ scenario: Scenario) -> [String] {
        guard scenario.backend != .hostDirectory else { return [] }
        return scenario.files.map { file in
            "copy \(file) /h5/\((file as NSString).lastPathComponent)"
        }
    }

    /// Commands whose output the structural oracle reads.
    ///
    /// A host directory is not an RBF device, so neither tool applies to it --
    /// which is itself worth stating, since "no structural check ran" must not
    /// be mistaken for "the structural check passed".
    static func inspect(_ backend: Backend) -> [String] {
        guard backend != .hostDirectory else { return [] }
        let device = device(backend)
        return ["free \(device)", "dcheck \(device)"]
    }
}
