//
//  Record.swift
//  RBFHammerCore
//
//  The self-describing record every hammer worker writes.
//
//  Fixed width on purpose. A variable-length record makes a torn write
//  indistinguishable from a short one: you cannot tell whether the writer was
//  interrupted or simply wrote less. At a fixed stride, any trailing partial
//  record is unambiguously a torn write, and the offset of record N is known
//  without parsing records 0..<N -- which is what lets a reader verify a file
//  another process is still appending to.
//
//  Format, 64 bytes, CR-terminated (OS-9 ends lines in CR, not LF):
//
//      W99 S99999 C65535 P<payload padded to 44 chars>\r
//
//  Every field is fixed-width decimal so a 6809 BASIC09 worker can build it
//  with nothing but INTEGER arithmetic and string padding. The checksum is
//  taken modulo 65536 for the same reason: 6809 BASIC09's INTEGER is 16-bit,
//  so a wider checksum is literally unrepresentable on half our targets.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// One self-describing record in a hammer output file.
///
/// A record identifies which worker wrote it, where the record falls in that
/// worker's own sequence, and carries a checksum over its payload. Together
/// those let the verifier distinguish a lost write from a corrupted one from a
/// duplicated one -- classes of damage that a plain byte comparison reports
/// identically.
public struct Record: Equatable, Sendable {

    /// Total encoded size in bytes, including the trailing CR.
    public static let width = 64

    /// Width of the payload field, space-padded on the right.
    public static let payloadWidth = 44

    /// Modulus applied to the checksum so it fits a 6809 BASIC09 `INTEGER`.
    public static let checksumModulus = 65_536

    /// Which worker wrote this record. 0...99.
    public let worker: Int

    /// This record's position in its own worker's sequence. 0...99_999.
    public let sequence: Int

    /// The record's contents, with trailing padding removed.
    public let payload: String

    /// The checksum as it actually appeared in the encoded record.
    ///
    /// For a record built in memory this equals ``checksum``. For a record read
    /// back from a device the two differ exactly when the payload was corrupted
    /// in transit -- which is the whole point of carrying it.
    public let recordedChecksum: Int

    /// The checksum the payload should have.
    public var checksum: Int {
        Self.checksum(of: payload)
    }

    /// True when the payload matches the checksum stored alongside it.
    public var isIntact: Bool {
        recordedChecksum == checksum
    }

    /// Creates a record with a checksum computed from its payload.
    ///
    /// - Parameters:
    ///   - worker: Writing worker's id, 0...99.
    ///   - sequence: Position in that worker's sequence, 0...99_999.
    ///   - payload: Contents, at most ``payloadWidth`` characters.
    public init(worker: Int, sequence: Int, payload: String) {
        self.worker = worker
        self.sequence = sequence
        self.payload = payload
        self.recordedChecksum = Self.checksum(of: payload)
    }

    /// Creates a record from already-decoded fields, keeping the checksum that
    /// was found on the device rather than recomputing it.
    private init(worker: Int, sequence: Int, payload: String, recordedChecksum: Int) {
        self.worker = worker
        self.sequence = sequence
        self.payload = payload
        self.recordedChecksum = recordedChecksum
    }

    /// Sum of a payload's bytes, reduced to 16 bits.
    ///
    /// Deliberately trivial: a 6809 worker has to compute the identical value
    /// with 16-bit integer arithmetic, so anything stronger would not be
    /// reproducible on the guest side.
    public static func checksum(of payload: String) -> Int {
        payload.utf8.reduce(0) { ($0 + Int($1)) % checksumModulus }
    }

    /// Encodes the record to its fixed-width on-device representation.
    public func encode() -> String {
        let padded = payload.padding(toLength: Self.payloadWidth, withPad: " ", startingAt: 0)
        return String(format: "W%02d S%05d C%05d P", worker, sequence, recordedChecksum)
            + padded + "\r"
    }

    /// Decodes one fixed-width record.
    ///
    /// - Returns: The record, or `nil` when `text` is not exactly ``width``
    ///   characters or any field fails to parse. A `nil` here means the bytes
    ///   are not a record at all, which the verifier reports as a torn write --
    ///   so this must never repair or guess at malformed input.
    public static func decode(_ text: String) -> Record? {
        guard text.count == width, text.hasSuffix("\r") else { return nil }
        let fields = text.dropLast().split(separator: " ", maxSplits: 3,
                                           omittingEmptySubsequences: false)
        guard fields.count == 4 else { return nil }
        guard let worker = tagged(fields[0], "W"),
              let sequence = tagged(fields[1], "S"),
              let recorded = tagged(fields[2], "C"),
              fields[3].hasPrefix("P") else { return nil }
        let payload = String(fields[3].dropFirst())
            .replacingOccurrences(of: " +$", with: "", options: .regularExpression)
        return Record(worker: worker, sequence: sequence,
                      payload: payload, recordedChecksum: recorded)
    }

    /// Parses a `<letter><digits>` field, returning `nil` if the tag is wrong
    /// or the digits are not a number.
    private static func tagged(_ field: Substring, _ tag: Character) -> Int? {
        guard field.first == tag else { return nil }
        return Int(field.dropFirst())
    }
}
