//
//  Scenario.swift
//  RBFHammerCore
//
//  What a hammer run consists of, expressed as data.
//
//  A scenario names a storage backend, a roster of workers, and a scheduling
//  mode. Variety comes from combinations of these rather than from hand-written
//  programs, so "make it contend harder" is an edit to a value, not new code.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// Which OS-9 storage backend a scenario runs against.
///
/// These are genuinely different code paths inside RBF, not configuration of
/// one path, so a defect can easily appear on one and not the others.
public enum Backend: String, Equatable, Sendable, CaseIterable {

    /// `mount -r` — a filesystem built in memory, no host file behind it.
    case ramDisk

    /// `mount -k` — a real RBF image file, the closest thing to a physical disk.
    case rbfImage

    /// A host directory mapped in through `OS9Hx`, bypassing RBF's own
    /// allocation entirely.
    case hostDirectory
}

/// Whether the pre-emptive system tick runs during a scenario.
public enum TickMode: String, Equatable, Sendable {

    /// The default: 100Hz pre-emption, the configuration users actually get.
    case enabled

    /// `-q`, the documented fallback. A task essentially runs to completion,
    /// so interleaving has to come from workers yielding voluntarily.
    case disabled
}

/// How a worker gives up the CPU between its read and its write.
public enum NapMode: String, Equatable, Sendable {

    /// `SHELL "sleep <ticks>"` — a real F$Sleep block, ~10ms granularity.
    /// Verified on 68k. On 6809 the SHELL statement is documented only in the
    /// 68k manual and its availability is unconfirmed.
    case sleep

    /// A burst of writes to `/nil` — real syscalls, no timed block. Pure
    /// BASIC09, so it works wherever BASIC09 does. The portable floor.
    case nilWrites = "nil"
}

/// What one hammer worker does.
public struct WorkerSpec: Equatable, Sendable {

    /// The worker's identity, carried in every record it writes. 0...99.
    public let id: Int

    /// Which behaviour this worker performs.
    public let role: Role

    /// The file it operates on, as an OS-9 path.
    public let file: String

    /// How many records it writes, or reads.
    public let count: Int

    /// How much it yields between operations. Ticks for `.sleep`, iterations
    /// for `.nilWrites`. Zero means never yield.
    public let nap: Int

    /// Which yielding mechanism to use.
    public let napMode: NapMode

    /// What a worker does to the file.
    public enum Role: String, Equatable, Sendable {

        /// Extends the file with self-describing records.
        case append

        /// Walks the file back, counting whole records.
        case read

        /// Writes only the byte range this worker owns in a SHARED file:
        /// records `[base ..< base+count)` where `base = (id-1)*count`.
        ///
        /// Disjoint by construction. BASIC09 has no seek-to-end, so racing
        /// appenders would all write at offset 0 and overwrite each other --
        /// which would prove the test wrong, not the locking right. With
        /// computed slots, any cross-talk is unambiguously corruption.
        case slot

        /// Read-modify-writes ONE shared record that every other `rmw`
        /// worker also touches, so the locked extents OVERLAP.
        ///
        /// The only role that can detect a missing record lock: `LockHolder`
        /// reports a conflict only on overlap, and `slot` ranges are disjoint
        /// by construction.
        case rmw

        /// The same read-modify-write as `rmw` but through a READ path and a
        /// separate WRITE path, so no automatic lock is taken. The control
        /// that proves `rmw` can fail.
        case rmwfree

        /// Read-modify-writes ONE shared record with BINARY `GET`/`PUT` on a
        /// small integer array -- the exact shape of the proven 6809 lost-update
        /// reproduction (`rl-race3`). Unlike `rmw` (text `READ`/`PRINT`, whose
        /// lock serializes correctly), this exercises the binary `I$Read`/
        /// `I$Write` lock-retry path where a woken waiter re-presents a clobbered
        /// byte count and proceeds UNLOCKED -- the live data-loss bug. Pairs with
        /// `seedbin`.
        case rmwbin

        /// Writes a single record holding a decimal tally for `rmw` to
        /// increment.
        case seed

        /// Seeds the binary tally file for `rmwbin`: one small integer record,
        /// all zeros, written with `PUT`. The binary counterpart of `seed`.
        case seedbin

        /// Like `rmwbin` but a 400-byte MULTI-SECTOR record, to hammer the
        /// spanning-read lock path the single-sector 6809 fix may not cover.
        case rmwbig

        /// Seeds the 400-byte record for `rmwbig`.
        case seedbig

        /// Creates an empty file and exits, provisioning a shared file before
        /// racers start. Two workers both CREATEing one file is itself an
        /// error and would mask the result.
        case create
    }

    /// Creates a worker specification.
    public init(id: Int, role: Role, file: String, count: Int,
                nap: Int = 0, napMode: NapMode = .sleep) {
        self.id = id
        self.role = role
        self.file = file
        self.count = count
        self.nap = nap
        self.napMode = napMode
    }

    /// The first sequence number this worker writes.
    ///
    /// Zero for a worker that owns its whole file; its slot base when several
    /// workers share one.
    public var sequenceBase: Int {
        role == .slot ? (id - 1) * count : 0
    }

    /// What this worker claims it wrote, for the content oracle to check.
    public var expectation: WorkerExpectation {
        WorkerExpectation(worker: id,
                          count: (role == .append || role == .slot) ? count : 0,
                          firstSequence: sequenceBase)
    }
}

/// One complete hammer run: a backend, a roster, and a scheduling mode.
public struct Scenario: Equatable, Sendable {

    /// Short stable identifier, used in test names and failure reports.
    public let name: String

    /// Which storage backend to run against.
    public let backend: Backend

    /// The workers to run concurrently.
    public let workers: [WorkerSpec]

    /// Whether the pre-emptive tick runs.
    public let tick: TickMode

    /// Seconds before the run is declared hung. A hang is a real defect in the
    /// wait/wake path, so this is an oracle, not just plumbing.
    public let timeout: TimeInterval

    /// Size in KB of the RBF image device (`mount -k`). Small values are how the
    /// disk-full scenarios exhaust space deliberately rather than by accident.
    /// Ignored by the RAM-disk and host-directory backends.
    public let deviceKB: Int

    /// Shell commands run AFTER the racers are launched but BEFORE they are
    /// waited for -- the destructive act, fired while the workers still hold the
    /// file open. Empty for an ordinary run. This is how a file is deleted, or a
    /// writer killed, mid-flight, so the disk can then be checked for the damage
    /// that violence might have left behind.
    public let midFlight: [String]

    /// Creates a scenario.
    public init(name: String, backend: Backend, workers: [WorkerSpec],
                tick: TickMode = .enabled, timeout: TimeInterval = 60,
                deviceKB: Int = 500, midFlight: [String] = []) {
        self.name = name
        self.backend = backend
        self.workers = workers
        self.tick = tick
        self.timeout = timeout
        self.deviceKB = deviceKB
        self.midFlight = midFlight
    }

    /// Every distinct file the roster touches.
    public var files: [String] {
        var seen: [String] = []
        for worker in workers where !seen.contains(worker.file) {
            seen.append(worker.file)
        }
        return seen
    }

    /// What each worker claims it wrote, across the whole scenario.
    public var expectations: [WorkerExpectation] {
        workers.map(\.expectation)
    }

    /// What to expect in ONE file specifically.
    ///
    /// Must be per-file, not per-scenario: a roster writing to separate files
    /// would otherwise fault every file for lacking the other workers' records,
    /// and — far worse in the other direction — a roster sharing one file needs
    /// every participant listed or a real foreign record would be excused as a
    /// phantom writer.
    public func expectations(forFile file: String) -> [WorkerExpectation] {
        workers.filter { $0.file == file }.map(\.expectation)
    }
}
