//
//  StructuralOracle.swift
//  RBFHammerCore
//
//  Reads a device's on-disk health from `dcheck` and `free`, the two RBF tools
//  the content verifier cannot replace.
//
//  A torn or lost record is visible in the file's bytes; a cross-linked cluster,
//  a sector allocated to no file, or a free count that never came back after a
//  delete is NOT -- the file can read back perfectly while the filesystem around
//  it is corrupt. The destructive scenarios exist to provoke exactly that, so
//  they are only as good as this oracle. It parses the guest's own report rather
//  than trusting the run to have "looked fine".
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation

/// Reads structural and allocation health from `dcheck`/`free` output.
public enum StructuralOracle {

    /// The phrase `dcheck` prints when the DIRECTORY/FILE tree is walkable.
    ///
    /// Necessary but NOT sufficient for a clean disk -- and this was learned the
    /// hard way. `dcheck` prints "intact" for the file tree even when the
    /// ALLOCATION map is corrupt: a real image with a sector wrongly marked
    /// allocated printed both this line AND "1 cluster not in file structure".
    /// So the clean bill is required, and every allocation-fault phrase below
    /// must ALSO be absent. Verified live against os9exec's `dcheck`.
    static let cleanBillOfHealth = "file structure is intact"

    /// Phrases `dcheck` prints for specific corruption, checked in ADDITION to
    /// the clean bill -- because dcheck prints "intact" alongside some of them.
    /// `not in file structure` covers both the per-sector line ("Sector NNN ...
    /// not in file structure") and the summary ("N cluster not in file
    /// structure"); `not allocated` is the reverse (a sector a file uses that
    /// the bitmap calls free). Both are `Live`.
    static let damageMarkers = [
        "not in file structure",       // allocated, but no file owns it
        "not allocated",               // used by a file, but the bitmap calls it free
        "cross-linked",
        "bad file descriptor",
        "illegal"
    ]

    /// Whether `dcheck` certified the filesystem structure intact.
    ///
    /// - Parameter transcript: Everything `dcheck` printed (the surrounding shell
    ///   noise is harmless -- only the marker lines are consulted).
    public static func isIntact(dcheck transcript: String) -> Bool {
        let lower = transcript.lowercased()
        guard lower.contains(cleanBillOfHealth) else { return false }
        return !damageMarkers.contains { lower.contains($0) }
    }

    /// The device's free-sector count, parsed from `free` output, or nil if the
    /// output does not contain it (which is itself worth failing on -- a `free`
    /// that produced no count means the round-trip cannot be judged).
    ///
    /// Digits may be comma-grouped: NitrOS-9's `free` prints `7,471,391 free
    /// sectors` on a large device (os9exec's does not). Commas are stripped.
    public static func freeSectors(in transcript: String) -> Int? {
        firstInt(in: transcript, matching: #/(?<n>[\d,]+) free sectors/#)
    }

    /// The device's total capacity in sectors, parsed from `free` output.
    public static func capacitySectors(in transcript: String) -> Int? {
        firstInt(in: transcript, matching: #/Capacity:\s*(?<n>[\d,]+) sectors/#)
    }

    /// A structural violation if `dcheck` did not certify the disk.
    ///
    /// - Parameter dcheck: The `dcheck` transcript for the device under test.
    /// - Returns: One `.structuralDamage` violation, or none if intact.
    public static func structuralViolations(dcheck transcript: String) -> [Violation] {
        guard !isIntact(dcheck: transcript) else { return [] }
        return [Violation(kind: .structuralDamage,
                          detail: "dcheck did not report the filesystem intact:\n"
                                + relevantLines(of: transcript))]
    }

    /// An allocation-leak violation if the free count did not return to baseline.
    ///
    /// Used for a create/delete round-trip: the device is measured before the
    /// churn and after everything it created has been deleted. The two counts
    /// must match, or allocation was leaked (fewer free after) or double-freed
    /// (more free after).
    ///
    /// - Parameters:
    ///   - before: `free` output captured before the round-trip.
    ///   - after: `free` output captured after it, with all created files gone.
    /// - Returns: One `.allocationLeak` violation, or none if the counts match.
    public static func allocationViolations(before: String, after: String) -> [Violation] {
        guard let start = freeSectors(in: before) else {
            return [Violation(kind: .allocationLeak,
                              detail: "no free-sector count in the baseline `free` output")]
        }
        guard let end = freeSectors(in: after) else {
            return [Violation(kind: .allocationLeak,
                              detail: "no free-sector count in the post-round-trip `free` output")]
        }
        guard start != end else { return [] }
        let verb = end < start ? "leaked" : "double-freed"
        return [Violation(kind: .allocationLeak,
                          detail: "free sectors \(start) -> \(end): \(start - end) \(verb)")]
    }

    // ── Parsing helpers ─────────────────────────────────────────────────────

    /// First capture of `regex`'s `n` group in `text`, as an Int (commas dropped).
    private static func firstInt(in text: String,
                                 matching regex: some RegexComponent<(Substring, n: Substring)>)
        -> Int? {
        text.firstMatch(of: regex).flatMap { Int($0.output.n.filter { $0 != "," }) }
    }

    /// The dcheck lines worth putting in a failure report -- the clean/damage
    /// markers and anything mentioning a sector or error -- so the report is not
    /// the whole boot banner.
    private static func relevantLines(of transcript: String) -> String {
        let keep = ["sector", "error", "cross", "allocat", "structure", "file descriptor"]
        return transcript
            .split(separator: "\n")
            .filter { line in keep.contains { line.lowercased().contains($0) } }
            .joined(separator: "\n")
    }
}
