//
//  Verifier.swift
//  RBFHammerCore
//
//  The content oracle: decides whether a file several processes hammered
//  concurrently actually holds what those processes wrote.
//
//  This runs on the host, not in the guest, deliberately. Verification logic in
//  BASIC09 would have to be written twice (68k and 6809 dialects diverge) and
//  could not be unit-tested without an emulator. Here it is ordinary Swift with
//  tests that prove it reports every corruption class it claims to catch.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// How many records a worker reported writing, used to detect writes that
/// vanished entirely rather than arriving damaged.
public struct WorkerExpectation: Equatable, Sendable {

    /// The worker's id.
    public let worker: Int

    /// How many records that worker says it wrote.
    public let count: Int

    /// The first sequence number it used.
    ///
    /// Non-zero when several workers share one file and each owns a slot
    /// range, so "missing sequence" means missing from THAT worker's range
    /// rather than from zero.
    public let firstSequence: Int

    /// Creates an expectation for one worker.
    public init(worker: Int, count: Int, firstSequence: Int = 0) {
        self.worker = worker
        self.count = count
        self.firstSequence = firstSequence
    }
}

/// One way a hammered file failed to match what its writers reported.
public struct Violation: Equatable, Sendable {

    /// The classes of damage the verifier distinguishes.
    public enum Kind: String, Equatable, Sendable {

        /// Bytes that are not a whole record -- a write interrupted in flight.
        case tornRecord

        /// A worker's sequence skips a number: that write was lost.
        case sequenceGap

        /// The same worker and sequence appears more than once.
        case duplicate

        /// Framing intact, contents wrong. Neither `dcheck` nor `free` sees this.
        case checksumMismatch

        /// A record from a worker that never ran -- cross-file or cross-path bleed.
        case phantomWriter

        /// Fewer (or more) records than the worker reported writing.
        case countMismatch

        /// `dcheck` did not report the filesystem structure intact: a
        /// cross-linked, unaccounted, or dangling sector -- the on-disk damage a
        /// content check cannot see. This is what the destructive scenarios hunt.
        case structuralDamage

        /// The device's free-sector count did not return to its baseline after a
        /// create/delete round-trip: allocation was leaked or double-freed.
        case allocationLeak
    }

    /// Which class of damage this is.
    public let kind: Kind

    /// Human-readable specifics, for the failure report.
    public let detail: String

    /// Creates a violation.
    public init(kind: Kind, detail: String) {
        self.kind = kind
        self.detail = detail
    }
}

/// Checks a hammered file against what its writers reported doing.
public enum Verifier {

    /// Verifies a file produced by one or more hammer workers.
    ///
    /// - Parameters:
    ///   - data: The file's bytes, exactly as read back from the device.
    ///   - expecting: What each participating worker reported writing.
    /// - Returns: Every violation found. An empty array means the file is
    ///   exactly what the workers say they wrote -- no lost, torn, duplicated,
    ///   corrupted, or foreign records.
    public static func verify(data: Data, expecting: [WorkerExpectation]) -> [Violation] {
        var violations: [Violation] = []
        var sequencesByWorker: [Int: [Int]] = [:]
        let known = Set(expecting.map(\.worker))

        for (index, frame) in Record.frames(in: data).enumerated() {
            let offset = index * Record.width
            guard let record = Record.decode(frame: frame) else {
                violations.append(Violation(
                    kind: .tornRecord,
                    detail: "offset \(offset): \(frame.count) bytes, not a whole record"))
                continue
            }
            if !record.isIntact {
                violations.append(Violation(
                    kind: .checksumMismatch,
                    detail: "offset \(offset): worker \(record.worker) seq \(record.sequence) "
                          + "recorded \(record.recordedChecksum), computed \(record.checksum)"))
            }
            if known.contains(record.worker) {
                sequencesByWorker[record.worker, default: []].append(record.sequence)
            } else {
                violations.append(Violation(
                    kind: .phantomWriter,
                    detail: "offset \(offset): worker \(record.worker) never ran"))
            }
        }

        for expectation in expecting.sorted(by: { $0.worker < $1.worker }) {
            violations += check(expectation, sequencesByWorker[expectation.worker] ?? [])
        }
        return violations
    }

    /// Checks one worker's recovered sequence numbers for gaps, duplicates,
    /// and a total that disagrees with what the worker reported.
    private static func check(_ expectation: WorkerExpectation,
                              _ sequences: [Int]) -> [Violation] {
        var violations: [Violation] = []
        let worker = expectation.worker

        if sequences.count != expectation.count {
            violations.append(Violation(
                kind: .countMismatch,
                detail: "worker \(worker): wrote \(expectation.count), "
                      + "found \(sequences.count)"))
        }

        let seen = Set(sequences)
        if seen.count != sequences.count {
            let occurrences = sequences.reduce(into: [Int: Int]()) { counts, sequence in
                counts[sequence, default: 0] += 1
            }
            let repeated = occurrences.filter { $0.value > 1 }.keys.sorted()
            violations.append(Violation(
                kind: .duplicate,
                detail: "worker \(worker): repeated sequences \(repeated)"))
        }

        let range = expectation.firstSequence..<(expectation.firstSequence + expectation.count)
        let missing = range.filter { !seen.contains($0) }
        if !missing.isEmpty {
            violations.append(Violation(
                kind: .sequenceGap,
                detail: "worker \(worker): missing sequences \(missing)"))
        }
        return violations
    }
}
