//
//  WorkerScript.swift
//  RBFHammerCore
//
//  Turns the hammer template into a BASIC09 command script for one worker.
//
//  Shared by every target adapter. The substitution and the procedure split are
//  identical on 68k and 6809 -- the BASIC09 editor behaves the same on both --
//  so keeping one implementation is what makes "the two targets ran the same
//  program" a fact rather than a hope. A divergence between targets must come
//  from RBF, not from two copies of this drifting apart.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// Builds the BASIC09 command script that runs one worker.
public enum WorkerScript {

    /// Renders one worker's script from the template.
    ///
    /// The result is CR-separated, not LF: BASIC09 fed an LF-terminated script
    /// silently does nothing useful -- a healthy-looking banner and no work
    /// done -- which presents as an empty run rather than as an error.
    ///
    /// - Parameters:
    ///   - worker: The worker to render.
    ///   - template: Contents of `test/rbf-hammer/hammer.bas`.
    ///   - stripComments: Drops comment-only lines before the guest sees them.
    ///     The template is mostly commentary, and BASIC09 re-parses every line
    ///     through its editor at each launch -- a cost paid per worker, on a
    ///     2MHz 6809, on every run. Comments are inert, so removing them cannot
    ///     change behaviour, only how long entry takes. Off by default so the
    ///     68k target keeps compiling the exact text its results were proven
    ///     against.
    /// - Returns: Script text ready to feed to `basic`/`basic09` on stdin.
    public static func render(_ worker: WorkerSpec, from template: String,
                              stripComments: Bool = false) -> String {
        let substituted = template
            .replacingOccurrences(of: "@ID@", with: String(worker.id))
            .replacingOccurrences(of: "@COUNT@", with: String(worker.count))
            .replacingOccurrences(of: "@NAP@", with: String(max(0, worker.nap)))
            .replacingOccurrences(of: "@ROLE@", with: worker.role.rawValue)
            .replacingOccurrences(of: "@NAPMODE@", with: worker.napMode.rawValue)
            .replacingOccurrences(of: "@FILE@", with: worker.file)

        var lines: [String] = []
        for procedure in procedures(in: substituted, stripComments: stripComments) {
            // `e <name>` writes the PROCEDURE header itself, so the body must
            // not repeat it. A leading space is what makes the editor INSERT a
            // line rather than read it as an editor command.
            lines.append("e \(procedure.name)")
            lines += procedure.body.map { " \($0)" }
            lines.append("q")
        }
        lines += ["run hwork", "bye"]
        return lines.joined(separator: "\r") + "\r"
    }

    /// Splits a template into its named procedures.
    ///
    /// The template holds more than one because BASIC09 is a structured
    /// language: shared behaviour belongs in its own procedure called with
    /// `RUN`, not in a `GOSUB` to a numbered line.
    static func procedures(in template: String,
                           stripComments: Bool = false) -> [(name: String, body: [String])] {
        var found: [(name: String, body: [String])] = []
        for line in template.split(separator: "\n", omittingEmptySubsequences: false) {
            if line.hasPrefix("PROCEDURE ") {
                found.append((name: String(line.dropFirst("PROCEDURE ".count))
                                     .trimmingCharacters(in: .whitespaces), body: []))
            } else if stripComments,
                      line.trimmingCharacters(in: .whitespaces).hasPrefix("!") {
                continue
            } else if !found.isEmpty, !(line.isEmpty && found[found.count - 1].body.isEmpty) {
                found[found.count - 1].body.append(String(line))
            }
        }
        // A trailing blank line would be inserted as an empty editor line.
        for index in found.indices {
            while found[index].body.last?.isEmpty == true {
                found[index].body.removeLast()
            }
        }
        return found
    }
}
