//
//  WorkerScript.swift
//  RBFHammerCore
//
//  Turns the hammer template into a BASIC09 command script for one worker.
//
//  Shared by every target adapter. The substitution and the procedure split are
//  identical on 68k and 6809 -- the BASIC09 editor behaves the same on both --
//  so keeping one implementation is what makes "the two targets ran the same
//  program" a fact rather than a hope. A divergence between targets must come
//  from RBF, not from two copies of this drifting apart.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import Foundation

/// Builds the BASIC09 command script that runs one worker.
public enum WorkerScript {

    /// Renders one worker's script from the template.
    ///
    /// The result is CR-separated, not LF: BASIC09 fed an LF-terminated script
    /// silently does nothing useful -- a healthy-looking banner and no work
    /// done -- which presents as an empty run rather than as an error.
    ///
    /// - Parameters:
    ///   - worker: The worker to render.
    ///   - template: Contents of `test/rbf-hammer/hammer.bas`.
    ///   - stripComments: Drops comment-only lines before the guest sees them.
    ///     The template is mostly commentary, and BASIC09 re-parses every line
    ///     through its editor at each launch -- a cost paid per worker, on a
    ///     2MHz 6809, on every run. Comments are inert, so removing them cannot
    ///     change behaviour, only how long entry takes. Off by default so the
    ///     68k target keeps compiling the exact text its results were proven
    ///     against.
    /// - Returns: Script text ready to feed to `basic`/`basic09` on stdin.
    public static func render(_ worker: WorkerSpec, from template: String,
                              stripComments: Bool = false) -> String {
        editorScript(for: procedures(in: substitute(worker, into: template),
                                     stripComments: stripComments),
                     tail: ["run hwork", "bye"])
    }

    /// Renders a worker as a script that BUILDS AND PACKS it into a standalone
    /// module named `hwork<id>`, instead of running it.
    ///
    /// This is what lets the 6809 driver launch racers with `runb hwork<id>`
    /// (instant, no editor) rather than driving the BASIC09 editor from a script
    /// file at every launch. Several editors parsing at once race and hang; a
    /// packed module has no editor phase, so concurrent launches are safe.
    ///
    /// Both procedures are renamed with the worker's id (`hnap<id>` / `hwork<id>`
    /// and the `RUN` between them), so each racer's module shares NO name with
    /// any other -- no resident-module contamination when several run at once.
    /// `PACK hwork<id>,hnap<id>` makes `hwork<id>` the module's entry point.
    public static func renderPack(_ worker: WorkerSpec, from template: String) -> String {
        let suffix = String(worker.id)
        let named = substitute(worker, into: template)
            .replacingOccurrences(of: "hnap", with: "hnap\(suffix)")
            .replacingOccurrences(of: "hwork", with: "hwork\(suffix)")
        return editorScript(for: procedures(in: named, stripComments: true),
                            tail: ["pack hwork\(suffix),hnap\(suffix)", "bye"])
    }

    /// Bakes a worker's values into the template's `@TOKEN@`s.
    static func substitute(_ worker: WorkerSpec, into template: String) -> String {
        template
            .replacingOccurrences(of: "@ID@", with: String(worker.id))
            .replacingOccurrences(of: "@COUNT@", with: String(worker.count))
            .replacingOccurrences(of: "@NAP@", with: String(max(0, worker.nap)))
            .replacingOccurrences(of: "@ROLE@", with: worker.role.rawValue)
            .replacingOccurrences(of: "@NAPMODE@", with: worker.napMode.rawValue)
            .replacingOccurrences(of: "@FILE@", with: worker.file)
    }

    /// Turns a list of procedures into editor commands, then appends `tail`.
    private static func editorScript(for procedures: [(name: String, body: [String])],
                                     tail: [String]) -> String {
        var lines: [String] = []
        for procedure in procedures {
            // `e <name>` writes the PROCEDURE header itself, so the body must
            // not repeat it. A leading space is what makes the editor INSERT a
            // line rather than read it as an editor command.
            lines.append("e \(procedure.name)")
            lines += procedure.body.map { " \($0)" }
            lines.append("q")
        }
        lines += tail
        return lines.joined(separator: "\r") + "\r"
    }

    /// Splits a template into its named procedures.
    ///
    /// The template holds more than one because BASIC09 is a structured
    /// language: shared behaviour belongs in its own procedure called with
    /// `RUN`, not in a `GOSUB` to a numbered line.
    static func procedures(in template: String,
                           stripComments: Bool = false) -> [(name: String, body: [String])] {
        var found: [(name: String, body: [String])] = []
        for line in template.split(separator: "\n", omittingEmptySubsequences: false) {
            if line.hasPrefix("PROCEDURE ") {
                found.append((name: String(line.dropFirst("PROCEDURE ".count))
                                     .trimmingCharacters(in: .whitespaces), body: []))
            } else if stripComments,
                      line.trimmingCharacters(in: .whitespaces).hasPrefix("!") {
                continue
            } else if !found.isEmpty, !(line.isEmpty && found[found.count - 1].body.isEmpty) {
                found[found.count - 1].body.append(String(line))
            }
        }
        // A trailing blank line would be inserted as an empty editor line.
        for index in found.indices {
            while found[index].body.last?.isEmpty == true {
                found[index].body.removeLast()
            }
        }
        return found
    }
}
