//
//  main.swift
//  LiveVerify
//
//  Entry point for the 68k live-verification suite.
//  Run: swift run --package-path test LiveVerify
//       make live-verify
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation
import LiveVerifyCore

print("=== LiveVerify (68k) ===")
print("(no manifest entries yet)")
