//
//  ChoreographyExecutor.swift
//  LiveVerifyCore
//
//  Runs a `category: .choreography` entry: every source is a BASIC09
//  procedure, PACKed to a standalone module (not run via the raw-source
//  editor-run recipe SoloExecutor uses for solo .bas), then driven by
//  `roles` -- some backgrounded, some blocking, each after a real delay --
//  against one shared transcript.
//
//  Two PACK-specific gotchas this recipe routes around (both already
//  documented in basic09/pack-and-runb.md, confirmed live during this
//  suite's design):
//    1. `PACK name >target` prints a spurious Error #000:043/#051 even
//       when the output file is complete and correct -- never treated as
//       a build failure here.
//    2. A packed module can ONLY be invoked by bare name after `load`ing
//       it resident -- invoking it by explicit path (`/h5/lostinit`)
//       fails with the same #000:043, and a bare `lostinit` (without
//       `runb`) fails E$MNF. The working shape is `load <path>` once,
//       then `runb <moduleName>` (never a path) for every role launch.
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation

public struct ChoreographyExecutor {
    private let runner: OS9Runner
    private let corpusDir: URL

    public init(runner: OS9Runner, corpusDir: URL) {
        self.runner = runner
        self.corpusDir = corpusDir
    }

    public func run(_ entry: ManifestEntry, scratchDir: URL, timeout: TimeInterval) -> ExecutionResult {
        do {
            guard let roles = entry.roles, !roles.isEmpty else {
                return .fail("no roles (should have been caught by validate())")
            }
            // Within os9exec, the scratch directory is mounted at /h5
            let scratch = "/h5"

            // Unlike SoloExecutor, no separate on-disk staging step is needed:
            // `editorPackScriptBody` reads each source's content directly and
            // builds a CR-joined editor script from it, so there is no
            // intermediate CR-converted file any command below needs to read.
            //
            // Every source's pack script is one continuous BASIC09 editor
            // session (matches how the original dogfood pass packed all three
            // lostupdate procedures together): concatenate their CR-joined
            // texts, `bye` once at the very end.
            let editorSession = try entry.sources
                .map { try editorPackScriptBody($0, scratch: scratch) }
                .joined() + "bye\r"

            // Stage 1: mount + pack everything (immediate).
            let firstStageText = try writePackScriptAndBuildFirstStage(editorSession: editorSession,
                                                                       scratch: scratch,
                                                                       scratchDir: scratchDir,
                                                                       entry: entry)
            var staged: [StagedInput] = [
                StagedInput(text: firstStageText, delay: 0),
            ]

            // Stage 2+: one StagedInput per role, in the order given, honoring
            // each role's own delay and background flag.
            for role in roles {
                let command = role.background ? "runb \(role.moduleName) &\n" : "runb \(role.moduleName)\n"
                staged.append(StagedInput(text: command, delay: role.delayBeforeStart))
            }

            let outcome = runner.run(staged: staged, scratchDir: scratchDir, timeout: timeout)
            if outcome.timedOut { return .timedOut }
            let transcript = normalizeTranscript(outcome.transcript)
            if transcript.contains("error -") {
                return .buildFailed(preview(transcript))
            }
            if evaluate(entry.expect, against: transcript) {
                return .pass
            }
            return .fail(preview(transcript))
        } catch {
            return .buildFailed(error.localizedDescription)
        }
    }

    /// The corpus's choreography sources hardcode a real path under the
    /// shared, project-forbidden `/h1` image (`/h1/CLAUDETEST/...`, from
    /// the original dogfood pass). This suite must never touch that image
    /// -- every such path is redirected to this executor's own per-run RAM
    /// disk instead. Verified live against the lostupdate trio with this
    /// exact substitution (`/liveverify9` in place of `/h1/CLAUDETEST`).
    private static let sharedDiskPrefix = "/h1/CLAUDETEST"
    private static let scratchDiskDevice = "/liveverify9"

    /// `e <name>` / body (space-prefixed) / `q` / `pack <name> >path` for
    /// one source -- everything except the session-final `bye`, which is
    /// appended once after every source (see `run(_:scratchDir:timeout:)`).
    /// Throws if the fixture file cannot be read.
    private func editorPackScriptBody(_ source: SourceFile, scratch: String) throws -> String {
        let hostPath = corpusDir.appendingPathComponent(source.file)
        let text: String
        do {
            text = try String(contentsOf: hostPath, encoding: .utf8)
        } catch {
            throw NSError(domain: "ChoreographyExecutor", code: -1, userInfo: [
                NSLocalizedDescriptionKey: "failed to read fixture \(source.file): \(error.localizedDescription)"
            ])
        }
        var body = text.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        if body.first?.hasPrefix("PROCEDURE ") == true { body.removeFirst() }
        while body.last == "" { body.removeLast() }
        body = body.map { $0.replacingOccurrences(of: Self.sharedDiskPrefix, with: Self.scratchDiskDevice) }
        var lines = ["e \(source.moduleName)"]
        lines += body.map { " \($0)" }
        lines.append("q")
        lines.append("pack \(source.moduleName) >\(scratch)/\(source.moduleName)")
        return lines.joined(separator: "\r") + "\r"
    }

    /// Writes the combined pack session to `<scratch>/packscript`, then
    /// returns the first-stage command text: feed that script to `basic`,
    /// `load` every produced module resident (required -- see the type doc
    /// comment on the invoke-by-bare-name-only gotcha; verified live that
    /// omitting this step, relying on PACK's own registration alone,
    /// produces wrong results), and `chd` to the scratch RAM disk so any
    /// role that opens a file by bare relative name resolves there.
    /// Throws if the pack script cannot be written.
    private func writePackScriptAndBuildFirstStage(editorSession: String, scratch: String,
                                                   scratchDir: URL, entry: ManifestEntry) throws -> String {
        let scriptPath = scratchDir.appendingPathComponent("packscript")
        do {
            try Data(editorSession.utf8).write(to: scriptPath)
        } catch {
            throw NSError(domain: "ChoreographyExecutor", code: -1, userInfo: [
                NSLocalizedDescriptionKey: "failed to write pack script to \(scriptPath.path): \(error.localizedDescription)"
            ])
        }
        var lines = ["mount -r=200 \(Self.scratchDiskDevice)", "load math", "basic <\(scratch)/packscript"]
        for source in entry.sources {
            lines.append("load \(scratch)/\(source.moduleName)")
        }
        lines.append("chd \(Self.scratchDiskDevice)")
        return lines.joined(separator: "\n") + "\n"
    }

    private func preview(_ transcript: String) -> String {
        transcript.split(separator: "\n")
            .filter { !$0.hasPrefix("#") && $0 != "$" && !$0.isEmpty }
            .prefix(6).joined(separator: " | ")
    }
}
