//
//  Expectation+Matching.swift
//  LiveVerifyCore
//
//  Pattern matching against a run's transcript, and manifest self-checks
//  that need no emulator at all -- a typo'd oracle must fail loudly at
//  review time, not silently pass because it matches everything.
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation

/// Collapses OS-9's CR+LF line endings to a single `\n`, pair-first so a
/// real `\r\n` doesn't become a blank line (naive `tr '\r' '\n'`-style
/// single-character replacement does exactly that). A lone `\r` with no
/// paired `\n` still normalizes, so it never survives into a pattern match
/// as a literal carriage return.
public func normalizeTranscript(_ raw: String) -> String {
    raw.replacingOccurrences(of: "\r\n", with: "\n")
       .replacingOccurrences(of: "\r", with: "\n")
}

/// Whether `expectation` holds against an already-`normalizeTranscript`'d
/// transcript.
public func matches(_ expectation: Expectation, in transcript: String) -> Bool {
    if let literal = expectation.contains {
        return transcript.contains(literal)
    }
    if let pattern = expectation.matches, let regex = try? Regex(pattern) {
        return transcript.contains(regex)
    }
    return false
}

/// True only if every expectation matches (AND, not OR) — a test with two
/// assertions must fail if either one doesn't hold.
public func evaluate(_ expectations: [Expectation], against transcript: String) -> Bool {
    expectations.allSatisfy { matches($0, in: transcript) }
}

/// A manifest defect caught before any emulator run.
public enum ManifestValidationError: Error, CustomStringConvertible {
    case emptyContainsPattern(entryID: String)
    case invalidRegex(entryID: String, pattern: String)
    case expectationWithNeitherField(entryID: String)
    case soloEntryWithNoPrimarySource(entryID: String)
    case choreographyEntryWithNoRoles(entryID: String)
    case roleWithNoMatchingSource(entryID: String, moduleName: String)

    public var description: String {
        switch self {
        case .emptyContainsPattern(let id):
            return "\(id): an `expect` entry has an empty `contains` pattern"
        case .invalidRegex(let id, let pattern):
            return "\(id): `matches` pattern is not valid regex: \(pattern)"
        case .expectationWithNeitherField(let id):
            return "\(id): an `expect` entry has neither `contains` nor `matches`"
        case .soloEntryWithNoPrimarySource(let id):
            return "\(id): solo entry has no source marked `primary: true`"
        case .choreographyEntryWithNoRoles(let id):
            return "\(id): choreography entry has no `roles`"
        case .roleWithNoMatchingSource(let id, let name):
            return "\(id): role names moduleName \"\(name)\" with no matching source"
        }
    }
}

/// Validates one manifest entry's internal consistency. No emulator
/// involved -- this is a fast pass over the manifest's own data.
public func validate(_ entry: ManifestEntry) throws {
    for expectation in entry.expect {
        if let literal = expectation.contains {
            if literal.isEmpty {
                throw ManifestValidationError.emptyContainsPattern(entryID: entry.id)
            }
        } else if let pattern = expectation.matches {
            guard (try? Regex(pattern)) != nil else {
                throw ManifestValidationError.invalidRegex(entryID: entry.id, pattern: pattern)
            }
        } else {
            throw ManifestValidationError.expectationWithNeitherField(entryID: entry.id)
        }
    }

    switch entry.category {
    case .solo:
        guard entry.sources.contains(where: { $0.primary }) else {
            throw ManifestValidationError.soloEntryWithNoPrimarySource(entryID: entry.id)
        }
    case .choreography:
        guard let roles = entry.roles, !roles.isEmpty else {
            throw ManifestValidationError.choreographyEntryWithNoRoles(entryID: entry.id)
        }
        let knownModules = Set(entry.sources.map(\.moduleName))
        for role in roles where !knownModules.contains(role.moduleName) {
            throw ManifestValidationError.roleWithNoMatchingSource(entryID: entry.id, moduleName: role.moduleName)
        }
    }
}
