//
//  LiveVerifyCore.swift
//  LiveVerifyCore
//
//  Manifest-driven PASS/FAIL runner for the 68k live-verification corpus
//  (test/68k-live-verification/).
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//
