//
//  LiveVerifyCore.swift
//  LiveVerifyCore
//
//  Manifest-driven PASS/FAIL runner for the 68k live-verification corpus
//  (test/68k-live-verification/). See docs/superpowers/specs/
//  2026-07-21-live-verification-suite-design.md.
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//
