//
//  Manifest.swift
//  LiveVerifyCore
//
//  The manifest schema: one JSON file (test/live-verification-manifest.json)
//  is the single source of truth for every wrapped test, so the ~86-file
//  corpus is data, not ~86 duplicated shell scripts.
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation

/// The top-level manifest file.
public struct Manifest: Codable {
    public let entries: [ManifestEntry]
}

/// Whether an entry runs one program alone, or choreographs several
/// (backgrounded, timed) processes against a shared file.
public enum Category: String, Codable {
    case solo
    case choreography
}

/// One file to build. `moduleName` is explicit (not derived from `file`)
/// because this corpus's psect/module names don't always match their
/// filename mechanically (`batch1-01.a`'s psect is `batch101`, dash
/// stripped) — deriving it would be a fragile guess where an explicit
/// field is exact.
public struct SourceFile: Codable {
    public let file: String
    public let moduleName: String
    /// Solo category only: the one source whose output actually gets run
    /// and checked against `expect`. Every other source in the same entry
    /// is a dependency built (and, for `.a`, `load`ed resident) but never
    /// itself the thing under test.
    public let primary: Bool
}

/// Choreography category only: one process launch in the scenario.
public struct Role: Codable {
    /// Must match a `SourceFile.moduleName` in the same entry.
    public let moduleName: String
    /// Real seconds to wait (via the host, not OS-9) before launching this
    /// role, relative to the previous role's launch (or to the choreography start for the first role).
    public let delayBeforeStart: Double
    /// True to background this role in the OS-9 shell (`&`); a `false`
    /// role blocks until it exits before the next command is sent.
    public let background: Bool
}

/// A literal substring (`contains`) or a regular expression (`matches`)
/// checked against the run's normalized transcript. Exactly one of the two
/// must be set — `ManifestValidation` (Task 3) enforces this.
public struct Expectation: Codable {
    public let contains: String?
    public let matches: String?
}

/// One wrapped test.
public struct ManifestEntry: Codable {
    public let id: String
    public let category: Category
    public let sources: [SourceFile]
    /// Choreography category only.
    public let roles: [Role]?
    /// All entries must match (AND, not OR) for the entry to PASS.
    public let expect: [Expectation]
    /// Provenance: which doc row / dogfood report this test guards. Not
    /// used by any check — for a future reader tracing a failure back to
    /// the original finding.
    public let notes: String
}
