//
//  OS9Runner.swift
//  LiveVerifyCore
//
//  Launches the locally-built os9exec, feeding it staged (optionally timed)
//  shell input and capturing the transcript. The timed-staging variant is
//  what test/68k-live-verification/pipe-abort-repro.sh already does via
//  host shell `sleep` between piped writes, translated to real Swift
//  delays between stdin-pipe writes -- needed for choreography category's
//  real backgrounding (Task 6), where OS9Tests' existing os9() helper
//  (which writes all input at once) can't time anything.
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation

#if canImport(Darwin)
import Darwin
#else
import Glibc
#endif

/// One chunk of shell input, sent after waiting `delay` real seconds from
/// the previous chunk (or from run start, for the first chunk).
public struct StagedInput {
    public let text: String
    public let delay: TimeInterval

    public init(text: String, delay: TimeInterval) {
        self.text = text
        self.delay = delay
    }
}

/// What one run produced.
public struct RunOutcome {
    public let transcript: String
    public let timedOut: Bool
}

/// Runs staged shell input against the locally built `os9exec`.
public struct OS9Runner {
    private let execURL: URL
    private let diskPath: String

    /// - Parameter repoRoot: directory containing `os9exec` and `h0`.
    public init(repoRoot: URL) throws {
        execURL = repoRoot.appendingPathComponent("os9exec")
        diskPath = repoRoot.appendingPathComponent("h0").path
        guard FileManager.default.isExecutableFile(atPath: execURL.path) else {
            throw CocoaError(.fileNoSuchFile)
        }
    }

    /// Runs `staged` against a fresh `os9exec -r shell`, using
    /// `scratchDir` (a directory the caller creates and owns) as the `/h5`
    /// device. Every staged chunk after the last real one is followed by
    /// ESC (`\u{1B}`), matching `OS9Tests`' own end-of-input convention, so
    /// callers don't need to append it themselves.
    public func run(staged: [StagedInput], scratchDir: URL, timeout: TimeInterval) -> RunOutcome {
        let process = Process()
        process.executableURL = execURL
        process.arguments = ["-r", "shell"]
        process.environment = ["OS9DISK": diskPath, "OS9H5": scratchDir.path]
        process.currentDirectoryURL = scratchDir

        let stdinPipe = Pipe()
        let stdoutPipe = Pipe()
        let stderrPipe = Pipe()
        process.standardInput = stdinPipe
        process.standardOutput = stdoutPipe
        process.standardError = stderrPipe

        guard (try? process.run()) != nil else {
            return RunOutcome(transcript: "OS9Runner: failed to launch process at \(execURL.path)", timedOut: false)
        }

        var collected = Data()
        let collectQueue = DispatchQueue(label: "liveverify.os9runner.collect")
        let readGroup = DispatchGroup()
        readGroup.enter()
        DispatchQueue.global().async {
            let handle = stdoutPipe.fileHandleForReading
            while true {
                let chunk = handle.availableData
                if chunk.isEmpty { break }
                collectQueue.sync { collected.append(chunk) }
            }
            readGroup.leave()
        }
        DispatchQueue.global().async {
            _ = stderrPipe.fileHandleForReading.readDataToEndOfFile()
        }

        for chunk in staged {
            if chunk.delay > 0 { Thread.sleep(forTimeInterval: chunk.delay) }
            stdinPipe.fileHandleForWriting.write(Data(chunk.text.utf8))
        }
        stdinPipe.fileHandleForWriting.write(Data("\u{1B}\n".utf8))
        stdinPipe.fileHandleForWriting.closeFile()

        let timedOut = readGroup.wait(timeout: .now() + timeout) == .timedOut
        if timedOut {
            process.terminate()
            // Give the process a grace period to exit after SIGTERM
            let graceEnd = Date().addingTimeInterval(2.0)
            while process.isRunning && Date() < graceEnd {
                Thread.sleep(forTimeInterval: 0.01)
            }
            // If still running after grace period, escalate to SIGKILL
            if process.isRunning {
                _ = kill(process.processIdentifier, SIGKILL)
            }
        }
        process.waitUntilExit()
        while process.isRunning { Thread.sleep(forTimeInterval: 0.01) }

        let transcript = collectQueue.sync {
            String(decoding: collected, as: UTF8.self)
        }
        return RunOutcome(transcript: transcript, timedOut: timedOut)
    }
}
