//
//  SoloExecutor.swift
//  LiveVerifyCore
//
//  Builds and runs one `category: .solo` manifest entry. Each SourceFile's
//  extension picks the recipe: .a assembles+links via r68/l68, .c compiles
//  via cc (with any .a dependency built and F$Load-resident first so a
//  bare-name os9fork()/F$Fork from the C program can find it), .bas is fed
//  to an interactive `basic` session as an editor script (raw piped source
//  text does NOT work -- see the design doc and dogfood-report-eoflock-
//  2026-07-18.md's own note that these were "PACKed and run standalone"),
//  and .sh executes the file directly, host-side, using its own exit code.
//
//  Toolchain paths, chx, and CR line endings all follow gotchas documented
//  in 68k/os9-68k-assembly.md and basic09/pack-and-runb.md -- see inline
//  comments at each divergence from the "obvious" invocation.
//
//  Generated by Claude Sonnet 5 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation

/// What running one entry produced.
public enum ExecutionResult {
    case pass
    case fail(String)        // preview of the transcript
    case buildFailed(String) // r68/l68/cc/basic reported a toolchain error
    case timedOut
}

public struct SoloExecutor {
    private let runner: OS9Runner
    private let corpusDir: URL
    private let repoRoot: URL

    /// - Parameters:
    ///   - runner: drives `os9exec`.
    ///   - corpusDir: directory holding the `.a`/`.c`/`.bas`/`.sh` source
    ///     files named in manifest entries (in production,
    ///     `test/68k-live-verification/`; in tests, the `Fixtures` bundle
    ///     resource).
    ///   - repoRoot: the repository root containing `os9exec` and `h0` (used
    ///     when running shell scripts that need access to the emulator).
    public init(runner: OS9Runner, corpusDir: URL, repoRoot: URL? = nil) {
        self.runner = runner
        self.corpusDir = corpusDir
        // If not provided, derive repoRoot from corpusDir (go up until we find os9exec)
        if let repoRoot = repoRoot {
            self.repoRoot = repoRoot
        } else {
            var current = corpusDir
            while !FileManager.default.fileExists(atPath: current.appendingPathComponent("os9exec").path) {
                let parent = current.deletingLastPathComponent()
                if parent == current { break }
                current = parent
            }
            self.repoRoot = current
        }
    }

    public func run(_ entry: ManifestEntry, scratchDir: URL, timeout: TimeInterval) -> ExecutionResult {
        guard let primary = entry.sources.first(where: { $0.primary }) else {
            return .fail("no primary source (should have been caught by validate())")
        }

        // `.sh` short-circuits entirely: it's already a complete, runnable
        // repro script with its own exit-code contract (0 = pass).
        if primary.file.hasSuffix(".sh") {
            return runShellScript(primary)
        }

        do {
            for source in entry.sources {
                try stage(source, into: scratchDir)
            }
        } catch {
            return .buildFailed("failed to stage fixtures into scratch: \(error)")
        }

        let staged = buildCommands(entry: entry, primary: primary, scratchDir: scratchDir)
        let outcome = runner.run(staged: staged, scratchDir: scratchDir, timeout: timeout)
        if outcome.timedOut { return .timedOut }

        let transcript = normalizeTranscript(outcome.transcript)
        if transcript.contains("error -") {
            return .buildFailed(preview(transcript))
        }
        if evaluate(entry.expect, against: transcript) {
            return .pass
        }
        return .fail(preview(transcript))
    }

    // MARK: - Staging

    /// Copies a source file into the scratch device, converting LF to CR
    /// -- OS-9 text tools silently misbehave on LF-terminated input.
    private func stage(_ source: SourceFile, into scratchDir: URL) throws {
        let hostPath = corpusDir.appendingPathComponent(source.file)
        let text = try String(contentsOf: hostPath, encoding: .utf8)
        let converted = text.replacingOccurrences(of: "\n", with: "\r")
        try Data(converted.utf8).write(to: scratchDir.appendingPathComponent(source.file))
    }

    private func runShellScript(_ source: SourceFile) -> ExecutionResult {
        let scriptAbsPath = corpusDir.appendingPathComponent(source.file)

        // Try to find the script in the canonical test/68k-live-verification location first
        // (for production use); fall back to corpusDir (for test fixtures).
        let canonicalPath = repoRoot.appendingPathComponent("test/68k-live-verification/\(source.file)").path
        let scriptPath = FileManager.default.fileExists(atPath: canonicalPath) ? canonicalPath : scriptAbsPath.path

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/sh")
        process.arguments = [scriptPath]
        process.currentDirectoryURL = repoRoot
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        guard (try? process.run()) != nil else {
            return .buildFailed("could not launch \(source.file)")
        }
        let output = String(decoding: pipe.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self)
        process.waitUntilExit()
        return process.terminationStatus == 0 ? .pass : .fail(preview(output))
    }

    // MARK: - Command building

    /// Builds the full staged command list for a non-`.sh` entry: every
    /// dependency source first (assembled/linked/`load`ed, never run
    /// directly), then the primary source's own build-and-run recipe.
    private func buildCommands(entry: ManifestEntry, primary: SourceFile,
                               scratchDir: URL) -> [StagedInput] {
        var lines: [String] = []
        // Within os9exec, the scratch directory is mounted at /h5
        let scratch = "/h5"

        for source in entry.sources where !source.primary {
            lines += buildOnlyCommands(source, scratch: scratch)
        }

        switch fileKind(of: primary.file) {
        case .asm:
            lines += [
                "load /dd/CMDS/r68 /dd/CMDS/l68",
                "r68 -O=\(scratch)/\(primary.moduleName).r \(scratch)/\(primary.file)",
                "l68 -o=\(scratch)/\(primary.moduleName) \(scratch)/\(primary.moduleName).r",
                "\(scratch)/\(primary.moduleName)",
            ]
        case .c:
            lines += [
                "load /dd/CMDS/cpp /dd/CMDS/c68 /dd/CMDS/o68 /dd/CMDS/r68 /dd/CMDS/l68",
                "setenv CLIB /dd/LIB",
                "setenv CDEF /dd/DEFS",
                "cc \(scratch)/\(primary.file) -F=\(scratch)/\(primary.moduleName)",
                // Verified live: a bare-name os9fork()/F$Fork from this
                // program resolves via CHX, the same convention Shell
                // itself uses -- NOT via prior F$Load residency. CHX must
                // point at the scratch dir only for THIS final run step;
                // `cc`'s own bare-name tool resolution above already
                // happened against the default CHX (/dd/CMDS), so
                // switching now doesn't disturb it.
                "chx \(scratch)",
                "\(scratch)/\(primary.moduleName)",
            ]
        case .bas:
            // No current manifest entry combines a .bas primary with a
            // dependency, but `lines` (any dependency-build commands
            // accumulated above) must still be included, not discarded.
            // `chd` matters here: the corpus's .bas files open their data
            // files by bare relative name (e.g. "dlk.dat"), which resolves
            // against the DATA directory, not CHX.
            lines += ["mount -r=200 /liveverify9", "chd /liveverify9", "load math"]
            // `e <name>` etc. are BASIC09 editor commands, not shell
            // commands -- they only mean anything once `basic` is already
            // running and reading them as its own input. Verified live:
            // writing the script to a file and redirecting it as `basic`'s
            // stdin (`basic <path`) is what actually runs it; piping the
            // same text as top-level shell commands does nothing useful.
            let editorText = editorRunScript(primary, scratch: scratch)
            try? Data(editorText.utf8).write(to: scratchDir.appendingPathComponent("runscript"))
            lines.append("basic <\(scratch)/runscript")
            return [StagedInput(text: lines.joined(separator: "\n") + "\n", delay: 0)]
        }

        return [StagedInput(text: lines.joined(separator: "\n") + "\n", delay: 0)]
    }

    /// Dependency (`primary: false`) sources are built but never run
    /// directly: only `.a` dependencies are supported (the corpus has no
    /// `.c`/`.bas` dependency case). Assembled and linked to a file in the
    /// scratch dir named `moduleName`; that alone is enough for the
    /// primary's bare-name fork to find it once CHX points there (see the
    /// `.c` case above) -- no separate `load` step is needed or was tested.
    private func buildOnlyCommands(_ source: SourceFile, scratch: String) -> [String] {
        [
            "load /dd/CMDS/r68 /dd/CMDS/l68",
            "r68 -O=\(scratch)/\(source.moduleName).r \(scratch)/\(source.file)",
            "l68 -o=\(scratch)/\(source.moduleName) \(scratch)/\(source.moduleName).r",
        ]
    }

    /// A `.bas` solo entry is NOT run by piping its raw source text to
    /// `basic` -- that types e.g. `PROCEDURE eofdlk` at the interactive
    /// `Ready` prompt, which enters line-numbered edit mode rather than
    /// running anything, and the session spins forever once stdin runs dry
    /// (the same EOF-spin class of bug documented for BASIC09's debugger).
    /// The working shape, confirmed live: `e <name>`, each body line
    /// prefixed with a space (a bare command with no leading space is read
    /// as an editor command, not inserted text), `q` to leave edit mode,
    /// `run <name>`, `bye`.
    private func editorRunScript(_ source: SourceFile, scratch: String) -> String {
        var lines = ["e \(source.moduleName)"]
        // The body is staged into the scratch dir as source.file, but for
        // the editor we need its BASIC09 text with the `PROCEDURE <name>`
        // header stripped (`e <name>` synthesizes that header itself).
        let hostPath = corpusDir.appendingPathComponent(source.file)
        let text = (try? String(contentsOf: hostPath, encoding: .utf8)) ?? ""
        var body = text.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        if body.first?.hasPrefix("PROCEDURE ") == true { body.removeFirst() }
        while body.last == "" { body.removeLast() }
        lines += body.map { " \($0)" }
        lines.append("q")
        lines.append("run \(source.moduleName)")
        lines.append("bye")
        return lines.joined(separator: "\r") + "\r"
    }

    private enum FileKind { case asm, c, bas }

    private func fileKind(of filename: String) -> FileKind {
        if filename.hasSuffix(".a") { return .asm }
        if filename.hasSuffix(".c") { return .c }
        return .bas
    }

    private func preview(_ transcript: String) -> String {
        transcript.split(separator: "\n")
            .filter { !$0.hasPrefix("#") && $0 != "$" && !$0.isEmpty }
            .prefix(6).joined(separator: " | ")
    }
}
