//
//  GuestFormatTests.swift
//  RBFHammerCoreTests
//
//  Proves the BASIC09 worker and the Swift verifier agree on the byte format.
//
//  The fixture is not synthetic. It is a real file produced by running
//  `test/rbf-hammer/hammer.bas` in the `append` role under os9exec, copied
//  byte for byte out of the guest. Everything the harness concludes rests on
//  the two sides agreeing about these bytes, and the two sides are written in
//  different languages by different means -- so the agreement is asserted
//  here rather than assumed.
//
//  Regenerating: run the worker with @ID@=3, @COUNT@=5, @NAP@=1,
//  @ROLE@=append, and copy the produced file over the fixture.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import XCTest
@testable import RBFHammerCore

final class GuestFormatTests: XCTestCase {

    /// Bytes a real guest run produced, read from the test bundle.
    private func guestFixture() throws -> Data {
        let url = try XCTUnwrap(Bundle.module.url(
            forResource: "Fixtures/guest-append-worker3-5records",
            withExtension: "dat"))
        return try Data(contentsOf: url)
    }

    /// The guest writes exactly the fixed stride the host expects.
    ///
    /// A mismatch here means every offset the verifier computes is wrong, and
    /// torn-record detection becomes meaningless.
    func testGuestRecordsAreTheExpectedFixedWidth() throws {
        let data = try guestFixture()
        XCTAssertEqual(data.count, 5 * Record.width)
    }

    /// A clean guest run verifies clean. This is the end-to-end agreement
    /// check: guest-authored bytes, host-authored oracle, no violations.
    func testGuestProducedFileVerifiesClean() throws {
        let violations = Verifier.verify(data: try guestFixture(),
                                         expecting: [WorkerExpectation(worker: 3, count: 5)])
        XCTAssertEqual(violations, [], "guest output rejected by the host verifier")
    }

    /// The checksums the guest computed match the ones the host computes.
    ///
    /// The two implementations are independent: BASIC09 sums bytes in a loop
    /// with 16-bit signed arithmetic, Swift reduces over UTF-8. This is where
    /// they are actually compared.
    func testGuestChecksumsMatchHostChecksums() throws {
        let data = try guestFixture()
        let records = Record.frames(in: data).compactMap(Record.decode(frame:))
        XCTAssertEqual(records.count, 5)
        for record in records {
            XCTAssertTrue(record.isIntact,
                          "worker \(record.worker) seq \(record.sequence): guest said "
                        + "\(record.recordedChecksum), host computes \(record.checksum)")
        }
    }

    /// The guest's payloads carry the identifying information the oracle needs
    /// -- worker id and sequence -- rather than padding that happens to parse.
    func testGuestPayloadsIdentifyWorkerAndSequence() throws {
        let data = try guestFixture()
        let first = try XCTUnwrap(Record.decode(
            String(bytes: data.prefix(Record.width), encoding: .ascii) ?? ""))
        XCTAssertEqual(first.worker, 3)
        XCTAssertEqual(first.sequence, 0)
        XCTAssertEqual(first.payload, "w3-r0")
    }
}
