//
//  StructuralOracleTests.swift
//  RBFHammerCoreTests
//
//  The structural/allocation oracle, checked against real os9exec `dcheck` and
//  `free` output and against damaged output it MUST reject.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import XCTest
@testable import RBFHammerCore

final class StructuralOracleTests: XCTestCase {

    /// Real `dcheck /h9` output on a freshly `mount -k`ed image holding one file.
    /// Captured before `mount -k` learned to name a volume after its device, so a
    /// fresh image now says 'h9' here. Kept verbatim: the oracle keys on the
    /// "file structure is intact" line, and doctoring a capture to match today's
    /// output would make it something other than a capture.
    private static let cleanDcheck = """
        Sector $000001 is start of bitmap
        Sector $000002 is start of root dir
        Building allocation map...
        Checking allocation map...

        'Ram Disk (Caution: Volatile)' file structure is intact
        1 directory, 1 file
        1536 of 516096 bytes (0.00 of 0.49 meg) used on media
        """

    /// Real `free /h9` output on the same fresh 500K image.
    private static let cleanFree = """
        Capacity: 2016 sectors (256-byte sectors, 1-sector clusters)
        2012 free sectors, largest block 2012 sectors
        515072 of 516096 bytes (503.00 of 504.00 Kb) free on media (99%)
        """

    // ── dcheck: the clean bill of health ──────────────────────────────────────

    func testIntactDcheckIsAccepted() {
        XCTAssertTrue(StructuralOracle.isIntact(dcheck: Self.cleanDcheck))
        XCTAssertEqual(StructuralOracle.structuralViolations(dcheck: Self.cleanDcheck), [])
    }

    /// The failability proof: dcheck that withholds its clean bill -- what it does
    /// the moment it finds a fault -- must be reported as damage.
    func testDcheckWithoutTheCleanBillIsDamage() {
        let damaged = """
            Sector $000001 is start of bitmap
            Building allocation map...
            Checking allocation map...
            Sector $000123 is allocated but not in the file structure
            """
        XCTAssertFalse(StructuralOracle.isIntact(dcheck: damaged))
        let violations = StructuralOracle.structuralViolations(dcheck: damaged)
        XCTAssertEqual(violations.map(\.kind), [.structuralDamage])
    }

    /// The real one, and the reason this oracle exists: `dcheck` on an image
    /// whose bitmap marks an unused sector allocated prints its "file structure
    /// is intact" line AND the fault. A naive "require intact" check passes this
    /// corrupt disk; the allocation-fault markers are what catch it. Captured
    /// live by flipping a bitmap bit host-side and re-running `dcheck`.
    func testAllocationFaultAlongsideAnIntactLineIsDamage() {
        let realDamage = """
            Sector $000001 is start of bitmap
            Sector $000002 is start of root dir
            Building allocation map...
            .
            Sector 000063 (byte=000c bit=3) not in file structure.

            'Ram Disk (Caution: Volatile)' file structure is intact
            1 cluster not in file structure
            1 directory, 1 file
            1536 of 516096 bytes (0.00 of 0.49 meg) used on media
            """
        XCTAssertTrue(realDamage.contains(StructuralOracle.cleanBillOfHealth),
                      "precondition: dcheck really does print the intact line here")
        XCTAssertFalse(StructuralOracle.isIntact(dcheck: realDamage))
        XCTAssertEqual(StructuralOracle.structuralViolations(dcheck: realDamage).map(\.kind),
                       [.structuralDamage])
    }

    // ── free: parsing the counts ──────────────────────────────────────────────

    func testFreeSectorsAndCapacityAreParsed() {
        XCTAssertEqual(StructuralOracle.freeSectors(in: Self.cleanFree), 2012)
        XCTAssertEqual(StructuralOracle.capacitySectors(in: Self.cleanFree), 2016)
    }

    func testFreeSectorsIsNilWhenTheCountIsAbsent() {
        XCTAssertNil(StructuralOracle.freeSectors(in: "no counts here"))
    }

    // ── allocation round-trip ─────────────────────────────────────────────────

    func testEqualFreeCountsAreNoLeak() {
        XCTAssertEqual(StructuralOracle.allocationViolations(before: Self.cleanFree,
                                                             after: Self.cleanFree), [])
    }

    /// The failability proof for allocation: fewer free sectors after the
    /// round-trip than before means clusters were leaked, and must be reported.
    func testFewerFreeSectorsAfterIsALeak() {
        let after = Self.cleanFree.replacingOccurrences(of: "2012 free", with: "2000 free")
        let violations = StructuralOracle.allocationViolations(before: Self.cleanFree, after: after)
        XCTAssertEqual(violations.map(\.kind), [.allocationLeak])
        XCTAssertTrue(violations[0].detail.contains("12 leaked"), violations[0].detail)
    }

    /// More free after than before is also wrong: a double-free.
    func testMoreFreeSectorsAfterIsADoubleFree() {
        let after = Self.cleanFree.replacingOccurrences(of: "2012 free", with: "2020 free")
        let violations = StructuralOracle.allocationViolations(before: Self.cleanFree, after: after)
        XCTAssertEqual(violations.map(\.kind), [.allocationLeak])
        XCTAssertTrue(violations[0].detail.contains("double-freed"), violations[0].detail)
    }

    /// A `free` that produced no count cannot be judged clean -- it must fail,
    /// not pass by default.
    func testMissingBaselineCountFails() {
        XCTAssertEqual(
            StructuralOracle.allocationViolations(before: "garbage", after: Self.cleanFree)
                .map(\.kind), [.allocationLeak])
    }
}
