//
//  VerifierTests.swift
//  RBFHammerCoreTests
//
//  Proves the content oracle reports every corruption class it claims to catch.
//
//  These tests exist because an oracle that has never gone red is not evidence.
//  Each one hands the verifier a specifically broken stream and requires the
//  matching violation back. A verifier that returned "clean" unconditionally --
//  the failure mode that made the old lost-update race useless -- fails all of
//  them.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import XCTest
@testable import RBFHammerCore

final class VerifierTests: XCTestCase {

    // ── Record format ─────────────────────────────────────────────────────────

    /// A record survives an encode/decode round trip with every field intact.
    func testRecordRoundTrip() throws {
        let record = Record(worker: 7, sequence: 42, payload: "hello")
        let decoded = try XCTUnwrap(Record.decode(record.encode()))
        XCTAssertEqual(decoded.worker, 7)
        XCTAssertEqual(decoded.sequence, 42)
        XCTAssertEqual(decoded.payload, "hello")
    }

    /// Every encoded record is exactly the fixed width, so a short tail can only
    /// mean a torn write. The whole framing strategy depends on this.
    func testEncodedRecordIsFixedWidth() {
        XCTAssertEqual(Record(worker: 1, sequence: 1, payload: "x").encode().count,
                       Record.width)
        XCTAssertEqual(Record(worker: 99, sequence: 99_999, payload: String(repeating: "z", count: 44))
                       .encode().count, Record.width)
    }

    /// The checksum stays inside a 16-bit INTEGER, which is all a 6809 BASIC09
    /// worker can accumulate. A wider checksum would be unrepresentable there.
    func testChecksumFitsIn16Bits() {
        let widest = Record(worker: 99, sequence: 99_999, payload: String(repeating: "\u{7F}", count: 44))
        XCTAssertLessThan(widest.checksum, 65_536)
    }

    // ── The oracle finds each corruption class ────────────────────────────────

    /// A clean run from two workers reports nothing.
    func testCleanRunHasNoViolations() {
        let data = Self.stream(workers: [1: 0..<10, 2: 0..<10])
        let expected = [WorkerExpectation(worker: 1, count: 10),
                        WorkerExpectation(worker: 2, count: 10)]
        XCTAssertEqual(Verifier.verify(data: data, expecting: expected), [])
    }

    /// A missing sequence number is a lost update -- the defect this whole
    /// harness exists to catch.
    func testMissingSequenceIsReportedAsLostUpdate() {
        let text = (0..<10).filter { $0 != 4 }
            .map { Record(worker: 1, sequence: $0, payload: "p\($0)").encode() }
            .joined()
        let violations = Verifier.verify(data: Data(text.utf8),
                                         expecting: [WorkerExpectation(worker: 1, count: 10)])
        XCTAssertTrue(violations.contains { $0.kind == .sequenceGap })
    }

    /// A truncated final record is a torn write, not merely a short file.
    func testTruncatedTailIsReportedAsTornRecord() {
        let intact = Record(worker: 1, sequence: 0, payload: "ok").encode()
        let torn = String(Record(worker: 1, sequence: 1, payload: "bad").encode().prefix(20))
        let violations = Verifier.verify(data: Data((intact + torn).utf8),
                                         expecting: [WorkerExpectation(worker: 1, count: 2)])
        XCTAssertTrue(violations.contains { $0.kind == .tornRecord })
    }

    /// A corrupted payload is caught by the checksum even though the framing
    /// is perfectly intact -- the case `dcheck` and `free` cannot see.
    func testCorruptedPayloadIsCaughtByChecksum() {
        let text = Record(worker: 1, sequence: 0, payload: "good").encode()
            .replacingOccurrences(of: "Pgood", with: "Pbadd")
        let violations = Verifier.verify(data: Data(text.utf8),
                                         expecting: [WorkerExpectation(worker: 1, count: 1)])
        XCTAssertTrue(violations.contains { $0.kind == .checksumMismatch })
    }

    /// A record from a worker that never ran means cross-file or cross-process
    /// bleed -- exactly what a broken FD-sharing ring would produce.
    func testPhantomWriterIsReported() {
        let data = Data(Record(worker: 9, sequence: 0, payload: "x").encode().utf8)
        let violations = Verifier.verify(data: data,
                                         expecting: [WorkerExpectation(worker: 1, count: 0)])
        XCTAssertTrue(violations.contains { $0.kind == .phantomWriter })
    }

    /// Two records sharing a worker and sequence mean a duplicated write.
    func testDuplicateRecordIsReported() {
        let one = Record(worker: 1, sequence: 3, payload: "x").encode()
        let violations = Verifier.verify(data: Data((one + one).utf8),
                                         expecting: [WorkerExpectation(worker: 1, count: 2)])
        XCTAssertTrue(violations.contains { $0.kind == .duplicate })
    }

    /// Fewer records than the worker reported writing means writes vanished.
    func testShortfallIsReportedAsCountMismatch() {
        let data = Self.stream(workers: [1: 0..<3])
        let violations = Verifier.verify(data: data,
                                         expecting: [WorkerExpectation(worker: 1, count: 10)])
        XCTAssertTrue(violations.contains { $0.kind == .countMismatch })
    }

    /// A garbage byte anywhere in a record is reported rather than tolerated.
    ///
    /// NOTE ON WHAT THIS DOES NOT PROVE: it does not justify the strict-ASCII
    /// decode in `Verifier`. Checked by mutation -- a lenient
    /// `String(decoding:as:)` also reports `.tornRecord` here, because the
    /// replacement character corrupts the sequence field and the field parse
    /// fails instead. Strict ASCII is kept because it fails AT the corruption
    /// rather than incidentally downstream, and cannot merge several bad bytes
    /// into one replacement character -- but no test currently distinguishes
    /// the two, and this one must not be cited as if it did.
    func testGarbageByteIsReportedAsTornRecord() {
        var bytes = Data(Record(worker: 1, sequence: 0, payload: "ok").encode().utf8)
        bytes[10] = 0xFF
        let violations = Verifier.verify(data: bytes,
                                         expecting: [WorkerExpectation(worker: 1, count: 1)])
        XCTAssertTrue(violations.contains { $0.kind == .tornRecord })
    }

    /// An empty file where records were expected is a total loss, and must not
    /// be mistaken for a clean run.
    func testEmptyFileIsNotCleanWhenRecordsWereExpected() {
        let violations = Verifier.verify(data: Data(),
                                         expecting: [WorkerExpectation(worker: 1, count: 5)])
        XCTAssertFalse(violations.isEmpty)
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// Builds a well-formed stream for the given workers and sequence ranges.
    private static func stream(workers: [Int: Range<Int>]) -> Data {
        let text = workers.sorted { $0.key < $1.key }.flatMap { worker, range in
            range.map { Record(worker: worker, sequence: $0, payload: "p\($0)").encode() }
        }.joined()
        return Data(text.utf8)
    }
}
