//
//  DestructiveTests6809.swift
//  RBFHammer6809Tests
//
//  Destructive scenarios against real NitrOS-9 (6809), on a formatted RAM disk
//  (`/r0`) so `dcheck` is instant. NitrOS-9's RBF is the community-maintained
//  clone; whatever it does here is a statement about NitrOS-9, and where it
//  differs from os9exec that difference is REPORTED, not failed.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import XCTest
@testable import RBFHammerCore

final class DestructiveTests6809: XCTestCase {

    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammer6809Tests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// Floor: one worker writes to a freshly `format`ted RAM disk, and the device
    /// comes back structurally intact. If this cannot pass, nothing about the
    /// RAM-disk plumbing (format, run on /r0, dcheck) means anything.
    func testRamDiskSingleWorkerIsIntactOn6809() throws {
        let file = "/r0/one.dat"
        let scenario = Scenario(name: "ramdisk-single-6809",
                                backend: .ramDisk,
                                workers: [WorkerSpec(id: 1, role: .append, file: file, count: 8)],
                                timeout: 180)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never completed. Clone at \(result.scratchPath)\n"
                     + result.transcript.suffix(2500))
        XCTAssertTrue(result.transcript.contains("worker 1 wrote 8"),
                      "the worker never wrote to the RAM disk:\n\(result.transcript.suffix(2500))")
        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "the RAM disk came back damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nClone at \(result.scratchPath)")
    }

    /// The cross-target counterpart to the os9exec delete-during-write LEAK. A
    /// writer holds a file open for write (`UPDATE`, non-sharable); mid-write it
    /// is `del`eted. On os9exec this is ALLOWED and leaks the post-delete
    /// clusters (see the 68k `DestructiveTests`). NitrOS-9's RBF instead REFUSES
    /// it -- `Error #253` (Non-sharable file busy / E$Share) -- so the leak
    /// cannot happen, and the RAM disk stays intact. This test pins that
    /// difference: the delete is rejected AND the device is clean.
    func testDeletingAFileOpenForWriteIsRefusedOn6809() throws {
        let file = "/r0/grow.dat"
        let scenario = Scenario(name: "delete-open-write-6809",
                                backend: .ramDisk,
                                workers: [WorkerSpec(id: 1, role: .append, file: file,
                                                     count: 20, nap: 400, napMode: .nilWrites)],
                                timeout: 180,
                                midFlight: ["sleep 60", "del \(file)"])
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never completed. Clone at \(result.scratchPath)\n"
                     + result.transcript.suffix(2500))

        // NitrOS-9 refuses to delete a file open for write -- the very thing that
        // makes the os9exec leak impossible here.
        XCTAssertTrue(result.transcript.contains("253"),
                      "expected NitrOS-9 to refuse the mid-write delete with E$Share #253 "
                    + "(os9exec allows it and leaks):\n\(result.transcript.suffix(2500))")

        // And with the delete refused, the writer finished and the disk is clean.
        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "NitrOS-9 RAM disk damaged after a refused mid-write delete:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nClone at \(result.scratchPath)")
    }

    /// One worker writes past the end of the 512-sector RAM disk. NitrOS-9's RBF
    /// must hit the wall with a clean error (the worker's ON ERROR reports it)
    /// and leave the device structurally intact -- exhaustion must not corrupt.
    func testExhaustingTheRamDiskLeavesItIntactOn6809() throws {
        let file = "/r0/big.dat"
        let scenario = Scenario(name: "disk-full-6809",
                                backend: .ramDisk,
                                workers: [WorkerSpec(id: 1, role: .append, file: file, count: 2500)],
                                timeout: 300)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "disk-full run never completed. Clone at \(result.scratchPath)\n"
                     + result.transcript.suffix(2500))

        // It must actually have run out of space: a worker that finished all 2500
        // records (never hit the wall) would make the intact check vacuous.
        XCTAssertFalse(result.transcript.contains("worker 1 wrote 2500"),
                       "the RAM disk was never exhausted -- disk-full proved nothing:\n"
                     + result.transcript.suffix(2500))
        XCTAssertTrue(result.transcript.contains("worker 1 ERROR err"),
                      "expected the worker to report an exhaustion error:\n"
                     + result.transcript.suffix(2500))

        let structural = StructuralOracle.structuralViolations(dcheck: result.transcript)
        XCTAssertEqual(structural, [],
                       "the exhausted RAM disk came back damaged:\n"
                     + structural.map(\.detail).joined(separator: "\n")
                     + "\nClone at \(result.scratchPath)")
    }
}
