//
//  Scenario6809Tests.swift
//  RBFHammer6809Tests
//
//  The hammer aimed at real NitrOS-9 on an emulated CoCo3:
//
//      swift test --package-path test --filter testSeedWorkerRunsOn6809
//
//  Slower than every other target here by an order of magnitude -- each run
//  boots a real 6809 for roughly forty seconds -- so the rosters are kept small
//  and the record-lock pair is the point rather than breadth.
//
//  NitrOS-9's RBF is a community-maintained clone, NOT Microware's code, and
//  neither it nor os9exec is an oracle for the other. A difference between the
//  two targets is REPORTED as a difference; it is not a 6809 failure.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import XCTest
@testable import RBFHammerCore

final class Scenario6809Tests: XCTestCase {

    /// Repository root, four levels up from this file.
    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammer6809Tests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// How many records each worker writes.
    private static var records: Int {
        Int(ProcessInfo.processInfo.environment["RBF_HAMMER_RECORDS"] ?? "") ?? 8
    }

    /// The disk the scenarios write to. `/DD` is the booted IDE hard disk --
    /// a real RBF device with a real allocator.
    private static let device = "/DD"

    /// Operating point for the record-lock pair, found by measurement (the
    /// rows are in `test/rbf-hammer/FAILABILITY.md`).
    ///
    /// A `.nilWrites` burst of this many writes, held between the read and the
    /// write, spans several of NitrOS-9's 60Hz preemption ticks -- long enough
    /// that a competing worker is scheduled into the window, and with no
    /// process fork (which is what made `.sleep` too slow to run). Chosen by
    /// bisection: nap 100 never interleaves, nap 1000 interleaves but holds the
    /// lock so long the locked roster starves and times out. At nap 400 the
    /// unlocked control loses ~13 of 40 updates every run while the locked
    /// roster keeps all 40 in about ten seconds.
    private static let lockNap = 400
    private static let lockWorkers = 4
    private static let lockIncrements = 10

    /// The 1-minute host load above which the lock pair is not run. The pair
    /// needs its four workers to actually OVERLAP inside the `.nilWrites`
    /// window; measured rock-solid below ~2 and fragile by ~4-5, where a racer
    /// starves and the roster either fails to interleave or hangs to the 600s
    /// timeout. Neither outcome is an RBF verdict -- both are the busy host --
    /// so the honest move is to skip, not to emit a false pass or a 10-minute
    /// hang. (See `test/rbf-hammer/FAILABILITY.md`, the 6809 load caveat.)
    private static let maxLoadForLockPair = 2.5

    /// The system's 1-minute load average, or nil if the host does not report
    /// one. `getloadavg` comes from libc via Foundation on the macOS host these
    /// 6809 tests require.
    private func hostLoadAverage() -> Double? {
        var samples = [Double](repeating: 0, count: 3)
        return getloadavg(&samples, 3) > 0 ? samples[0] : nil
    }

    /// Skips the calling lock-pair test when the host is too busy for its timing
    /// to mean anything. A load artifact must never read as a lock verdict.
    private func skipLockPairWhenHostBusy() throws {
        if let load = hostLoadAverage(), load > Self.maxLoadForLockPair {
            throw XCTSkip(String(format:
                "host 1-min load %.1f exceeds %.1f: the rmw lock pair needs a quiet host to "
              + "interleave. Running it loaded yields a hang or a false no-interleave, not an "
              + "RBF result -- re-run at low load.", load, Self.maxLoadForLockPair))
        }
    }

    // ── Floor ─────────────────────────────────────────────────────────────────

    /// The smallest possible end-to-end proof that the 6809 path works at all:
    /// one worker, one file, no concurrency. If this cannot pass, nothing about
    /// contention on this target means anything.
    func testSingleWorkerAppendsOn6809() throws {
        let file = "\(Self.device)/hammer.dat"
        let scenario = Scenario(name: "one-worker-6809",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file,
                                                     count: Self.records)],
                                timeout: 180)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never reported completion. Clone kept at \(result.scratchPath)\n"
                     + result.transcript)
        guard let data = result.produced[file] else {
            return XCTFail("\(file) was never produced:\n\(result.transcript)")
        }
        let violations = Verifier.verify(data: data,
                                         expecting: scenario.expectations(forFile: file))
        XCTAssertEqual(violations, [],
                       violations.map(\.detail).joined(separator: "\n"))
    }

    // ── Many workers, ONE file ────────────────────────────────────────────────

    /// Builds a roster of `population` slot-writers plus the provisioning
    /// worker that pre-extends the file.
    ///
    /// The provisioning worker's count is the file's FULL final slot count.
    /// OS-9 cannot write into a hole: a slot worker seeking past the current
    /// end of file dies with E$EOF, and its whole range then reads back
    /// missing -- which looks exactly like RBF losing data under concurrent
    /// writers, and is not.
    ///
    /// The nap is `.nilWrites`, NOT the `.sleep` default, and on this target
    /// that is load-bearing rather than a preference. `.sleep` forks a `SHELL
    /// "sleep"` per record; four slot workers launched together (the racers go
    /// out on ONE shell line -- see `Adapter6809.execute`) then fork in a burst,
    /// and NitrOS-9 starts refusing those forks with `Error #237`. What that
    /// error is NOT is the guest running out of memory: `mfree` taken mid-flight
    /// while 237s were flooding reported **1736K-1760K free**. Whatever the
    /// exhausted resource is, it is not the free-memory pool, and adding RAM
    /// does not reach it -- the guest is already booted with `-ram 2048`.
    /// The damage was two-faced and neither face named a fork: a worker died at
    /// its own `ON ERROR` (`worker N ERROR err 237`) so its slot range read back
    /// missing, or its `runb` failed to link the module it had just packed
    /// (`Error #043`), so that worker never ran and the roster sat out its full
    /// timeout. Both present as "RBF lost a writer's records". `.nilWrites`
    /// yields through ordinary writes to `/nil` with no fork at all.
    private func sharedRoster(_ population: Int, file: String, nap: Int) -> [WorkerSpec] {
        var roster = [WorkerSpec(id: 99, role: .create, file: file,
                                 count: population * Self.records)]
        roster += (1...population).map {
            WorkerSpec(id: $0, role: .slot, file: file, count: Self.records,
                       nap: nap, napMode: .nilWrites)
        }
        return roster
    }

    /// Four workers holding four paths onto one file. Exercises the FD ring,
    /// the shared sector buffers, the segment list and the allocator at once.
    ///
    /// Cannot detect a missing record lock -- slot ranges are disjoint and
    /// never overlap. That is what the `rmw` pair below is for.
    ///
    /// `midFlight` runs `mfree` while the roster is live, so the guest's own
    /// free-memory map lands in the transcript of any future failure. That is
    /// the measurement that disproved this test's long-standing "RAM Full"
    /// explanation, and it costs one read-only shell command.
    func testFourWorkersShareOneFileOn6809() throws {
        let file = "\(Self.device)/shared.dat"
        let scenario = Scenario(name: "four-workers-shared-6809",
                                backend: .rbfImage,
                                workers: sharedRoster(4, file: file, nap: 100),
                                timeout: 300,
                                midFlight: ["mfree"])
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never completed. Clone kept at \(result.scratchPath)\n"
                     + "workers reported:\n" + Self.workerLines(result.transcript)
                     + "\nguest transcript:\n\(result.transcript.suffix(20000))")
        guard let data = result.produced[file] else {
            return XCTFail("\(file) was never produced:\n\(result.transcript)")
        }
        let violations = Verifier.verify(data: data,
                                         expecting: scenario.expectations(forFile: file))
        // Violations alone cannot tell a lost write from a worker that never
        // wrote: "missing sequences" reads identically either way. The guest's
        // own per-worker report line says which, so it has to come out with the
        // verdict -- printing only the violation detail discards the evidence on
        // exactly the failure that needs it.
        XCTAssertEqual(violations, [],
                       violations.map(\.detail).joined(separator: "\n")
                     + "\n\nworkers reported:\n" + Self.workerLines(result.transcript)
                     + "\nfile: \(data.count) bytes"
                     + "\nclone kept at \(result.scratchPath)"
                     + "\nguest transcript (tail):\n\(result.transcript.suffix(3000))")
    }

    /// The guest's own `hammer: ...` report lines, in order, pulled out of a
    /// transcript that is mostly shell prompts and banners.
    private static func workerLines(_ transcript: String) -> String {
        let lines = transcript.split(whereSeparator: \.isNewline)
            .filter { $0.contains("hammer:") }
        return lines.isEmpty ? "(none -- no worker ever reported)"
                             : lines.joined(separator: "\n")
    }

    // ── THE RECORD-LOCK TEST ──────────────────────────────────────────────────
    // Every worker read-modify-writes the SAME record, so the locked extents
    // OVERLAP -- the only way a missing record lock can be detected at all.
    //
    // NitrOS-9's RBF is a community-maintained clone. Whatever these report is
    // a statement about NitrOS-9, never about what OS-9 "should" do.

    /// Runs an rmw roster and returns the final tally the workers left behind.
    private func finalTally(workers population: Int, increments: Int,
                            nap: Int, role: WorkerSpec.Role,
                            napMode: NapMode = .sleep) throws -> Int {
        let file = "\(Self.device)/tally.dat"
        // Binary rmw roles read back an integer record, so they need a binary
        // provisioner sized to match; the text roles need the text one.
        let binary = role == .rmwbin || role == .rmwbig
        let seedRole: WorkerSpec.Role = switch role {
            case .rmwbig: .seedbig
            case .rmwbin: .seedbin
            default:      .seed
        }
        var roster = [WorkerSpec(id: 98, role: seedRole, file: file, count: 1)]
        roster += (1...population).map {
            // The lock pair below uses `.nilWrites` with a LARGE burst -- see
            // the operating-point constants and the tests. An earlier reading
            // that `.nilWrites` "never interleaves" was measured with a nap of
            // ONE /nil write, which opens no window at all; a burst of a few
            // hundred writes spans several of NitrOS-9's 60Hz preemption ticks
            // and does interleave, with no process fork. `.sleep` is retained
            // as the caller's choice but forks a `sleep` per increment, which
            // is why it was too slow here. Whichever the caller picks, the
            // control (`rmwfree`) must lose updates or the locked result means
            // nothing.
            WorkerSpec(id: $0, role: role, file: file, count: increments,
                       nap: nap, napMode: napMode)
        }
        let scenario = Scenario(name: "rmw-6809-\(population)x\(increments)",
                                backend: .rbfImage, workers: roster, timeout: 600)
        // RBF_GOLDEN points the run at a specific disk image (e.g. a fixed-RBF
        // build), so the same reproduction can be A/B'd against stock and fix.
        let golden = ProcessInfo.processInfo.environment["RBF_GOLDEN"]
            .map { URL(fileURLWithPath: $0) }
        let result = try Adapter6809(repoRoot: Self.repoRoot, goldenMaster: golden).run(scenario)

        XCTAssertFalse(result.timedOut, "rmw roster hung; clone \(result.scratchPath)")
        guard let data = result.produced[file] else {
            XCTFail("no tally file. Transcript:\n\(result.transcript)")
            return -1
        }
        if binary {
            // rec(1) is the first of five 16-bit integers, stored MSB-first
            // (6809 is big-endian). The tally is that leading word.
            guard data.count >= 2 else {
                XCTFail("binary tally too short (\(data.count) bytes). Transcript:\n\(result.transcript)")
                return -1
            }
            return Int(data[data.startIndex]) << 8 | Int(data[data.startIndex + 1])
        }
        guard let text = String(bytes: data.prefix(9), encoding: .ascii),
              text.hasPrefix("T"), let tally = Int(text.dropFirst()) else {
            XCTFail("no readable tally. Transcript:\n\(result.transcript)")
            return -1
        }
        return tally
    }

    /// Env-driven bench: measure interleave/timing without editing code per run.
    ///
    /// Inert unless RBF_MEASURE is set. Knobs (all optional):
    ///   RBF_ROLE=rmw|rmwfree   RBF_NAP_MODE=sleep|nil   RBF_NAP_COUNT=<n>
    ///   RBF_WORKERS=<n>        RBF_INCREMENTS=<n>
    /// Prints "MEASURED tally=<t> expected=<e>" and never asserts, so a run
    /// always reports what happened rather than failing the process.
    func testMeasure6809() throws {
        let env = ProcessInfo.processInfo.environment
        guard env["RBF_MEASURE"] != nil else {
            throw XCTSkip("measurement harness; set RBF_MEASURE=1 to run")
        }
        let role: WorkerSpec.Role = switch env["RBF_ROLE"] {
            case "rmw": .rmw
            case "rmwbin": .rmwbin
            case "rmwbig": .rmwbig
            default: .rmwfree
        }
        let napMode: NapMode = env["RBF_NAP_MODE"] == "nil" ? .nilWrites : .sleep
        let nap = Int(env["RBF_NAP_COUNT"] ?? "") ?? 1
        let workers = Int(env["RBF_WORKERS"] ?? "") ?? 4
        let increments = Int(env["RBF_INCREMENTS"] ?? "") ?? 10

        let started = Date()
        let tally = try finalTally(workers: workers, increments: increments,
                                   nap: nap, role: role, napMode: napMode)
        let elapsed = Date().timeIntervalSince(started)
        print("MEASURED role=\(role.rawValue) napMode=\(napMode.rawValue) nap=\(nap) "
            + "\(workers)x\(increments) tally=\(tally) expected=\(workers * increments) "
            + "elapsed=\(Int(elapsed))s")
    }

    /// Runs the write-only-Creat follow scenario and returns how many records the
    /// follower saw. A WRITE-only producer creates a file and writes `records`
    /// records -- the first two fast, the rest paced -- while a follower reads it
    /// to EOF after a brief nap. Trailing to the end (count == records) is the
    /// DOCUMENTED behaviour and what stock does; stopping at the initial EOF
    /// (count small) is what the withdrawn `lockmode` patch caused. `golden`
    /// selects the image (nil = default stock master).
    private func followerRecordCount(records: Int, golden: URL?) throws -> Int? {
        let file = "/r0/wo.dat"
        let roster = [
            WorkerSpec(id: 1, role: .writeonly, file: file, count: records, nap: 40, napMode: .sleep),
            WorkerSpec(id: 2, role: .follow, file: file, count: 1, nap: 15, napMode: .sleep),
        ]
        let scenario = Scenario(name: "follow-6809", backend: .ramDisk, workers: roster, timeout: 300)
        let result = try Adapter6809(repoRoot: Self.repoRoot, goldenMaster: golden).run(scenario)
        return result.transcript.split(whereSeparator: \.isNewline)
            .first { $0.contains("follow done") }?
            .split(separator: " ").last.flatMap { Int($0) }
    }

    /// Env probe for interactive A/B (set RBF_FOLLOW; RBF_GOLDEN picks the image).
    func testFollowProbe6809() throws {
        let env = ProcessInfo.processInfo.environment
        guard env["RBF_FOLLOW"] != nil else { throw XCTSkip("follow probe; set RBF_FOLLOW=1") }
        let records = Int(env["RBF_FOLLOW_RECS"] ?? "") ?? 8
        let count = try followerRecordCount(records: records,
                                            golden: env["RBF_GOLDEN"].map { URL(fileURLWithPath: $0) })
        FileHandle.standardError.write(Data("FOLLOW count=\(count.map(String.init) ?? "?") of \(records)\n".utf8))
    }

    /// Runs the MIXED scenario (blind spot #5) and returns record 0's final
    /// counter. A `wobin` write-only producer CREATEs the file (Creat lock path)
    /// and writes paced records while `racers` `rmwmix` update-mode workers
    /// increment record 0 back-to-back (lost-update path) on the SAME file -- the
    /// first live interaction of the lockmode and lostupdate fixes. Correct final
    /// counter is `racers * increments`; a short count is a lost update surviving
    /// the mix. `/DD` so the counter record can be read back.
    private func mixedCounter(racers: Int, increments: Int, golden: URL?) throws -> Int {
        let file = "/DD/mix.dat"
        var roster = [WorkerSpec(id: 1, role: .wobin, file: file, count: 8, nap: 40, napMode: .sleep)]
        roster += (2...(racers + 1)).map {
            WorkerSpec(id: $0, role: .rmwmix, file: file, count: increments, nap: 30, napMode: .sleep)
        }
        let scenario = Scenario(name: "mix-6809", backend: .rbfImage, workers: roster, timeout: 600)
        let result = try Adapter6809(repoRoot: Self.repoRoot, goldenMaster: golden).run(scenario)
        guard let data = result.produced[file], data.count >= 2 else { return -1 }
        return Int(data[data.startIndex]) << 8 | Int(data[data.startIndex + 1])
    }

    /// Env probe for the mixed scenario (set RBF_MIX; RBF_GOLDEN picks the image).
    func testMixProbe6809() throws {
        let env = ProcessInfo.processInfo.environment
        guard env["RBF_MIX"] != nil else { throw XCTSkip("mix probe; set RBF_MIX=1") }
        let increments = Int(env["RBF_MIX_INC"] ?? "") ?? 200
        let counter = try mixedCounter(racers: 2, increments: increments,
                                       golden: env["RBF_GOLDEN"].map { URL(fileURLWithPath: $0) })
        FileHandle.standardError.write(Data("MIX counter=\(counter) expected=\(2 * increments)\n".utf8))
    }

    /// Runs the deadlock probe (blind spot #4) and returns whether RBF returned
    /// `E$DeadLk` (#254) and whether the roster hung. Two `cross` workers each
    /// open the file twice and lock two records in opposite orders (a crossed
    /// wait). `#254 fired && !hung` = detection works; `hung` = the wait/park
    /// rewrite broke detection (gold). The ~1s hold covers `runb` launch skew so
    /// both lock their first record before either reaches the second.
    private func deadlockOutcome(golden: URL?) throws -> (fired254: Bool, hung: Bool, transcript: String) {
        let file = "/r0/dl.dat"
        let roster = [
            WorkerSpec(id: 98, role: .seedbin2, file: file, count: 1),
            WorkerSpec(id: 1, role: .cross, file: file, count: 1, nap: 100, napMode: .sleep),
            WorkerSpec(id: 2, role: .cross, file: file, count: 1, nap: 100, napMode: .sleep),
        ]
        let scenario = Scenario(name: "deadlock-6809", backend: .ramDisk, workers: roster, timeout: 120)
        let result = try Adapter6809(repoRoot: Self.repoRoot, goldenMaster: golden).run(scenario)
        return (result.transcript.contains("cross error 254"), result.timedOut, result.transcript)
    }

    /// Env probe for the deadlock scenario (set RBF_DEADLOCK; RBF_GOLDEN picks image).
    func testDeadlockProbe6809() throws {
        let env = ProcessInfo.processInfo.environment
        guard env["RBF_DEADLOCK"] != nil else { throw XCTSkip("deadlock probe; set RBF_DEADLOCK=1") }
        let outcome = try deadlockOutcome(golden: env["RBF_GOLDEN"].map { URL(fileURLWithPath: $0) })
        let report = "DEADLOCK fired254=\(outcome.fired254) hung=\(outcome.hung)\n"
            + "===TRANSCRIPT===\n\(outcome.transcript)\n===END===\n"
        FileHandle.standardError.write(Data(report.utf8))
    }

    /// ★ Blind spot #5: the two NitrOS-9 fixes (lockmode + lostupdate) exercised
    /// TOGETHER on one file for the first time. A write-only producer creates the
    /// file (Creat lock path) and writes it while two update-mode racers increment
    /// record 0 back-to-back (lost-update path). The record-0 counter must end at
    /// `racers * increments`; a short count is a lost update surviving the mix.
    ///
    /// Teeth proven on stock before this (counter 356 of 400) and clean on the
    /// combined-fix image (400 of 400) -- the fixes do not interfere. Pinned with
    /// XCTExpectFailure because the default boot image is still stock; retries up
    /// to 3x for the bimodal loss variance and takes the bug as present the moment
    /// any run comes up short, so a lucky-clean run cannot masquerade as a fix.
    func testMixedWriteOnlyAndRmwKeepEveryUpdateOn6809() throws {
        let racers = 2, increments = 200
        let expected = racers * increments
        var lost = 0
        for _ in 1...3 {
            let counter = try mixedCounter(racers: racers, increments: increments, golden: nil)
            if counter >= 0 && counter < expected { lost = expected - counter; break }
        }
        XCTExpectFailure("stock RBF loses updates when write-only Creat traffic races update-mode RMW") {
            XCTAssertEqual(lost, 0,
                           "mixed write-only + update-mode RMW lost \(lost) of \(expected) "
                         + "on the same file -- the two lock paths interfered")
        }
    }

    /// ★ Blind spot #4: crossed record holds must be DETECTED as a deadlock, not
    /// hang. Two workers each open the file twice (so each holds two record
    /// auto-locks -- a single path holds only one) and lock record 0 and record 1
    /// in opposite orders. RBF must break the cycle with `E$DeadLk` (#254), which
    /// is the exact detection the lostupdate fix's wait/park rewrite could have
    /// regressed. Verified live: #254 fires on BOTH stock and the combined-fix
    /// image, never a hang -- the fix preserved detection.
    ///
    /// A regression guard, not an XCTExpectFailure: the correct behaviour (detect,
    /// don't hang) holds on the default image today. A hang would fail loudly
    /// (gold). Retries up to 3x because the crossed hold depends on both workers
    /// overlapping; a run where they don't cross is retried rather than passed
    /// vacuously, so the guard only passes when #254 actually fired.
    func testCrossedRecordHoldsAreDeadlockDetectedOn6809() throws {
        for _ in 1...3 {
            let outcome = try deadlockOutcome(golden: nil)
            if outcome.hung {
                return XCTFail("crossed record holds HUNG -- deadlock detection is broken:\n"
                             + outcome.transcript)
            }
            if outcome.fired254 { return }   // detection fired -- the guard is satisfied
        }
        XCTFail("E$DeadLk (#254) never fired in 3 tries -- the crossed hold was not exercised, "
              + "so this proved nothing; the timing needs tuning")
    }

    /// A WRITE-only producer MUST make a reader follow it. This assertion was
    /// inverted on 2026-07-27; it previously demanded the follower stop.
    ///
    /// The 6809 System Programmers Manual §6.6.3 states that a program creating a
    /// file for sequential output gains EOF Lock as soon as the file is created,
    /// and that no other process can then pass that writer through the file. Its
    /// own illustration is an assembly listing redirected to disk -- plain `>`
    /// output, a write-only path -- with a spooler reading behind it. §6.6.1's
    /// update-mode restriction is scoped to *reads* and does not reach this. The
    /// same passage appears in the Tandy Technical Reference (:3799), the Tandy
    /// Level Two Development System manual (:12732) and the OS-9/68000 v2.4
    /// Technical Reference (:6307).
    ///
    /// So stock is right and trails to the full count. The withdrawn `lockmode`
    /// patch gated the EOF-lock and Creat sites on `PD.MOD == UPDAT.`, which
    /// stopped the follower at the initial EOF -- and this test, asserting the
    /// old expectation, certified that regression as correct. Teeth: run against
    /// `rbf.combined-fix-testdisk.mn` via `RBF_GOLDEN` and it fails (2 of 8).
    func testWriteOnlyProducerMakesAReaderFollowOn6809() throws {
        let records = 8
        guard let count = try followerRecordCount(records: records, golden: nil) else {
            return XCTFail("follower never reported a count")
        }
        XCTAssertEqual(count, records,
                       "follower stopped at \(count) of \(records) behind a write-only producer "
                     + "-- it must trail to the producer's end (SPM 6.6.3)")
    }

    /// CONTROL, and the one that must be read first: the identical race with NO
    /// lock taken (a READ path and a separate WRITE path, so RBF's update-mode
    /// auto-lock never engages).
    ///
    /// This must LOSE updates. If it does not, the workers never interleaved
    /// and the locked result below proves nothing whatsoever -- which is
    /// exactly how the old counter race passed 600/600 against code with no
    /// locking at all.
    func testUnlockedReadModifyWriteDoesLoseUpdatesOn6809() throws {
        try skipLockPairWhenHostBusy()
        let expected = Self.lockWorkers * Self.lockIncrements
        let tally = try finalTally(workers: Self.lockWorkers, increments: Self.lockIncrements,
                                   nap: Self.lockNap, role: .rmwfree, napMode: .nilWrites)
        XCTAssertLessThan(tally, expected,
                          "unlocked RMW kept a perfect tally of \(tally) -- the race never "
                        + "interleaved, so any locked result on this target is meaningless. "
                        + "If this starts passing, the .nilWrites window has stopped opening "
                        + "and every other lock result here must be treated as meaningless.")
    }

    /// The locked race: RBF auto-locks the record an update-mode read returns.
    /// A short tally is a lost update.
    ///
    /// Meaningful only because its control loses updates in the SAME
    /// configuration -- run `testUnlockedReadModifyWriteDoesLoseUpdatesOn6809`
    /// first. A green here on its own would say the workers never contended,
    /// not that the lock worked.
    func testConcurrentReadModifyWriteLosesNoUpdatesOn6809() throws {
        try skipLockPairWhenHostBusy()
        let expected = Self.lockWorkers * Self.lockIncrements
        let tally = try finalTally(workers: Self.lockWorkers, increments: Self.lockIncrements,
                                   nap: Self.lockNap, role: .rmw, napMode: .nilWrites)
        XCTAssertEqual(tally, expected,
                       "lost update on NitrOS-9: expected \(expected), got \(tally)")
    }

    // ── The live lost-update bug, reproduced ──────────────────────────────────

    /// ★ A REPRODUCED DATA-LOSS BUG. Binary `GET`/`PUT` read-modify-write drops
    /// updates on stock NitrOS-9, where the byte-for-byte identical TEXT path
    /// (`READ`/`PRINT`, `testConcurrent...` above) keeps a perfect tally. Four
    /// workers each do 200 back-to-back `SEEK0/GET/+1/SEEK0/PUT` on ONE 10-byte
    /// record; with no gap they genuinely park and wake on each other's record
    /// lock, and the binary `I$Read`/`I$Write` lock-retry-after-park re-presents
    /// a clobbered byte count (0) so the woken waiter claims nothing and runs
    /// UNLOCKED, losing the update. The ONLY variable versus the passing text
    /// test is the I/O verb.
    ///
    /// Measured ~250-300 of 800 lost, every run, INCLUDING under host load --
    /// it is volume-driven, not a timing knife-edge, so unlike the lock pair it
    /// needs no load guard and does not flake toward a clean tally.
    ///
    /// Pinned with `XCTExpectFailure`: the correctness assertion (no updates
    /// lost) FAILS on the buggy RBF, so the suite CATALOGS a reproduced
    /// data-loss bug rather than reporting green. If RBF is ever fixed here this
    /// flips to "unexpectedly passed" and demands the marker be removed. Root
    /// cause, and A/B modules (`rbf.stock.mn` vs the fix), are in
    /// `docs/nitros9-rbf-lostupdate-*` and `docs/nitros9-rbf-reference/`.
    func testBinaryReadModifyWriteLosesUpdatesOn6809() throws {
        let workers = 4, increments = 200
        let expected = workers * increments

        // The reproduction is bimodal: when the racers' first GETs coincide it
        // drops ~250-300 of 800; a rarer run whose module loads happen to
        // stagger keeps a clean tally. So try up to three times and take the
        // bug as PRESENT the moment any try loses -- a single lucky-clean run
        // must not masquerade as a fix. Only three clean runs in a row (what an
        // actual fix would produce) leave `lost` at zero and trip the
        // XCTExpectFailure below into an "unexpectedly passed" that says: check
        // whether RBF was fixed here.
        var lost = 0
        var everRan = false
        for _ in 1...3 {
            let tally = try finalTally(workers: workers, increments: increments,
                                       nap: 0, role: .rmwbin, napMode: .nilWrites)
            // A tally of exactly 0 is NOT "every update was lost" -- it is what
            // a roster that never incremented at all looks like, and the two are
            // indistinguishable from the counter alone. The reproduction's own
            // measured range is ~250-300 of 800, so a full-width 800 is out of
            // family and must not be banked as a reproduced bug. Retry; only if
            // no try ever moved the counter do we report inconclusive.
            if tally == 0 { continue }
            everRan = true
            if tally < expected { lost = expected - tally; break }
        }

        guard everRan else {
            return XCTFail("inconclusive: the counter never moved off 0 in 3 tries, so this "
                         + "measured nothing about record locking -- check that the racers "
                         + "actually launched before reading any verdict from this test")
        }

        XCTExpectFailure("stock NitrOS-9 drops binary GET/PUT updates -- live data-loss bug") {
            XCTAssertEqual(lost, 0,
                           "binary RMW lost \(lost) of \(expected) updates -- "
                         + "the record lock's retry-after-park ran unlocked")
        }
    }

    // ── Backends that do not exist here ───────────────────────────────────────

    /// A host directory has no NitrOS-9 equivalent, and the adapter must say so
    /// rather than quietly running the scenario on `/DD`.
    ///
    /// This guards the silent-redirect failure mode directly: a scenario that
    /// ran somewhere other than where it claimed would report a pass for a code
    /// path never entered.
    func testHostDirectoryBackendIsRefusedNotRedirected() throws {
        XCTAssertThrowsError(try Backend6809.device(.hostDirectory)) { error in
            XCTAssertTrue("\(error)".contains("does not exist on 6809"),
                          "expected an explicit refusal, got: \(error)")
        }
    }

    /// The RAM disk is now VERIFIED and supported: `.ramDisk` resolves to `/r0`,
    /// the small fast device the destructive scenarios `format` and `dcheck`
    /// (see `DestructiveTests6809`). It used to be refused as unverified.
    func testRAMDiskBackendResolvesToR0() throws {
        XCTAssertEqual(try Backend6809.device(.ramDisk), "/r0")
    }
}
