//
//  Scenario6809Tests.swift
//  RBFHammer6809Tests
//
//  The hammer aimed at real NitrOS-9 on an emulated CoCo3:
//
//      swift test --package-path test --filter testSeedWorkerRunsOn6809
//
//  Slower than every other target here by an order of magnitude -- each run
//  boots a real 6809 for roughly forty seconds -- so the rosters are kept small
//  and the record-lock pair is the point rather than breadth.
//
//  NitrOS-9's RBF is a community-maintained clone, NOT Microware's code, and
//  neither it nor os9exec is an oracle for the other. A difference between the
//  two targets is REPORTED as a difference; it is not a 6809 failure.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import XCTest
@testable import RBFHammerCore

final class Scenario6809Tests: XCTestCase {

    /// Repository root, four levels up from this file.
    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammer6809Tests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// How many records each worker writes.
    private static var records: Int {
        Int(ProcessInfo.processInfo.environment["RBF_HAMMER_RECORDS"] ?? "") ?? 8
    }

    /// The disk the scenarios write to. `/DD` is the booted IDE hard disk --
    /// a real RBF device with a real allocator.
    private static let device = "/DD"

    // ── Floor ─────────────────────────────────────────────────────────────────

    /// The smallest possible end-to-end proof that the 6809 path works at all:
    /// one worker, one file, no concurrency. If this cannot pass, nothing about
    /// contention on this target means anything.
    func testSingleWorkerAppendsOn6809() throws {
        let file = "\(Self.device)/hammer.dat"
        let scenario = Scenario(name: "one-worker-6809",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file,
                                                     count: Self.records)],
                                timeout: 180)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never reported completion. Clone kept at \(result.scratchPath)\n"
                     + result.transcript)
        guard let data = result.produced[file] else {
            return XCTFail("\(file) was never produced:\n\(result.transcript)")
        }
        let violations = Verifier.verify(data: data,
                                         expecting: scenario.expectations(forFile: file))
        XCTAssertEqual(violations, [],
                       violations.map(\.detail).joined(separator: "\n"))
    }

    // ── Many workers, ONE file ────────────────────────────────────────────────

    /// Builds a roster of `population` slot-writers plus the provisioning
    /// worker that pre-extends the file.
    ///
    /// The provisioning worker's count is the file's FULL final slot count.
    /// OS-9 cannot write into a hole: a slot worker seeking past the current
    /// end of file dies with E$EOF, and its whole range then reads back
    /// missing -- which looks exactly like RBF losing data under concurrent
    /// writers, and is not.
    private func sharedRoster(_ population: Int, file: String, nap: Int) -> [WorkerSpec] {
        var roster = [WorkerSpec(id: 99, role: .create, file: file,
                                 count: population * Self.records)]
        roster += (1...population).map {
            WorkerSpec(id: $0, role: .slot, file: file, count: Self.records, nap: nap)
        }
        return roster
    }

    /// Four workers holding four paths onto one file. Exercises the FD ring,
    /// the shared sector buffers, the segment list and the allocator at once.
    ///
    /// Cannot detect a missing record lock -- slot ranges are disjoint and
    /// never overlap. That is what the `rmw` pair below is for.
    func testFourWorkersShareOneFileOn6809() throws {
        let file = "\(Self.device)/shared.dat"
        let scenario = Scenario(name: "four-workers-shared-6809",
                                backend: .rbfImage,
                                workers: sharedRoster(4, file: file, nap: 1),
                                timeout: 300)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never completed. Clone kept at \(result.scratchPath)\n"
                     + "guest transcript:\n\(result.transcript.suffix(3000))")
        guard let data = result.produced[file] else {
            return XCTFail("\(file) was never produced:\n\(result.transcript)")
        }
        let violations = Verifier.verify(data: data,
                                         expecting: scenario.expectations(forFile: file))
        XCTAssertEqual(violations, [],
                       violations.map(\.detail).joined(separator: "\n"))
    }

    // ── THE RECORD-LOCK TEST ──────────────────────────────────────────────────
    // Every worker read-modify-writes the SAME record, so the locked extents
    // OVERLAP -- the only way a missing record lock can be detected at all.
    //
    // NitrOS-9's RBF is a community-maintained clone. Whatever these report is
    // a statement about NitrOS-9, never about what OS-9 "should" do.

    /// Runs an rmw roster and returns the final tally the workers left behind.
    private func finalTally(workers population: Int, increments: Int,
                            nap: Int, role: WorkerSpec.Role) throws -> Int {
        let file = "\(Self.device)/tally.dat"
        var roster = [WorkerSpec(id: 98, role: .seed, file: file, count: 1)]
        roster += (1...population).map {
            // `.sleep`, and the cheaper `.nilWrites` is NOT an option here --
            // measured, not assumed. With `.nilWrites` the whole roster runs in
            // 11 seconds and the UNLOCKED control kept a perfect 100/100
            // tally: writing to /nil does not yield long enough for the
            // read-modify-write to ever interleave on this target, so every
            // result in that configuration is worthless. That is the exact
            // shape of the old counter race passing 600/600 with no locking.
            //
            // `SHELL "sleep n"` is a genuine F$Sleep and does open the window,
            // at the cost of forking a process per increment -- roughly a
            // quarter of an increment per second on a 2MHz 6809, which is why
            // the roster is kept small.
            WorkerSpec(id: $0, role: role, file: file, count: increments,
                       nap: nap, napMode: .sleep)
        }
        let scenario = Scenario(name: "rmw-6809-\(population)x\(increments)",
                                backend: .rbfImage, workers: roster, timeout: 600)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut, "rmw roster hung; clone \(result.scratchPath)")
        guard let data = result.produced[file],
              let text = String(bytes: data.prefix(9), encoding: .ascii),
              text.hasPrefix("T"), let tally = Int(text.dropFirst()) else {
            XCTFail("no readable tally. Transcript:\n\(result.transcript)")
            return -1
        }
        return tally
    }

    /// CONTROL, and the one that must be read first: the identical race with NO
    /// lock taken (a READ path and a separate WRITE path, so RBF's update-mode
    /// auto-lock never engages).
    ///
    /// This must LOSE updates. If it does not, the workers never interleaved
    /// and the locked result below proves nothing whatsoever -- which is
    /// exactly how the old counter race passed 600/600 against code with no
    /// locking at all.
    func testUnlockedReadModifyWriteDoesLoseUpdatesOn6809() throws {
        throw XCTSkip("""
            NOT ESTABLISHED ON 6809 -- skipped so it cannot be mistaken for coverage.

            Two configurations were measured, and neither is usable yet:

            * napMode .nilWrites  -- roster completes in 11s, but the UNLOCKED
              control kept a PERFECT 100/100 tally. The read-modify-write never
              interleaves, so a locked pass here would mean nothing. This is the
              600/600 counter-race failure mode exactly.
            * napMode .sleep      -- genuinely opens the window (a 4x25 roster
              reached 75/100 before a 300s deadline, so it does interleave and
              does lose updates), but forks a process per increment at roughly
              0.26 increments/second. A 4x10 roster still exceeded 10 minutes.

            So the mechanism that interleaves is too slow to run as a test, and
            the mechanism that is fast enough does not interleave. Until one of
            those is resolved, NitrOS-9's record locking is UNMEASURED by this
            harness -- which is NOT the same as "NitrOS-9 passes".

            Next step: PACK the worker once and launch it with runb, removing
            the per-launch BASIC09 parse, then re-measure whether .sleep with a
            small roster fits in a sane runtime.
            """)
        let workers = 4, increments = 10
        let tally = try finalTally(workers: workers, increments: increments,
                                   nap: 1, role: .rmwfree)
        XCTAssertLessThan(tally, workers * increments,
                          "unlocked RMW kept a perfect tally of \(tally) -- the race never "
                        + "interleaved, so any locked result on this target is meaningless")
    }

    /// The locked race: RBF auto-locks the record an update-mode read returns.
    /// A short tally is a lost update.
    func testConcurrentReadModifyWriteLosesNoUpdatesOn6809() throws {
        throw XCTSkip("""
            Skipped for the same reason as its control, and specifically because
            its control is not passing. A locked result is only meaningful once
            the UNLOCKED control has been shown to lose updates in the SAME
            configuration -- otherwise a green here says the workers never
            contended, not that the lock worked.

            See testUnlockedReadModifyWriteDoesLoseUpdatesOn6809.
            """)
        let workers = 4, increments = 10
        let tally = try finalTally(workers: workers, increments: increments,
                                   nap: 1, role: .rmw)
        XCTAssertEqual(tally, workers * increments,
                       "lost update on NitrOS-9: expected \(workers * increments), "
                     + "got \(tally)")
    }

    // ── Backends that do not exist here ───────────────────────────────────────

    /// A host directory has no NitrOS-9 equivalent, and the adapter must say so
    /// rather than quietly running the scenario on `/DD`.
    ///
    /// This guards the silent-redirect failure mode directly: a scenario that
    /// ran somewhere other than where it claimed would report a pass for a code
    /// path never entered.
    func testHostDirectoryBackendIsRefusedNotRedirected() throws {
        XCTAssertThrowsError(try Backend6809.device(.hostDirectory)) { error in
            XCTAssertTrue("\(error)".contains("does not exist on 6809"),
                          "expected an explicit refusal, got: \(error)")
        }
    }

    /// The RAM disk modules are present in the boot image but provisioning them
    /// has not been verified live, so it is refused rather than assumed.
    func testRAMDiskBackendIsRefusedUntilVerified() throws {
        XCTAssertThrowsError(try Backend6809.device(.ramDisk))
    }
}
