//
//  Scenario6809Tests.swift
//  RBFHammer6809Tests
//
//  The hammer aimed at real NitrOS-9 on an emulated CoCo3:
//
//      swift test --package-path test --filter testSeedWorkerRunsOn6809
//
//  Slower than every other target here by an order of magnitude -- each run
//  boots a real 6809 for roughly forty seconds -- so the rosters are kept small
//  and the record-lock pair is the point rather than breadth.
//
//  NitrOS-9's RBF is a community-maintained clone, NOT Microware's code, and
//  neither it nor os9exec is an oracle for the other. A difference between the
//  two targets is REPORTED as a difference; it is not a 6809 failure.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-20-2026
//

import XCTest
@testable import RBFHammerCore

final class Scenario6809Tests: XCTestCase {

    /// Repository root, four levels up from this file.
    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // RBFHammer6809Tests/
        .deletingLastPathComponent()   // Tests/
        .deletingLastPathComponent()   // test/
        .deletingLastPathComponent()   // repo root

    /// How many records each worker writes.
    private static var records: Int {
        Int(ProcessInfo.processInfo.environment["RBF_HAMMER_RECORDS"] ?? "") ?? 8
    }

    /// The disk the scenarios write to. `/DD` is the booted IDE hard disk --
    /// a real RBF device with a real allocator.
    private static let device = "/DD"

    /// Operating point for the record-lock pair, found by measurement (the
    /// rows are in `test/rbf-hammer/FAILABILITY.md`).
    ///
    /// A `.nilWrites` burst of this many writes, held between the read and the
    /// write, spans several of NitrOS-9's 60Hz preemption ticks -- long enough
    /// that a competing worker is scheduled into the window, and with no
    /// process fork (which is what made `.sleep` too slow to run). Chosen by
    /// bisection: nap 100 never interleaves, nap 1000 interleaves but holds the
    /// lock so long the locked roster starves and times out. At nap 400 the
    /// unlocked control loses ~13 of 40 updates every run while the locked
    /// roster keeps all 40 in about ten seconds.
    private static let lockNap = 400
    private static let lockWorkers = 4
    private static let lockIncrements = 10

    /// The 1-minute host load above which the lock pair is not run. The pair
    /// needs its four workers to actually OVERLAP inside the `.nilWrites`
    /// window; measured rock-solid below ~2 and fragile by ~4-5, where a racer
    /// starves and the roster either fails to interleave or hangs to the 600s
    /// timeout. Neither outcome is an RBF verdict -- both are the busy host --
    /// so the honest move is to skip, not to emit a false pass or a 10-minute
    /// hang. (See `test/rbf-hammer/FAILABILITY.md`, the 6809 load caveat.)
    private static let maxLoadForLockPair = 2.5

    /// The system's 1-minute load average, or nil if the host does not report
    /// one. `getloadavg` comes from libc via Foundation on the macOS host these
    /// 6809 tests require.
    private func hostLoadAverage() -> Double? {
        var samples = [Double](repeating: 0, count: 3)
        return getloadavg(&samples, 3) > 0 ? samples[0] : nil
    }

    /// Skips the calling lock-pair test when the host is too busy for its timing
    /// to mean anything. A load artifact must never read as a lock verdict.
    private func skipLockPairWhenHostBusy() throws {
        if let load = hostLoadAverage(), load > Self.maxLoadForLockPair {
            throw XCTSkip(String(format:
                "host 1-min load %.1f exceeds %.1f: the rmw lock pair needs a quiet host to "
              + "interleave. Running it loaded yields a hang or a false no-interleave, not an "
              + "RBF result -- re-run at low load.", load, Self.maxLoadForLockPair))
        }
    }

    // ── Floor ─────────────────────────────────────────────────────────────────

    /// The smallest possible end-to-end proof that the 6809 path works at all:
    /// one worker, one file, no concurrency. If this cannot pass, nothing about
    /// contention on this target means anything.
    func testSingleWorkerAppendsOn6809() throws {
        let file = "\(Self.device)/hammer.dat"
        let scenario = Scenario(name: "one-worker-6809",
                                backend: .rbfImage,
                                workers: [WorkerSpec(id: 1, role: .append, file: file,
                                                     count: Self.records)],
                                timeout: 180)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never reported completion. Clone kept at \(result.scratchPath)\n"
                     + result.transcript)
        guard let data = result.produced[file] else {
            return XCTFail("\(file) was never produced:\n\(result.transcript)")
        }
        let violations = Verifier.verify(data: data,
                                         expecting: scenario.expectations(forFile: file))
        XCTAssertEqual(violations, [],
                       violations.map(\.detail).joined(separator: "\n"))
    }

    // ── Many workers, ONE file ────────────────────────────────────────────────

    /// Builds a roster of `population` slot-writers plus the provisioning
    /// worker that pre-extends the file.
    ///
    /// The provisioning worker's count is the file's FULL final slot count.
    /// OS-9 cannot write into a hole: a slot worker seeking past the current
    /// end of file dies with E$EOF, and its whole range then reads back
    /// missing -- which looks exactly like RBF losing data under concurrent
    /// writers, and is not.
    private func sharedRoster(_ population: Int, file: String, nap: Int) -> [WorkerSpec] {
        var roster = [WorkerSpec(id: 99, role: .create, file: file,
                                 count: population * Self.records)]
        roster += (1...population).map {
            WorkerSpec(id: $0, role: .slot, file: file, count: Self.records, nap: nap)
        }
        return roster
    }

    /// Four workers holding four paths onto one file. Exercises the FD ring,
    /// the shared sector buffers, the segment list and the allocator at once.
    ///
    /// Cannot detect a missing record lock -- slot ranges are disjoint and
    /// never overlap. That is what the `rmw` pair below is for.
    func testFourWorkersShareOneFileOn6809() throws {
        let file = "\(Self.device)/shared.dat"
        let scenario = Scenario(name: "four-workers-shared-6809",
                                backend: .rbfImage,
                                workers: sharedRoster(4, file: file, nap: 1),
                                timeout: 300)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut,
                       "run never completed. Clone kept at \(result.scratchPath)\n"
                     + "guest transcript:\n\(result.transcript.suffix(3000))")
        guard let data = result.produced[file] else {
            return XCTFail("\(file) was never produced:\n\(result.transcript)")
        }
        let violations = Verifier.verify(data: data,
                                         expecting: scenario.expectations(forFile: file))
        XCTAssertEqual(violations, [],
                       violations.map(\.detail).joined(separator: "\n"))
    }

    // ── THE RECORD-LOCK TEST ──────────────────────────────────────────────────
    // Every worker read-modify-writes the SAME record, so the locked extents
    // OVERLAP -- the only way a missing record lock can be detected at all.
    //
    // NitrOS-9's RBF is a community-maintained clone. Whatever these report is
    // a statement about NitrOS-9, never about what OS-9 "should" do.

    /// Runs an rmw roster and returns the final tally the workers left behind.
    private func finalTally(workers population: Int, increments: Int,
                            nap: Int, role: WorkerSpec.Role,
                            napMode: NapMode = .sleep) throws -> Int {
        let file = "\(Self.device)/tally.dat"
        var roster = [WorkerSpec(id: 98, role: .seed, file: file, count: 1)]
        roster += (1...population).map {
            // The lock pair below uses `.nilWrites` with a LARGE burst -- see
            // the operating-point constants and the tests. An earlier reading
            // that `.nilWrites` "never interleaves" was measured with a nap of
            // ONE /nil write, which opens no window at all; a burst of a few
            // hundred writes spans several of NitrOS-9's 60Hz preemption ticks
            // and does interleave, with no process fork. `.sleep` is retained
            // as the caller's choice but forks a `sleep` per increment, which
            // is why it was too slow here. Whichever the caller picks, the
            // control (`rmwfree`) must lose updates or the locked result means
            // nothing.
            WorkerSpec(id: $0, role: role, file: file, count: increments,
                       nap: nap, napMode: napMode)
        }
        let scenario = Scenario(name: "rmw-6809-\(population)x\(increments)",
                                backend: .rbfImage, workers: roster, timeout: 600)
        let result = try Adapter6809(repoRoot: Self.repoRoot).run(scenario)

        XCTAssertFalse(result.timedOut, "rmw roster hung; clone \(result.scratchPath)")
        guard let data = result.produced[file],
              let text = String(bytes: data.prefix(9), encoding: .ascii),
              text.hasPrefix("T"), let tally = Int(text.dropFirst()) else {
            XCTFail("no readable tally. Transcript:\n\(result.transcript)")
            return -1
        }
        return tally
    }

    /// Env-driven bench: measure interleave/timing without editing code per run.
    ///
    /// Inert unless RBF_MEASURE is set. Knobs (all optional):
    ///   RBF_ROLE=rmw|rmwfree   RBF_NAP_MODE=sleep|nil   RBF_NAP_COUNT=<n>
    ///   RBF_WORKERS=<n>        RBF_INCREMENTS=<n>
    /// Prints "MEASURED tally=<t> expected=<e>" and never asserts, so a run
    /// always reports what happened rather than failing the process.
    func testMeasure6809() throws {
        let env = ProcessInfo.processInfo.environment
        guard env["RBF_MEASURE"] != nil else {
            throw XCTSkip("measurement harness; set RBF_MEASURE=1 to run")
        }
        let role: WorkerSpec.Role = env["RBF_ROLE"] == "rmw" ? .rmw : .rmwfree
        let napMode: NapMode = env["RBF_NAP_MODE"] == "nil" ? .nilWrites : .sleep
        let nap = Int(env["RBF_NAP_COUNT"] ?? "") ?? 1
        let workers = Int(env["RBF_WORKERS"] ?? "") ?? 4
        let increments = Int(env["RBF_INCREMENTS"] ?? "") ?? 10

        let started = Date()
        let tally = try finalTally(workers: workers, increments: increments,
                                   nap: nap, role: role, napMode: napMode)
        let elapsed = Date().timeIntervalSince(started)
        print("MEASURED role=\(role.rawValue) napMode=\(napMode.rawValue) nap=\(nap) "
            + "\(workers)x\(increments) tally=\(tally) expected=\(workers * increments) "
            + "elapsed=\(Int(elapsed))s")
    }

    /// CONTROL, and the one that must be read first: the identical race with NO
    /// lock taken (a READ path and a separate WRITE path, so RBF's update-mode
    /// auto-lock never engages).
    ///
    /// This must LOSE updates. If it does not, the workers never interleaved
    /// and the locked result below proves nothing whatsoever -- which is
    /// exactly how the old counter race passed 600/600 against code with no
    /// locking at all.
    func testUnlockedReadModifyWriteDoesLoseUpdatesOn6809() throws {
        try skipLockPairWhenHostBusy()
        let expected = Self.lockWorkers * Self.lockIncrements
        let tally = try finalTally(workers: Self.lockWorkers, increments: Self.lockIncrements,
                                   nap: Self.lockNap, role: .rmwfree, napMode: .nilWrites)
        XCTAssertLessThan(tally, expected,
                          "unlocked RMW kept a perfect tally of \(tally) -- the race never "
                        + "interleaved, so any locked result on this target is meaningless. "
                        + "If this starts passing, the .nilWrites window has stopped opening "
                        + "and every other lock result here must be treated as meaningless.")
    }

    /// The locked race: RBF auto-locks the record an update-mode read returns.
    /// A short tally is a lost update.
    ///
    /// Meaningful only because its control loses updates in the SAME
    /// configuration -- run `testUnlockedReadModifyWriteDoesLoseUpdatesOn6809`
    /// first. A green here on its own would say the workers never contended,
    /// not that the lock worked.
    func testConcurrentReadModifyWriteLosesNoUpdatesOn6809() throws {
        try skipLockPairWhenHostBusy()
        let expected = Self.lockWorkers * Self.lockIncrements
        let tally = try finalTally(workers: Self.lockWorkers, increments: Self.lockIncrements,
                                   nap: Self.lockNap, role: .rmw, napMode: .nilWrites)
        XCTAssertEqual(tally, expected,
                       "lost update on NitrOS-9: expected \(expected), got \(tally)")
    }

    // ── Backends that do not exist here ───────────────────────────────────────

    /// A host directory has no NitrOS-9 equivalent, and the adapter must say so
    /// rather than quietly running the scenario on `/DD`.
    ///
    /// This guards the silent-redirect failure mode directly: a scenario that
    /// ran somewhere other than where it claimed would report a pass for a code
    /// path never entered.
    func testHostDirectoryBackendIsRefusedNotRedirected() throws {
        XCTAssertThrowsError(try Backend6809.device(.hostDirectory)) { error in
            XCTAssertTrue("\(error)".contains("does not exist on 6809"),
                          "expected an explicit refusal, got: \(error)")
        }
    }

    /// The RAM disk is now VERIFIED and supported: `.ramDisk` resolves to `/r0`,
    /// the small fast device the destructive scenarios `format` and `dcheck`
    /// (see `DestructiveTests6809`). It used to be refused as unverified.
    func testRAMDiskBackendResolvesToR0() throws {
        XCTAssertEqual(try Backend6809.device(.ramDisk), "/r0")
    }
}
