//
//  main.swift
//  RBFHammer
//
//  The soak/gate CLI. Runs the hammer scenarios in a parallel pool -- once as a
//  fast gate, or for many iterations as a soak -- and verifies each run's file
//  content AND the device's structural health (dcheck/free). Exits non-zero if
//  any run comes back wrong, so it drops straight into a Makefile or CI.
//
//      swift run RBFHammer --target 68k --gate
//      swift run RBFHammer --target 68k --iterations 50 --jobs 4
//      swift run RBFHammer --target 6809 --iterations 5 --jobs 2
//
//  A soak exists to catch what a single run hides: an intermittent lost update,
//  a structural fault that only appears under contention or host load. Running
//  the contended scenarios over and over, several at once, is how those surface.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation
import RBFHammerCore

// ── Arguments ──────────────────────────────────────────────────────────────

/// Which emulator the soak drives.
enum Target: String { case os968k = "68k", os96809 = "6809" }

/// Parsed command line.
struct Options {
    var target: Target = .os968k
    var iterations = 1
    var jobs = 2
    var records = 8
    var chaos = false
    var minutes = 270          // ~4.5 hours
    var golden: String?
    var seed: UInt64 = UInt64(Date().timeIntervalSince1970)
}

func parseOptions(_ argv: [String]) -> Options {
    var options = Options()
    var i = 0
    func next() -> String? { i + 1 < argv.count ? argv[i + 1] : nil }
    while i < argv.count {
        switch argv[i] {
        case "--target":     if let v = next(), let t = Target(rawValue: v) { options.target = t }; i += 1
        case "--iterations": if let v = next(), let n = Int(v) { options.iterations = max(1, n) }; i += 1
        case "--jobs":       if let v = next(), let n = Int(v) { options.jobs = max(1, n) }; i += 1
        case "--records":    if let v = next(), let n = Int(v) { options.records = max(1, n) }; i += 1
        case "--gate":       options.iterations = 1
        case "--chaos":      options.chaos = true
        case "--minutes":    if let v = next(), let n = Int(v) { options.minutes = max(1, n) }; i += 1
        case "--golden":     options.golden = next(); i += 1
        case "--seed":       if let v = next(), let n = UInt64(v) { options.seed = n }; i += 1
        default: break
        }
        i += 1
    }
    return options
}

// ── Scenario library ───────────────────────────────────────────────────────
// The contended scenarios, the ones worth repeating: many workers sharing one
// file, and separate-file rosters, on every backend the target has. These
// verify generically (complete content + structural health), so the soak needs
// no per-scenario oracle -- unlike the lock and destructive tests, which assert
// bespoke conditions and live in the test targets.

func sharedRoster(_ population: Int, file: String, records: Int) -> [WorkerSpec] {
    var roster = [WorkerSpec(id: 99, role: .create, file: file, count: population * records)]
    roster += (1...population).map {
        WorkerSpec(id: $0, role: .slot, file: file, count: records, nap: 1)
    }
    return roster
}

func separateRoster(_ population: Int, records: Int, dir: String) -> [WorkerSpec] {
    (1...population).map {
        WorkerSpec(id: $0, role: .append, file: "\(dir)/w\($0).dat", count: records)
    }
}

func scenarios(for target: Target, records: Int) -> [Scenario] {
    switch target {
    case .os968k:
        let img = "/h9", ram = "/ram9"
        return [
            Scenario(name: "shared-4-rbf", backend: .rbfImage,
                     workers: sharedRoster(4, file: "\(img)/shared.dat", records: records)),
            Scenario(name: "shared-12-rbf", backend: .rbfImage,
                     workers: sharedRoster(12, file: "\(img)/shared.dat", records: records)),
            Scenario(name: "separate-4-rbf", backend: .rbfImage,
                     workers: separateRoster(4, records: records, dir: img)),
            Scenario(name: "shared-4-ram", backend: .ramDisk,
                     workers: sharedRoster(4, file: "\(ram)/shared.dat", records: records)),
        ]
    case .os96809:
        // Each 6809 run boots a real CoCo3 (~12s), so the soak set is small and
        // the point is repetition under load, not breadth. On the RAM disk
        // (`/r0`), where `dcheck` is instant and runs -- unlike `/DD`, so the
        // structural verdict is real here.
        return [
            Scenario(name: "shared-4-6809-ram", backend: .ramDisk,
                     workers: sharedRoster(4, file: "/r0/shared.dat", records: records),
                     timeout: 300),
        ]
    }
}

// ── Verification ───────────────────────────────────────────────────────────

/// Every way a single run can be judged wrong, as plain strings for the report.
///
/// - Parameter collectsContent: whether the produced files can be read back
///   host-side. The 6809 RAM disk lives in guest RAM and cannot be extracted, so
///   there its verdict is worker-completion plus the in-guest `dcheck`, not a
///   byte-for-byte content check.
func faults(_ scenario: Scenario, _ result: RunResult, collectsContent: Bool) -> [String] {
    var faults: [String] = []
    if result.timedOut { faults.append("timed out (a parked worker never woke)") }
    if result.transcript.contains("FAIL") { faults.append("a worker reported FAIL") }
    if result.transcript.contains("ERROR err") {
        faults.append("a worker hit an uncaught error (ON ERROR fired)")
    }

    if collectsContent {
        for file in scenario.files {
            let expectations = scenario.expectations(forFile: file)
            guard let data = result.produced[file] else {
                if expectations.contains(where: { $0.count > 0 }) {
                    faults.append("\(file) not produced")
                }
                continue
            }
            for violation in Verifier.verify(data: data, expecting: expectations) {
                faults.append("\(file): \(violation.kind.rawValue) -- \(violation.detail)")
            }
        }
    } else {
        // Content is not extractable: confirm every writing worker announced it
        // finished, so a silently dropped racer is still caught.
        for worker in scenario.workers where worker.role == .slot || worker.role == .append {
            if !result.transcript.contains("worker \(worker.id) wrote") {
                faults.append("worker \(worker.id) never reported writing")
            }
        }
    }

    for violation in StructuralOracle.structuralViolations(dcheck: result.transcript) {
        faults.append("structure: \(violation.detail)")
    }
    return faults
}

// ── The pool ───────────────────────────────────────────────────────────────

/// Repo root, four levels up from this source file.
let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()   // RBFHammer/
    .deletingLastPathComponent()   // Sources/
    .deletingLastPathComponent()   // test/
    .deletingLastPathComponent()   // repo root

/// One unit of work: a scenario and which iteration it is.
struct Job: Sendable { let index: Int; let iteration: Int; let scenario: Scenario }

/// What a job produced.
struct Outcome: Sendable { let job: Job; let faults: [String]; let seconds: Double }

func makeAdapter(_ target: Target, golden: URL? = nil) throws -> Adapter {
    switch target {
    case .os968k:  return try Adapter68k(repoRoot: repoRoot)
    case .os96809: return try Adapter6809(repoRoot: repoRoot, goldenMaster: golden)
    }
}

/// Runs `jobs` with at most `concurrency` in flight at once, reporting each as
/// it finishes so a long soak shows progress rather than going dark.
func runPool(_ queue: [Job], target: Target, concurrency: Int) async -> [Outcome] {
    var outcomes: [Outcome] = []
    var next = 0
    await withTaskGroup(of: Outcome.self) { group in
        func addNext() {
            guard next < queue.count else { return }
            let job = queue[next]; next += 1
            group.addTask {
                let start = Date()
                let faultList: [String]
                // The 6809 RAM disk is not extractable host-side; everywhere else
                // the produced files come back and can be content-checked.
                let collectsContent = !(target == .os96809 && job.scenario.backend == .ramDisk)
                do {
                    let result = try makeAdapter(target).run(job.scenario)
                    faultList = faults(job.scenario, result, collectsContent: collectsContent)
                } catch {
                    faultList = ["adapter threw: \(error)"]
                }
                return Outcome(job: job, faults: faultList,
                               seconds: Date().timeIntervalSince(start))
            }
        }
        for _ in 0..<min(concurrency, queue.count) { addNext() }
        while let outcome = await group.next() {
            let tag = outcome.faults.isEmpty ? "ok  " : "FAIL"
            let name = outcome.job.scenario.name
            let line = "  [\(tag)] iter \(outcome.job.iteration) \(name) "
                     + "(\(String(format: "%.1f", outcome.seconds))s)\n"
            FileHandle.standardError.write(Data(line.utf8))
            outcomes.append(outcome)
            addNext()
        }
    }
    return outcomes
}

// ── Chaos mode ───────────────────────────────────────────────────────────────
// A long unattended soak that bombards RBF with VARIETY, not repetition: every
// run draws a fresh roster, backend, size and pacing from the full menu of role
// families. The point is to shake out an intermittent structural corruption or a
// hang that only a rare combination triggers. Reproducible from its `--seed`.

/// Seedable PRNG (SplitMix64) so a chaos run replays exactly from its seed.
struct SplitMix64: RandomNumberGenerator {
    private var state: UInt64
    init(seed: UInt64) { state = seed }
    mutating func next() -> UInt64 {
        state &+= 0x9E3779B97F4A7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58476D1CE4E5B9
        z = (z ^ (z >> 27)) &* 0x94D049BB133111EB
        return z ^ (z >> 31)
    }
}

/// The dcheck-capable device for a target -- where the structural oracle runs,
/// so a corruption is actually visible. (68k: the RBF image; 6809: the RAM disk,
/// since dcheck on `/DD` is far too slow.)
func chaosDevice(_ target: Target) -> (backend: Backend, path: String) {
    target == .os968k ? (.rbfImage, "/h9") : (.ramDisk, "/r0")
}

/// Builds one randomized-but-VALID scenario. Each template uses roles the way
/// they actually compose (provisioners first, matching seeds, sane counts), so
/// the chaos is in the parameters, never a malformed roster that would fault for
/// harness reasons rather than an RBF one.
func chaosScenario(_ rng: inout SplitMix64, target: Target, n: Int) -> Scenario {
    let is68k = target == .os968k
    let (backend, dev) = chaosDevice(target)
    // 6809 caps hard at ~4 concurrent racers: past that, `runb` packs modules
    // unreliably (Error #043) and the CoCo3 runs out of RAM (#237) when several
    // workers fork `SHELL sleep` at once. 68k has no such limit.
    let maxW = is68k ? 8 : 4
    let w = Int.random(in: 2...maxW, using: &rng)
    let r = Int.random(in: 5...40, using: &rng)
    let nap = [0, 0, 1, Int.random(in: 1...8, using: &rng)].randomElement(using: &rng)!
    let tmo: TimeInterval = is68k ? 90 : 400

    // The binary write-only / mixed / deadlock templates (3-5) are proven on
    // 6809; on 68k only the record-lock, slot and append families are exercised
    // so far, so keep 68k to those and let 6809 draw from the whole menu.
    switch Int.random(in: 0..<(is68k ? 3 : 6), using: &rng) {
    case 0:                                        // binary lost-update RMW
        let f = "\(dev)/lu.dat"
        var roster = [WorkerSpec(id: 99, role: .seedbin, file: f, count: 1)]
        roster += (1...w).map { WorkerSpec(id: $0, role: .rmwbin, file: f,
                                           count: r * 5, nap: 0, napMode: .nilWrites) }
        return Scenario(name: "c\(n)-lu-w\(w)r\(r*5)", backend: backend, workers: roster, timeout: tmo)
    case 1:                                        // many slot writers, one file
        let f = "\(dev)/sl.dat"
        var roster = [WorkerSpec(id: 99, role: .create, file: f, count: w * r)]
        roster += (1...w).map { WorkerSpec(id: $0, role: .slot, file: f, count: r, nap: nap) }
        return Scenario(name: "c\(n)-slot-w\(w)r\(r)", backend: backend, workers: roster, timeout: tmo)
    case 2:                                        // separate-file appenders
        let roster = (1...w).map { WorkerSpec(id: $0, role: .append,
                                              file: "\(dev)/wa\($0).dat", count: r, nap: nap) }
        return Scenario(name: "c\(n)-append-w\(w)r\(r)", backend: backend, workers: roster, timeout: tmo)
    case 3:                                        // write-only producer + follower
        let f = "\(dev)/wo.dat"
        let roster = [
            WorkerSpec(id: 1, role: .writeonly, file: f, count: max(4, r), nap: 40, napMode: .sleep),
            WorkerSpec(id: 2, role: .follow, file: f, count: 1, nap: 15, napMode: .sleep),
        ]
        return Scenario(name: "c\(n)-follow-r\(r)", backend: backend, workers: roster, timeout: tmo)
    case 4:                                        // mixed write-only + update RMW
        // The producer counts as a racer, so cap the RMW workers to keep the
        // total within the 6809's ~4-racer ceiling.
        let mw = min(w, is68k ? w : 3)
        let f = "\(dev)/mix.dat"
        var roster = [WorkerSpec(id: 1, role: .wobin, file: f, count: 8, nap: 40, napMode: .sleep)]
        roster += (2...(mw + 1)).map { WorkerSpec(id: $0, role: .rmwmix, file: f,
                                                  count: r * 5, nap: 30, napMode: .sleep) }
        return Scenario(name: "c\(n)-mixed-w\(mw)", backend: backend, workers: roster, timeout: tmo)
    default:                                       // crossed-hold deadlock
        let f = "\(dev)/dl.dat"
        let roster = [
            WorkerSpec(id: 98, role: .seedbin2, file: f, count: 1),
            WorkerSpec(id: 1, role: .cross, file: f, count: 1, nap: 100, napMode: .sleep),
            WorkerSpec(id: 2, role: .cross, file: f, count: 1, nap: 100, napMode: .sleep),
        ]
        return Scenario(name: "c\(n)-deadlock", backend: backend, workers: roster, timeout: tmo)
    }
}

/// Chaos verdict: only the target-independent signs of an RBF DEFECT, since a
/// random roster has no single content oracle. Structural damage (`dcheck`) is
/// the corruption signal; a timeout is a parked-forever lock; a worker `FAIL` or
/// an uncaught `ERROR err` is an unexpected fault (the deadlock's own handled
/// "cross error 254" is neither, so it is not flagged).
func chaosFaults(_ result: RunResult) -> [String] {
    var faults: [String] = []
    if result.timedOut { faults.append("HANG -- timed out, a worker never woke") }
    if result.transcript.contains("FAIL") { faults.append("a worker reported FAIL") }
    if result.transcript.contains("ERROR err") { faults.append("a worker hit an uncaught error") }
    for violation in StructuralOracle.structuralViolations(dcheck: result.transcript) {
        faults.append("STRUCTURE -- \(violation.detail)")
    }
    return faults
}

/// Generates and runs chaos scenarios until the wall-clock deadline, `jobs` at a
/// time, logging every run and keeping a record of each failure with its seed +
/// scenario name so any hit is reproducible (`--seed <s>` replays the sequence).
func runChaos(target: Target, minutes: Int, jobs: Int, golden: URL?,
              seed: UInt64) async -> (runs: Int, failures: [(name: String, faults: [String])]) {
    let deadline = Date().addingTimeInterval(Double(minutes) * 60)
    var rng = SplitMix64(seed: seed)
    var made = 0, runs = 0
    var failures: [(String, [String])] = []
    await withTaskGroup(of: (String, [String], Double).self) { group in
        func addNext() {
            guard Date() < deadline else { return }
            made += 1
            let scenario = chaosScenario(&rng, target: target, n: made)
            group.addTask {
                let start = Date()
                var faultList: [String]
                do {
                    let result = try makeAdapter(target, golden: golden).run(scenario)
                    faultList = chaosFaults(result)
                } catch { faultList = ["adapter threw: \(error)"] }
                return (scenario.name, faultList, Date().timeIntervalSince(start))
            }
        }
        for _ in 0..<jobs { addNext() }
        while let outcome = await group.next() {
            let (name, faults, secs) = outcome
            runs += 1
            let tag = faults.isEmpty ? "ok  " : "FAIL"
            let remaining = Int(deadline.timeIntervalSinceNow / 60)
            var line = "  [\(tag)] \(name) (\(String(format: "%.1f", secs))s) "
                     + "[run \(runs), ~\(max(0, remaining))m left]\n"
            if !faults.isEmpty {
                failures.append((name, faults))
                line += faults.map { "        ! \($0)\n" }.joined()
            }
            FileHandle.standardError.write(Data(line.utf8))
            addNext()
        }
    }
    return (runs, failures)
}

// ── Main ───────────────────────────────────────────────────────────────────

let options = parseOptions(Array(CommandLine.arguments.dropFirst()))

if options.chaos {
    let golden = options.golden.map { URL(fileURLWithPath: $0) }
    print("RBFHammer CHAOS: target \(options.target.rawValue), \(options.minutes)m, "
        + "\(options.jobs) at a time, seed \(options.seed)"
        + (golden.map { ", image \($0.lastPathComponent)" } ?? ""))
    let started = Date()
    let (runs, failures) = await runChaos(target: options.target, minutes: options.minutes,
                                          jobs: options.jobs, golden: golden, seed: options.seed)
    let mins = Int(Date().timeIntervalSince(started) / 60)
    print("\nCHAOS done: \(runs) runs in \(mins)m, seed \(options.seed) -- "
        + "\(runs - failures.count) clean, \(failures.count) FAILED")
    if !failures.isEmpty {
        print("\nFAILURES (replay the run with --seed \(options.seed)):")
        for (name, faults) in failures {
            print("  \(name):")
            for fault in faults { print("    - \(fault)") }
        }
        exit(1)
    }
    exit(0)
}

let set = scenarios(for: options.target, records: options.records)

var queue: [Job] = []
for iteration in 1...options.iterations {
    for (index, scenario) in set.enumerated() {
        queue.append(Job(index: index, iteration: iteration, scenario: scenario))
    }
}

let mode = options.iterations == 1 ? "gate" : "soak"
print("RBFHammer \(mode): target \(options.target.rawValue), \(set.count) scenarios "
    + "x \(options.iterations) iterations = \(queue.count) runs, \(options.jobs) at a time")

let started = Date()
let outcomes = await runPool(queue, target: options.target, concurrency: options.jobs)
let elapsed = Date().timeIntervalSince(started)

let failures = outcomes.filter { !$0.faults.isEmpty }
print("\n\(queue.count) runs in \(String(format: "%.1f", elapsed))s: "
    + "\(queue.count - failures.count) passed, \(failures.count) failed")

if !failures.isEmpty {
    print("\nFAILURES:")
    for failure in failures.sorted(by: { $0.job.iteration < $1.job.iteration }) {
        print("  iter \(failure.job.iteration) \(failure.job.scenario.name):")
        for fault in failure.faults { print("    - \(fault)") }
    }
    exit(1)
}
