//
//  main.swift
//  RBFHammer
//
//  The soak/gate CLI. Runs the hammer scenarios in a parallel pool -- once as a
//  fast gate, or for many iterations as a soak -- and verifies each run's file
//  content AND the device's structural health (dcheck/free). Exits non-zero if
//  any run comes back wrong, so it drops straight into a Makefile or CI.
//
//      swift run RBFHammer --target 68k --gate
//      swift run RBFHammer --target 68k --iterations 50 --jobs 4
//      swift run RBFHammer --target 6809 --iterations 5 --jobs 2
//
//  A soak exists to catch what a single run hides: an intermittent lost update,
//  a structural fault that only appears under contention or host load. Running
//  the contended scenarios over and over, several at once, is how those surface.
//
//  Generated by Claude Opus 4.8 (Anthropic) — collaborator: rdoggett
//  date: 07-21-2026
//

import Foundation
import RBFHammerCore

// ── Arguments ──────────────────────────────────────────────────────────────

/// Which emulator the soak drives.
enum Target: String { case os968k = "68k", os96809 = "6809" }

/// Parsed command line.
struct Options {
    var target: Target = .os968k
    var iterations = 1
    var jobs = 2
    var records = 8
}

func parseOptions(_ argv: [String]) -> Options {
    var options = Options()
    var i = 0
    func next() -> String? { i + 1 < argv.count ? argv[i + 1] : nil }
    while i < argv.count {
        switch argv[i] {
        case "--target":     if let v = next(), let t = Target(rawValue: v) { options.target = t }; i += 1
        case "--iterations": if let v = next(), let n = Int(v) { options.iterations = max(1, n) }; i += 1
        case "--jobs":       if let v = next(), let n = Int(v) { options.jobs = max(1, n) }; i += 1
        case "--records":    if let v = next(), let n = Int(v) { options.records = max(1, n) }; i += 1
        case "--gate":       options.iterations = 1
        default: break
        }
        i += 1
    }
    return options
}

// ── Scenario library ───────────────────────────────────────────────────────
// The contended scenarios, the ones worth repeating: many workers sharing one
// file, and separate-file rosters, on every backend the target has. These
// verify generically (complete content + structural health), so the soak needs
// no per-scenario oracle -- unlike the lock and destructive tests, which assert
// bespoke conditions and live in the test targets.

func sharedRoster(_ population: Int, file: String, records: Int) -> [WorkerSpec] {
    var roster = [WorkerSpec(id: 99, role: .create, file: file, count: population * records)]
    roster += (1...population).map {
        WorkerSpec(id: $0, role: .slot, file: file, count: records, nap: 1)
    }
    return roster
}

func separateRoster(_ population: Int, records: Int, dir: String) -> [WorkerSpec] {
    (1...population).map {
        WorkerSpec(id: $0, role: .append, file: "\(dir)/w\($0).dat", count: records)
    }
}

func scenarios(for target: Target, records: Int) -> [Scenario] {
    switch target {
    case .os968k:
        let img = "/h9", ram = "/ram9"
        return [
            Scenario(name: "shared-4-rbf", backend: .rbfImage,
                     workers: sharedRoster(4, file: "\(img)/shared.dat", records: records)),
            Scenario(name: "shared-12-rbf", backend: .rbfImage,
                     workers: sharedRoster(12, file: "\(img)/shared.dat", records: records)),
            Scenario(name: "separate-4-rbf", backend: .rbfImage,
                     workers: separateRoster(4, records: records, dir: img)),
            Scenario(name: "shared-4-ram", backend: .ramDisk,
                     workers: sharedRoster(4, file: "\(ram)/shared.dat", records: records)),
        ]
    case .os96809:
        // Each 6809 run boots a real CoCo3 (~12s), so the soak set is small and
        // the point is repetition under load, not breadth. On the RAM disk
        // (`/r0`), where `dcheck` is instant and runs -- unlike `/DD`, so the
        // structural verdict is real here.
        return [
            Scenario(name: "shared-4-6809-ram", backend: .ramDisk,
                     workers: sharedRoster(4, file: "/r0/shared.dat", records: records),
                     timeout: 300),
        ]
    }
}

// ── Verification ───────────────────────────────────────────────────────────

/// Every way a single run can be judged wrong, as plain strings for the report.
///
/// - Parameter collectsContent: whether the produced files can be read back
///   host-side. The 6809 RAM disk lives in guest RAM and cannot be extracted, so
///   there its verdict is worker-completion plus the in-guest `dcheck`, not a
///   byte-for-byte content check.
func faults(_ scenario: Scenario, _ result: RunResult, collectsContent: Bool) -> [String] {
    var faults: [String] = []
    if result.timedOut { faults.append("timed out (a parked worker never woke)") }
    if result.transcript.contains("FAIL") { faults.append("a worker reported FAIL") }
    if result.transcript.contains("ERROR err") {
        faults.append("a worker hit an uncaught error (ON ERROR fired)")
    }

    if collectsContent {
        for file in scenario.files {
            let expectations = scenario.expectations(forFile: file)
            guard let data = result.produced[file] else {
                if expectations.contains(where: { $0.count > 0 }) {
                    faults.append("\(file) not produced")
                }
                continue
            }
            for violation in Verifier.verify(data: data, expecting: expectations) {
                faults.append("\(file): \(violation.kind.rawValue) -- \(violation.detail)")
            }
        }
    } else {
        // Content is not extractable: confirm every writing worker announced it
        // finished, so a silently dropped racer is still caught.
        for worker in scenario.workers where worker.role == .slot || worker.role == .append {
            if !result.transcript.contains("worker \(worker.id) wrote") {
                faults.append("worker \(worker.id) never reported writing")
            }
        }
    }

    for violation in StructuralOracle.structuralViolations(dcheck: result.transcript) {
        faults.append("structure: \(violation.detail)")
    }
    return faults
}

// ── The pool ───────────────────────────────────────────────────────────────

/// Repo root, four levels up from this source file.
let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()   // RBFHammer/
    .deletingLastPathComponent()   // Sources/
    .deletingLastPathComponent()   // test/
    .deletingLastPathComponent()   // repo root

/// One unit of work: a scenario and which iteration it is.
struct Job: Sendable { let index: Int; let iteration: Int; let scenario: Scenario }

/// What a job produced.
struct Outcome: Sendable { let job: Job; let faults: [String]; let seconds: Double }

func makeAdapter(_ target: Target) throws -> Adapter {
    switch target {
    case .os968k:  return try Adapter68k(repoRoot: repoRoot)
    case .os96809: return try Adapter6809(repoRoot: repoRoot)
    }
}

/// Runs `jobs` with at most `concurrency` in flight at once, reporting each as
/// it finishes so a long soak shows progress rather than going dark.
func runPool(_ queue: [Job], target: Target, concurrency: Int) async -> [Outcome] {
    var outcomes: [Outcome] = []
    var next = 0
    await withTaskGroup(of: Outcome.self) { group in
        func addNext() {
            guard next < queue.count else { return }
            let job = queue[next]; next += 1
            group.addTask {
                let start = Date()
                let faultList: [String]
                // The 6809 RAM disk is not extractable host-side; everywhere else
                // the produced files come back and can be content-checked.
                let collectsContent = !(target == .os96809 && job.scenario.backend == .ramDisk)
                do {
                    let result = try makeAdapter(target).run(job.scenario)
                    faultList = faults(job.scenario, result, collectsContent: collectsContent)
                } catch {
                    faultList = ["adapter threw: \(error)"]
                }
                return Outcome(job: job, faults: faultList,
                               seconds: Date().timeIntervalSince(start))
            }
        }
        for _ in 0..<min(concurrency, queue.count) { addNext() }
        while let outcome = await group.next() {
            let tag = outcome.faults.isEmpty ? "ok  " : "FAIL"
            let name = outcome.job.scenario.name
            let line = "  [\(tag)] iter \(outcome.job.iteration) \(name) "
                     + "(\(String(format: "%.1f", outcome.seconds))s)\n"
            FileHandle.standardError.write(Data(line.utf8))
            outcomes.append(outcome)
            addNext()
        }
    }
    return outcomes
}

// ── Main ───────────────────────────────────────────────────────────────────

let options = parseOptions(Array(CommandLine.arguments.dropFirst()))
let set = scenarios(for: options.target, records: options.records)

var queue: [Job] = []
for iteration in 1...options.iterations {
    for (index, scenario) in set.enumerated() {
        queue.append(Job(index: index, iteration: iteration, scenario: scenario))
    }
}

let mode = options.iterations == 1 ? "gate" : "soak"
print("RBFHammer \(mode): target \(options.target.rawValue), \(set.count) scenarios "
    + "x \(options.iterations) iterations = \(queue.count) runs, \(options.jobs) at a time")

let started = Date()
let outcomes = await runPool(queue, target: options.target, concurrency: options.jobs)
let elapsed = Date().timeIntervalSince(started)

let failures = outcomes.filter { !$0.faults.isEmpty }
print("\n\(queue.count) runs in \(String(format: "%.1f", elapsed))s: "
    + "\(queue.count - failures.count) passed, \(failures.count) failed")

if !failures.isEmpty {
    print("\nFAILURES:")
    for failure in failures.sorted(by: { $0.job.iteration < $1.job.iteration }) {
        print("  iter \(failure.job.iteration) \(failure.job.scenario.name):")
        for fault in failure.faults { print("    - \(fault)") }
    }
    exit(1)
}
