//
//  main.swift
//  OS9Tests
//
//  Integration test runner for os9exec. Sends commands to the OS-9 shell
//  and checks stdout for expected content.
//
//  Run: swift run --package-path test  (from repo root)
//  Or:  make test
//
//  Generated by Claude Sonnet 4.6 (Anthropic) — collaborator: rdoggett
//  date: 06-24-2026
//

import Foundation

// ── Configuration ─────────────────────────────────────────────────────────────

let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()   // OS9Tests/
    .deletingLastPathComponent()   // Sources/
    .deletingLastPathComponent()   // test/
    .deletingLastPathComponent()   // repo root

let execURL  = repoRoot.appendingPathComponent("os9exec")
let diskPath = repoRoot.appendingPathComponent("dd").path

// ── Shell runner ──────────────────────────────────────────────────────────────

/// Run one or more OS-9 shell commands and return combined stdout.
/// ESC on a final line signals EOF to the shell.
/// Times out after `timeout` seconds to prevent hangs from blocking the suite.
func os9(_ commands: [String], timeout: TimeInterval = 15) -> String {
    let input = commands.joined(separator: "\n") + "\n\u{1B}\n"

    let process = Process()
    process.executableURL = execURL
    process.arguments    = ["/dd/CMDS/shell"]
    process.environment  = ["OS9DISK": diskPath]

    let stdinPipe  = Pipe()
    let stdoutPipe = Pipe()
    process.standardInput  = stdinPipe
    process.standardOutput = stdoutPipe
    // Discard stderr — os9exec writes verbose debug there; leaving it as an
    // unread Pipe would fill the buffer and deadlock the process.
    process.standardError  = FileHandle(forWritingAtPath: "/dev/null")
                             ?? FileHandle.standardError

    guard (try? process.run()) != nil else { return "" }
    stdinPipe.fileHandleForWriting.write(Data(input.utf8))
    stdinPipe.fileHandleForWriting.closeFile()

    let sem = DispatchSemaphore(value: 0)
    var output = ""
    DispatchQueue.global().async {
        output = String(
            decoding: stdoutPipe.fileHandleForReading.readDataToEndOfFile(),
            as: UTF8.self
        )
        sem.signal()
    }

    if sem.wait(timeout: .now() + timeout) == .timedOut {
        process.terminate()
        return "(timeout)"
    }
    process.waitUntilExit()
    return output
}

// ── Test runner ───────────────────────────────────────────────────────────────

var passed = 0
var failed = 0
let filter = CommandLine.arguments.dropFirst().first ?? ""

func run(_ name: String, expectation: String, commands: [String], check: (String) -> Bool) {
    guard filter.isEmpty || name.localizedCaseInsensitiveContains(filter) else { return }
    let output = os9(commands)
    if check(output) {
        print("PASS: \(name)")
        passed += 1
    } else {
        print("FAIL: \(name)")
        print("      [\(expectation)]")
        let preview = output
            .split(separator: "\n")
            .filter { !$0.hasPrefix("#") && $0 != "$" && !$0.isEmpty }
            .prefix(4)
            .joined(separator: " | ")
        print("      output: \(preview)")
        failed += 1
    }
}

func check(_ name: String, contains pattern: String, _ commands: String...) {
    run(name, expectation: "contains: \(pattern)", commands: commands) { $0.contains(pattern) }
}

func check(_ name: String, absent pattern: String, _ commands: String...) {
    run(name, expectation: "absent: \(pattern)", commands: commands) { !$0.contains(pattern) }
}

func noError(_ name: String, _ commands: String...) {
    // Match "Error #" — the OS-9 error format — not the startup ioctl message
    run(name, expectation: "no OS-9 error", commands: commands) {
        !$0.contains("Error #")
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

print("=== OS9exec integration tests ===\n")

// echo
check("echo: basic",           contains: "hello world",  "echo hello world")
check("echo: single word",     contains: "hello",        "echo hello")

// pipe (!)
check("pipe: echo ! dump",     contains: "6162 630d",    "echo abc ! dump")
check("pipe: echo ! count",    contains: "1",            "echo hello ! count")
check("pipe: echo ! tr",       contains: "HELLO",        "echo hello ! tr a-z A-Z")

// named pipes (/pipe)
check("namedpipe: write+read", contains: "6162 630d",
    "echo abc >/pipe/t1", "dump </pipe/t1")

// directory ops
check("dir: lists known file",   contains: "shell",    "dir /dd/CMDS")
check("dir: root lists CMDS",    contains: "CMDS",     "dir /dd")
check("pd: shows current dir",   contains: "/dd",      "pd")
// dir listing uses fixed-width columns: "testdir " (trailing space) appears only in the listing,
// not in the command echo ("makdir /dd/testdir" has no trailing space after "testdir")
check("makdir: creates dir",     contains: "testdir ",
    "makdir /dd/testdir", "dir /dd")
check("deldir: removes dir",     absent:   "testdir ",
    "deldir -q /dd/testdir", "dir /dd")

// file ops
check("copy: creates file",      contains: "t_echo",
    "copy /dd/CMDS/echo /dd/t_echo", "dir /dd")
check("rename: new name present", contains: "t_echo2",
    "rename /dd/t_echo t_echo2", "dir /dd")
check("rename: old name gone",   absent:   "t_echo ",  "dir /dd")
noError("attr: shows attrs",     "attr /dd/t_echo2")
check("ident: identifies mod",   contains: "echo",     "ident /dd/t_echo2")
noError("del: file cleanup",     "del /dd/t_echo2")

// text commands (/dd/startup is a known text file on the disk)
check("list: shows content",     contains: "OS-9",     "list /dd/startup")
check("count: line count",       contains: "17",       "count /dd/startup")
check("grep: finds pattern",     contains: "shell",    "grep shell /dd/startup")
check("grep: no match silent",   absent:   "shell",    "grep ZZZNOTFOUND /dd/startup")
check("merge: combines files",   contains: "OS-9",
    "merge /dd/startup /dd/startup")

// dump
check("dump: shows hex",         contains: "4afc",     "dump /dd/CMDS/echo")

// touch
check("touch: creates file",     contains: "t_touch",
    "touch /dd/t_touch", "dir /dd")
noError("del: touch cleanup",    "del /dd/t_touch")

// cmp
noError("cmp: identical files",
    "copy /dd/CMDS/echo /dd/t_cmp1",
    "copy /dd/CMDS/echo /dd/t_cmp2",
    "cmp /dd/t_cmp1 /dd/t_cmp2",
    "del /dd/t_cmp1", "del /dd/t_cmp2")

// tee
check("tee: copies to file",     contains: "teetest",
    "echo teetest ! tee /dd/t_tee", "list /dd/t_tee")
noError("del: tee cleanup",      "del /dd/t_tee")

// compress / expand
check("compress+expand: roundtrip", contains: "OS-9",
    "copy /dd/startup /dd/t_comp",
    "compress /dd/t_comp",
    "expand /dd/t_comp",
    "list /dd/t_comp")
noError("del: compress cleanup", "del /dd/t_comp")

// qsort — use two single-line files merged into qsort (>> is stderr redirect in OS-9, not append)
check("qsort: sorts lines",      contains: "apple",
    "echo banana >/dd/t_qs1",
    "echo apple >/dd/t_qs2",
    "merge /dd/t_qs1 /dd/t_qs2 ! qsort",
    "del /dd/t_qs1", "del /dd/t_qs2")

// pr
check("pr: formats output",      contains: "OS-9",    "pr /dd/startup")

// system info
noError("date: runs",            "date")
noError("mdir: runs",            "mdir")
check("mdir: shell listed",      contains: "shell",   "mdir")
noError("procs: runs",           "procs")
noError("devs: runs",            "devs")
noError("printenv: runs",        "printenv")

// module ops
noError("load+unlink: echo",
    "load /dd/CMDS/echo", "unlink echo")

// sleep
noError("sleep: zero seconds",   "sleep 0")

// system info — extended
check("events: lists events",    contains: "OS-9",    "events")
check("mfree: shows memory",     contains: "K",       "mfree")
check("tmode: shows settings",   contains: "baud",    "tmode")

// file tools
check("hasher: produces hash",   contains: "/dd/startup",  "hasher /dd/startup")
check("finder: finds file",      contains: "startup", "finder /dd -n=startup")

// binary exchange roundtrip
check("binex+exbin: roundtrip",  contains: "Good CRC",
    "binex /dd/CMDS/echo /dd/t_echo.x",
    "exbin /dd/t_echo.x /dd/t_echo2",
    "ident /dd/t_echo2",
    "del /dd/t_echo.x", "del /dd/t_echo2")

// build a shell script from a file (stdin redirect avoids interactive stdin conflict)
check("build: creates script file", contains: "t_bscript",
    "echo echo built >/dd/t_bld_in",
    "build /dd/t_bscript </dd/t_bld_in",
    "dir /dd ! grep t_bscript",
    "del /dd/t_bscript", "del /dd/t_bld_in")

// module save/restore
check("save: writes module file", contains: "echo",
    "load /dd/CMDS/echo",
    "save echo",
    "dir /dd/CMDS ! grep echo",
    "del /dd/echo",
    "unlink echo")

// commands requiring args (usage / graceful failure)
check("tsmon: shows usage",      contains: "tsmon",       "tsmon")
check("os9gen: no device",       contains: "os9gen",      "os9gen")
noError("cfp: shows help",       "cfp")

// attr: show file attribute string
check("attr: module attrs",      contains: "--e-r",       "attr -re /dd/CMDS/echo")
check("attr: data file attrs",   contains: "rewr",        "attr -re /dd/startup")

// help: specific command help
check("help dir: options listed", contains: "recursive",  "help dir")

// merge: line count confirms newlines preserved
check("merge: two files two lines", contains: "2 lines",
    "echo x >/dd/t_mg1", "echo y >/dd/t_mg2",
    "merge /dd/t_mg1 /dd/t_mg2 ! count",
    "del /dd/t_mg1", "del /dd/t_mg2")

// disk save generates a restore script
check("dsave: generates script", contains: "copy",        "dsave /dd")

// module integrity checker
check("fixmod: good CRC",        contains: "CRC matches", "fixmod /dd/CMDS/echo")

// inline help system
check("help: shows function",    contains: "Function",    "help")


// concurrent execution (&)
// Both background and foreground echo must produce output — tests the scheduler
check("concurrent: fg runs",          contains: "fg_out",  "echo bg_out & echo fg_out")
check("concurrent: bg runs",          contains: "bg_out",  "echo bg_out & echo fg_out")
noError("concurrent: no crash",                            "sleep 0 & echo done")

// chd: directory change persists for subsequent commands
check("chd: changes working dir",     contains: "/dd/CMDS",
    "chd /dd/CMDS", "pd", "chd /dd")

// stderr redirect (>> in OS-9 is stderr, not append)
check("stderr: redirect to file",     contains: "Error",
    "list /dd/no_such_file_xyz >> /dd/t_stderr",
    "list /dd/t_stderr",
    "del /dd/t_stderr")

// paths: list open paths
noError("paths: runs",                "paths")

// what: scan module for embedded strings
noError("what: runs on module",       "what /dd/CMDS/echo")

// ── Results ───────────────────────────────────────────────────────────────────

print("\nResults: \(passed) passed, \(failed) failed")
exit(failed > 0 ? 1 : 0)
