//
//  main.swift
//  OS9Tests
//
//  Integration test runner for os9exec. Sends commands to the OS-9 shell
//  and checks stdout for expected content.
//
//  Setup (once):
//    cd test && ln -s ../os9/dd dd       (create symlink to your OS-9 disk in test/)
//
//  Run (local):
//    swift run --package-path test
//    make test
//
//  Run (Docker):
//    DOCKER_IMAGE=ghcr.io/peacedudes/os9exec:latest swift run --package-path test
//    DOCKER_IMAGE=os9exec:linux32 swift run --package-path test
//
//  Run (Apple Container):
//    CONTAINER_IMAGE=os9exec:apple swift run --package-path test
//
//  Generated by Claude Sonnet 4.6 (Anthropic) — collaborator: rdoggett
//  date: 06-29-2026
//

import Foundation

// ── Configuration ─────────────────────────────────────────────────────────────

let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()   // OS9Tests/
    .deletingLastPathComponent()   // Sources/
    .deletingLastPathComponent()   // test/
    .deletingLastPathComponent()   // repo root

let testDir  = repoRoot.appendingPathComponent("test")
let execURL  = repoRoot.appendingPathComponent("os9exec")
let diskPath = testDir.appendingPathComponent("dd").path

// Optional container image for testing
// Docker: DOCKER_IMAGE=os9exec:latest swift run
// Apple Container: CONTAINER_IMAGE=os9exec:apple swift run
let dockerImage = ProcessInfo.processInfo.environment["DOCKER_IMAGE"]
let containerImage = ProcessInfo.processInfo.environment["CONTAINER_IMAGE"]

// ── Shell runner ──────────────────────────────────────────────────────────────

/// Run one or more OS-9 shell commands and return combined stdout.
/// ESC on a final line signals EOF to the shell.
/// Times out after `timeout` seconds to prevent hangs from blocking the suite.
/// If DOCKER_IMAGE is set, runs via Docker; otherwise runs locally (assumes dd symlink exists).
func os9(_ commands: [String], timeout: TimeInterval = 15) -> String {
    let input = commands.joined(separator: "\n") + "\n\u{1B}\n"

    let process = Process()

    if let image = dockerImage {
        // Run via Docker: mount local dd directory and pipe stdin/stdout
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = [
            "docker",
            "run",
            "--rm",
            "-i",
            "-v", diskPath + ":/dd",
            image,
            "shell"
        ]
    } else if let image = containerImage {
        // Run via Apple Container: mount local dd directory and pipe stdin/stdout
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = [
            "container",
            "run",
            "--rm",
            "-i",
            "-v", diskPath + ":/dd",
            image,
            "shell"
        ]
    } else {
        // Run locally: use existing symlink at dd/
        process.executableURL = execURL
        process.arguments    = ["shell"]
        process.environment  = ["OS9DISK": diskPath]
    }

    let stdinPipe  = Pipe()
    let stdoutPipe = Pipe()
    let stderrPipe = Pipe()  // Capture stderr too for debugging
    process.standardInput  = stdinPipe
    process.standardOutput = stdoutPipe
    process.standardError  = stderrPipe

    guard (try? process.run()) != nil else { return "" }
    stdinPipe.fileHandleForWriting.write(Data(input.utf8))
    stdinPipe.fileHandleForWriting.closeFile()

    let sem = DispatchSemaphore(value: 0)
    var output = ""
    // Read stdout and stderr concurrently to avoid deadlock
    let readGroup = DispatchGroup()

    readGroup.enter()
    DispatchQueue.global().async {
        output = String(
            decoding: stdoutPipe.fileHandleForReading.readDataToEndOfFile(),
            as: UTF8.self
        )
        readGroup.leave()
    }

    readGroup.enter()
    DispatchQueue.global().async {
        _ = stderrPipe.fileHandleForReading.readDataToEndOfFile()
        readGroup.leave()
    }

    if readGroup.wait(timeout: .now() + timeout) == .timedOut {
        process.terminate()
        process.waitUntilExit()
        return "(timeout)"
    }
    process.waitUntilExit()

    // Ensure process is fully cleaned up before returning
    // This is critical for shared systems to prevent resource leaks
    while process.isRunning {
        Thread.sleep(forTimeInterval: 0.01)  // 10ms
    }

    return output
}

// ── Test runner ───────────────────────────────────────────────────────────────

var passed = 0
var failed = 0
let filter = CommandLine.arguments.dropFirst().first ?? ""

func run(_ name: String, expectation: String, commands: [String], check: (String) -> Bool) {
    guard filter.isEmpty || name.localizedCaseInsensitiveContains(filter) else { return }
    let output = os9(commands)
    if check(output) {
        print("PASS: \(name)")
        passed += 1
    } else {
        print("FAIL: \(name)")
        print("      [\(expectation)]")
        let preview = output
            .split(separator: "\n")
            .filter { !$0.hasPrefix("#") && $0 != "$" && !$0.isEmpty }
            .prefix(4)
            .joined(separator: " | ")
        print("      output: \(preview)")
        failed += 1
    }
}

func check(_ name: String, contains pattern: String, _ commands: String...) {
    run(name, expectation: "contains: \(pattern)", commands: commands) { $0.contains(pattern) }
}

func check(_ name: String, absent pattern: String, _ commands: String...) {
    run(name, expectation: "absent: \(pattern)", commands: commands) { !$0.contains(pattern) }
}

func noError(_ name: String, _ commands: String...) {
    // Match "Error #" — the OS-9 error format — not the startup ioctl message
    run(name, expectation: "no OS-9 error", commands: commands) {
        !$0.contains("Error #")
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

print("=== OS9exec integration tests ===\n")

// echo
check("echo: basic",           contains: "hello world",  "echo hello world")
check("echo: single word",     contains: "hello",        "echo hello")

// pipe (!)
check("pipe: echo ! dump",     contains: "6162 630d",    "echo abc ! dump")
check("pipe: echo ! count",    contains: "1",            "echo hello ! count")
check("pipe: echo ! tr",       contains: "HELLO",        "echo hello ! tr a-z A-Z")

// named pipes (/pipe)
check("namedpipe: write+read", contains: "6162 630d",
    "echo abc >/pipe/t1", "dump </pipe/t1")

// directory ops
check("dir: lists known file",   contains: "shell",    "dir /dd/CMDS")
check("dir: root lists CMDS",    contains: "CMDS",     "dir /dd")
check("pd: shows current dir",   contains: "/dd",      "pd")
// dir listing uses fixed-width columns: "testdir " (trailing space) appears only in the listing,
// not in the command echo ("makdir /dd/testdir" has no trailing space after "testdir")
check("makdir: creates dir",     contains: "testdir ",
    "makdir /dd/testdir", "dir /dd")
check("deldir: removes dir",     absent:   "testdir ",
    "deldir -q /dd/testdir", "dir /dd")

// file ops
check("copy: creates file",      contains: "t_echo",
    "copy /dd/CMDS/echo /dd/t_echo", "dir /dd")
check("rename: new name present", contains: "t_echo2",
    "rename /dd/t_echo t_echo2", "dir /dd")
check("rename: old name gone",   absent:   "t_echo ",  "dir /dd")
noError("attr: shows attrs",     "attr /dd/t_echo2")
check("ident: identifies mod",   contains: "echo",     "ident /dd/t_echo2")
noError("del: file cleanup",     "del /dd/t_echo2")

// text commands — create a one-line fixture; each check runs in its own os9exec process
// so the echo that creates the file is never in the same output as the check
noError("text fixture: create",                            "echo OS-9 test line >/dd/t_text")
check("list: shows content",   contains: "OS-9 test line", "list /dd/t_text")
noError("count: counts lines",                             "count /dd/t_text")
check("grep: finds pattern",   contains: "OS-9 test line", "grep OS-9 /dd/t_text")
check("grep: no match silent", absent:   "OS-9 test line", "grep ZZZNOTFOUND /dd/t_text")
check("merge: combines files", contains: "OS-9 test line", "merge /dd/t_text /dd/t_text")

// dump
check("dump: shows hex",         contains: "4afc",     "dump /dd/CMDS/echo")

// touch
check("touch: creates file",     contains: "t_touch",
    "touch /dd/t_touch", "dir /dd")
noError("del: touch cleanup",    "del /dd/t_touch")

// cmp
noError("cmp: identical files",
    "copy /dd/CMDS/echo /dd/t_cmp1",
    "copy /dd/CMDS/echo /dd/t_cmp2",
    "cmp /dd/t_cmp1 /dd/t_cmp2",
    "del /dd/t_cmp1", "del /dd/t_cmp2")

// tee
check("tee: copies to file",     contains: "teetest",
    "echo teetest ! tee /dd/t_tee", "list /dd/t_tee")
noError("del: tee cleanup",      "del /dd/t_tee")

// compress / expand
check("compress+expand: roundtrip", contains: "OS-9 test line",
    "copy /dd/t_text /dd/t_comp",
    "compress /dd/t_comp",
    "expand /dd/t_comp",
    "list /dd/t_comp")
noError("del: compress cleanup", "del /dd/t_comp")

// qsort — use two single-line files merged into qsort (>> is stderr redirect in OS-9, not append)
check("qsort: sorts lines",      contains: "apple",
    "echo banana >/dd/t_qs1",
    "echo apple >/dd/t_qs2",
    "merge /dd/t_qs1 /dd/t_qs2 ! qsort",
    "del /dd/t_qs1", "del /dd/t_qs2")

// pr
check("pr: formats output",      contains: "OS-9 test line", "pr /dd/t_text")

// system info
noError("date: runs",            "date")
noError("mdir: runs",            "mdir")
check("mdir: shell listed",      contains: "shell",   "mdir")
noError("procs: runs",           "procs")
noError("devs: runs",            "devs")
noError("printenv: runs",        "printenv")

// module ops
noError("load+unlink: echo",
    "load /dd/CMDS/echo", "unlink echo")

// sleep
noError("sleep: zero seconds",   "sleep 0")

// system info — extended
check("events: lists events",    contains: "OS-9",    "events")
check("mfree: shows memory",     contains: "K",       "mfree")
check("tmode: shows settings",   contains: "baud",    "tmode")

// file tools

// binary exchange roundtrip
check("binex+exbin: roundtrip",  contains: "Good CRC",
    "binex /dd/CMDS/echo /dd/t_echo.x",
    "exbin /dd/t_echo.x /dd/t_echo2",
    "ident /dd/t_echo2",
    "del /dd/t_echo.x", "del /dd/t_echo2")

// build a shell script from a file (stdin redirect avoids interactive stdin conflict)
check("build: creates script file", contains: "t_bscript",
    "echo echo built >/dd/t_bld_in",
    "build /dd/t_bscript </dd/t_bld_in",
    "dir /dd ! grep t_bscript",
    "del /dd/t_bscript", "del /dd/t_bld_in")

// module save/restore
check("save: writes module file", contains: "echo",
    "load /dd/CMDS/echo",
    "save echo",
    "dir /dd/CMDS ! grep echo",
    "del /dd/echo",
    "unlink echo")

// commands requiring args (usage / graceful failure)
check("tsmon: shows usage",      contains: "tsmon",       "tsmon")
check("os9gen: no device",       contains: "os9gen",      "os9gen")
noError("cfp: shows help",       "cfp")

// attr: show file attribute string
check("attr: module attrs",      contains: "--e-r",  "attr -re /dd/CMDS/echo")
noError("attr: data file attrs",                     "attr -re /dd/t_text")
noError("text fixture: cleanup",                     "del /dd/t_text")

// help: specific command help
check("help dir: options listed", contains: "recursive",  "help dir")

// merge: line count confirms newlines preserved
check("merge: two files two lines", contains: "2 lines",
    "echo x >/dd/t_mg1", "echo y >/dd/t_mg2",
    "merge /dd/t_mg1 /dd/t_mg2 ! count",
    "del /dd/t_mg1", "del /dd/t_mg2")

// disk save generates a restore script
check("dsave: generates script", contains: "copy",        "dsave /dd")

// module integrity checker
check("fixmod: good CRC",        contains: "CRC matches", "fixmod /dd/CMDS/echo")

// inline help system
check("help: shows function",    contains: "Function",    "help")


// concurrent execution (&)
// Both background and foreground echo must produce output — tests the scheduler
check("concurrent: fg runs",          contains: "fg_out",  "echo bg_out & echo fg_out")
check("concurrent: bg runs",          contains: "bg_out",  "echo bg_out & echo fg_out")
noError("concurrent: no crash",                            "sleep 0 & echo done")

// chd: directory change persists for subsequent commands
check("chd: changes working dir",     contains: "/dd/CMDS",
    "chd /dd/CMDS", "pd", "chd /dd")

// stderr redirect (>> in OS-9 is stderr, not append)
check("stderr: redirect to file",     contains: "Error",
    "list /dd/no_such_file_xyz >> /dd/t_stderr",
    "list /dd/t_stderr",
    "del /dd/t_stderr")

// paths: list open paths
noError("paths: runs",                "paths")

// what: scan module for embedded strings
noError("what: runs on module",       "what /dd/CMDS/echo")

// cudo: convert OS-9/68k module to OS-9000 format (test on a copy — cudo modifies in place)
check("cudo: converts module format", contains: "converting",
    "copy /dd/CMDS/echo /dd/t_cudo",
    "cudo /dd/t_cudo",
    "del /dd/t_cudo")

// editmod: module field editor — shows version when run with no args
check("editmod: shows version",  contains: "module editor",  "editmod")

// chown: change file owner (0.0 is a no-op without super-user, but still prints confirmation)
check("chown: changes ownership", contains: "Changed owner",
    "touch /dd/t_own",
    "chown 0.0 /dd/t_own",
    "del /dd/t_own")

// deiniz / iniz: detach and reattach a device
noError("deiniz: detaches device",  "deiniz /dd")
noError("iniz: reattaches device",  "iniz /dd")

// padrom: pad a file with 0xFF to a target size
noError("padrom: pads file",
    "touch /dd/t_padrom",
    "padrom 512 /dd/t_padrom",
    "del /dd/t_padrom")

// mkdatmod: shows help when run without required args
check("mkdatmod: shows usage",   contains: "OS-9 data module",  "mkdatmod")

// pwrstat: power management utility — shows help when run with no args
check("pwrstat: shows usage",    contains: "Power Management",  "pwrstat")

// tar: create, extract, verify round-trip
check("tar: roundtrip", contains: "tar_test_content",
    "echo tar_test_content >/dd/t_tar_src",
    "tar -cf /dd/t_tar /dd/t_tar_src",
    "del /dd/t_tar_src",
    "tar -xf /dd/t_tar",
    "list /dd/t_tar_src",
    "del /dd/t_tar_src", "del /dd/t_tar")

// ── Results ───────────────────────────────────────────────────────────────────

print("\nResults: \(passed) passed, \(failed) failed")
exit(failed > 0 ? 1 : 0)
