//
//  main.swift
//  OS9Tests
//
//  Integration test runner for os9exec. Sends commands to the OS-9 shell
//  and checks stdout for expected content.
//
//  Setup: none needed beyond the repo-root h0 (SDK toolchain) dir/symlink
//  that os9exec itself already uses. OS9DISK is pointed straight at
//  <repo root>/h0 -- no symlinks inside test/ required. RBF-specific tests
//  provision their own scratch RBF image at runtime via `mount -k=<size>`
//  and delete it afterward -- no pre-existing disk image needed.
//
//  Run (local):
//    swift run --package-path test
//    make test
//
//  Run (Docker):
//    DOCKER_IMAGE=ghcr.io/peacedudes/os9exec:latest swift run --package-path test
//    DOCKER_IMAGE=os9exec:linux32 swift run --package-path test
//
//  Run (Apple Container):
//    CONTAINER_IMAGE=os9exec:apple swift run --package-path test
//
//  Generated by Claude Sonnet 4.6 (Anthropic) — collaborator: rdoggett
//  date: 06-29-2026
//

import Foundation

// ── Configuration ─────────────────────────────────────────────────────────────

let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()   // OS9Tests/
    .deletingLastPathComponent()   // Sources/
    .deletingLastPathComponent()   // test/
    .deletingLastPathComponent()   // repo root

let execURL  = repoRoot.appendingPathComponent("os9exec")

// Primary test disk: the repo-root h0 (SDK toolchain) dir, mounted as /dd.
// Same h0 the emulator itself already uses -- no test/-local symlink needed.
let diskPath = repoRoot.appendingPathComponent("h0").path

// Optional container image for testing
// Docker: DOCKER_IMAGE=os9exec:latest swift run
// Apple Container: CONTAINER_IMAGE=os9exec:apple swift run
let dockerImage = ProcessInfo.processInfo.environment["DOCKER_IMAGE"]
let containerImage = ProcessInfo.processInfo.environment["CONTAINER_IMAGE"]

// Shell binary to launch — override with OS9SHELL env var if shell is not in /dd/CMDS
// e.g.: OS9SHELL=/h0/CMDS/shell make test
let shellArg = ProcessInfo.processInfo.environment["OS9SHELL"] ?? "shell"

// Command directory of the SDK disk these tests exercise. The tests chx here
// so every command — and every command a command forks internally (e.g.
// deldir → pd) — resolves from the SDK disk, with no other SHARE fallbacks
// shadowing it. /dd is h0 itself (see diskPath above), so this is just
// /dd/CMDS: override with OS9_SDK_CMDS if your command set is mounted elsewhere.
let sdkCmds = ProcessInfo.processInfo.environment["OS9_SDK_CMDS"] ?? "/dd/CMDS"

// ── Shell runner ──────────────────────────────────────────────────────────────

/// Run one or more OS-9 shell commands and return combined stdout.
/// ESC on a final line signals EOF to the shell.
/// Times out after `timeout` seconds to prevent hangs from blocking the suite.
/// If DOCKER_IMAGE is set, runs via Docker; otherwise runs locally (assumes dd symlink exists).
/// True when tests run inside a container (Docker or Apple Container) rather than
/// against the locally built binary.
let containerized = dockerImage != nil || containerImage != nil

/// Per-command budget. A container pays for image start-up and a cold emulator
/// boot (the UAE CPU tables are rebuilt every run) on top of the command itself,
/// which pushed the slower commands (list, pr, tar, build...) past the native 15s
/// and made them report "(timeout)" as if they had failed. Give containers room.
let defaultTimeout: TimeInterval = containerized ? 45 : 15

/// Stop a container by name. On timeout we MUST do this: terminating the `docker
/// run` client does not stop the container it started -- the container keeps
/// running, keeps the pipes open, and the suite hangs forever instead of
/// reporting a timeout. (Seen for real: one container left "Up 18 minutes" with
/// the whole run wedged behind it.)
func killContainer(_ name: String) {
    let runtime = dockerImage != nil ? "docker" : "container"
    let kill = Process()
    kill.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    kill.arguments     = [runtime, "kill", name]
    kill.standardOutput = FileHandle.nullDevice
    kill.standardError  = FileHandle.nullDevice
    try? kill.run()
    kill.waitUntilExit()
}

func os9(_ commands: [String], timeout: TimeInterval = defaultTimeout, paced: Bool = false,
         disk: String = diskPath) -> String {
    let setup  = "chx \(sdkCmds)\nload math cio\n"
    let input  = setup + commands.joined(separator: "\n") + "\n\u{1B}\n"

    let process = Process()
    let speedFlag: [String] = paced ? [] : ["-r"]
    // Named so a timeout can actually stop it -- see killContainer above.
    let containerName = "os9test-\(UUID().uuidString.prefix(8))"

    if let image = dockerImage {
        // Run via Docker: mount local dd directory and pipe stdin/stdout
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = [
            "docker",
            "run",
            "--rm",
            "-i",
            "--name", containerName,
            "-v", disk + ":/dd",
            image
        ] + speedFlag + ["shell"]
    } else if let image = containerImage {
        // Run via Apple Container: mount local dd directory and pipe stdin/stdout
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = [
            "container",
            "run",
            "--rm",
            "-i",
            "--name", containerName,
            "-v", disk + ":/dd",
            image
        ] + speedFlag + ["shell"]
    } else {
        // Run locally: OS9DISK points straight at the repo-root h0 dir.
        process.executableURL = execURL
        process.arguments    = speedFlag + [shellArg]
        process.environment  = ["OS9DISK": disk]
    }

    let stdinPipe  = Pipe()
    let stdoutPipe = Pipe()
    let stderrPipe = Pipe()  // Capture stderr too for debugging
    process.standardInput  = stdinPipe
    process.standardOutput = stdoutPipe
    process.standardError  = stderrPipe

    guard (try? process.run()) != nil else { return "" }
    stdinPipe.fileHandleForWriting.write(Data(input.utf8))
    stdinPipe.fileHandleForWriting.closeFile()

    var output = ""
    // Read stdout and stderr concurrently to avoid deadlock
    let readGroup = DispatchGroup()

    readGroup.enter()
    DispatchQueue.global().async {
        output = String(
            decoding: stdoutPipe.fileHandleForReading.readDataToEndOfFile(),
            as: UTF8.self
        )
        readGroup.leave()
    }

    readGroup.enter()
    DispatchQueue.global().async {
        _ = stderrPipe.fileHandleForReading.readDataToEndOfFile()
        readGroup.leave()
    }

    if readGroup.wait(timeout: .now() + timeout) == .timedOut {
        if containerized { killContainer(containerName) } // client != container
        process.terminate()
        process.waitUntilExit()
        return "(timeout)"
    }
    process.waitUntilExit()

    // Ensure process is fully cleaned up before returning
    // This is critical for shared systems to prevent resource leaks
    while process.isRunning {
        Thread.sleep(forTimeInterval: 0.01)  // 10ms
    }

    return output
}

// ── Test runner ───────────────────────────────────────────────────────────────

var passed = 0
var failed = 0
let filter = CommandLine.arguments.dropFirst().first ?? ""

func run(_ name: String, expectation: String, commands: [String], disk: String = diskPath,
         check: (String) -> Bool) {
    guard filter.isEmpty || name.localizedCaseInsensitiveContains(filter) else { return }
    let output = os9(commands, disk: disk)
    if check(output) {
        print("PASS: \(name)")
        passed += 1
    } else {
        print("FAIL: \(name)")
        print("      [\(expectation)]")
        let preview = output
            .split(separator: "\n")
            .filter { !$0.hasPrefix("#") && $0 != "$" && !$0.isEmpty }
            .prefix(4)
            .joined(separator: " | ")
        print("      output: \(preview)")
        failed += 1
    }
}

func check(_ name: String, contains pattern: String, _ commands: String...) {
    run(name, expectation: "contains: \(pattern)", commands: commands) { $0.contains(pattern) }
}

func check(_ name: String, contains pattern: String, disk: String, _ commands: String...) {
    run(name, expectation: "contains: \(pattern)", commands: commands, disk: disk) {
        $0.contains(pattern)
    }
}

func check(_ name: String, absent pattern: String, _ commands: String...) {
    run(name, expectation: "absent: \(pattern)", commands: commands) { !$0.contains(pattern) }
}

func noError(_ name: String, _ commands: String...) {
    // Match "Error #" — the OS-9 error format — not the startup ioctl message
    run(name, expectation: "no OS-9 error", commands: commands) {
        !$0.contains("Error #")
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

print("=== OS9exec integration tests ===\n")

// echo
check("echo: basic",           contains: "hello world",  "echo hello world")
check("echo: single word",     contains: "hello",        "echo hello")

// pipe (!)
check("pipe: echo ! dump",     contains: "6162 630d",    "echo abc ! dump")
check("pipe: echo ! count",    contains: "1",            "echo hello ! count")
check("pipe: echo ! tr",       contains: "HELLO",        "echo hello ! tr a-z A-Z")

// named pipes (/pipe)
check("namedpipe: write+read", contains: "6162 630d",
    "echo abc >/pipe/t1", "dump </pipe/t1")

// directory ops
check("dir: lists known file",   contains: "SHARE",    "dir /dd/CMDS")
check("dir: root lists CMDS",    contains: "CMDS",     "dir /dd")
check("pd: shows current dir",   contains: "/dd",      "pd")
// dir listing uses fixed-width columns: "testdir " (trailing space) appears only in the listing,
// not in the command echo ("makdir /dd/testdir" has no trailing space after "testdir")
check("makdir: creates dir",     contains: "testdir ",
    "makdir /dd/testdir", "dir /dd")
check("deldir: removes dir",     absent:   "testdir ",
    "deldir -q /dd/testdir", "dir /dd")

// file ops
check("copy: creates file",      contains: "t_echo",
    "copy \(sdkCmds)/echo /dd/t_echo", "dir /dd")
check("rename: new name present", contains: "t_echo2",
    "rename /dd/t_echo t_echo2", "dir /dd")
check("rename: old name gone",   absent:   "t_echo ",  "dir /dd")
noError("attr: shows attrs",     "attr /dd/t_echo2")
check("ident: identifies mod",   contains: "echo",     "ident /dd/t_echo2")
noError("del: file cleanup",     "del /dd/t_echo2")

// text commands — create a one-line fixture; each check runs in its own os9exec process
// so the echo that creates the file is never in the same output as the check
noError("text fixture: create",                            "echo OS-9 test line >/dd/t_text")
check("list: shows content",   contains: "OS-9 test line", "list /dd/t_text")
noError("count: counts lines",                             "count /dd/t_text")
check("grep: finds pattern",   contains: "OS-9 test line", "grep OS-9 /dd/t_text")
check("grep: no match silent", absent:   "OS-9 test line", "grep ZZZNOTFOUND /dd/t_text")
check("merge: combines files", contains: "OS-9 test line", "merge /dd/t_text /dd/t_text")

// dump
check("dump: shows hex",         contains: "4afc",     "dump \(sdkCmds)/echo")

// baud pacing: a >256-byte paced write must produce byte-identical dump
// content to the unpaced (-r) version -- proves the FIFO/pWaitWrite
// block-and-resume path doesn't drop, duplicate, or reorder bytes. 115200
// baud keeps this fast enough to finish well inside the timeout even though
// it's genuinely paced (not bypassing the FIFO like -r does).
//
// Only the dump's own hex-dump lines are compared, not the full session
// transcript: the shell's "$ " prompt now goes through the paced
// ConsoleOut path while the shell's own input-character echo (ConsRead,
// unrelated to this feature) still displays instantly, so the byte-level
// interleaving of prompts/echoes vs. paced output can legitimately differ
// between paced and unpaced runs without either one losing or corrupting
// data. That's not what this test exists to catch.
// This one is genuinely paced (that's the point), so it is the slowest test in the
// suite -- ~15s even natively, which is exactly the default timeout. Inside a
// container the extra startup pushed it over, and it "failed" with 0 lines purely
// from timing out. Give it real headroom rather than let it flap.
do {
    let pacedTimeout: TimeInterval = containerized ? 90 : 45
    let pacedOutput   = os9(["tmode baud=115200", "dump \(sdkCmds)/echo"],
                            timeout: pacedTimeout, paced: true)
    let unpacedOutput = os9(["tmode baud=115200", "dump \(sdkCmds)/echo"])

    func hexDumpLines(_ s: String) -> [Substring] {
        // Line endings here are "\r\n"; Swift treats that pair as a single
        // Character (extended grapheme cluster), so split(separator: "\n")
        // never fires. Split on any newline Character instead.
        s.split(whereSeparator: \.isNewline).filter {
            $0.range(of: "^[0-9a-f]{8}  ", options: .regularExpression) != nil
        }
    }

    let pacedLines   = hexDumpLines(pacedOutput)
    let unpacedLines = hexDumpLines(unpacedOutput)

    if pacedLines == unpacedLines && !unpacedLines.isEmpty {
        print("PASS: baud pacing: paced dump matches unpaced dump byte-for-byte")
        passed += 1
    } else {
        print("FAIL: baud pacing: paced dump differs from unpaced")
        print("      paced lines=\(pacedLines.count), unpaced lines=\(unpacedLines.count)")
        failed += 1
    }
}

// touch
check("touch: creates file",     contains: "t_touch",
    "touch /dd/t_touch", "dir /dd")
noError("del: touch cleanup",    "del /dd/t_touch")

// cmp
noError("cmp: identical files",
    "copy \(sdkCmds)/echo /dd/t_cmp1",
    "copy \(sdkCmds)/echo /dd/t_cmp2",
    "cmp /dd/t_cmp1 /dd/t_cmp2",
    "del /dd/t_cmp1", "del /dd/t_cmp2")

// tee
check("tee: copies to file",     contains: "teetest",
    "echo teetest ! tee /dd/t_tee", "list /dd/t_tee")
noError("del: tee cleanup",      "del /dd/t_tee")

// compress / expand
check("compress+expand: roundtrip", contains: "OS-9 test line",
    "copy /dd/t_text /dd/t_comp",
    "compress /dd/t_comp",
    "expand /dd/t_comp",
    "list /dd/t_comp")
noError("del: compress cleanup", "del /dd/t_comp")

// qsort — use two single-line files merged into qsort (>> is stderr redirect in OS-9, not append)
check("qsort: sorts lines",      contains: "apple",
    "echo banana >/dd/t_qs1",
    "echo apple >/dd/t_qs2",
    "merge /dd/t_qs1 /dd/t_qs2 ! qsort",
    "del /dd/t_qs1", "del /dd/t_qs2")

// pr
check("pr: formats output",      contains: "OS-9 test line", "pr /dd/t_text")

// system info
noError("date: runs",            "date")
noError("mdir: runs",            "mdir")
check("mdir: shell listed",      contains: "shell",   "mdir")
noError("procs: runs",           "procs")
// devs lists the device table; the binary has a known post-list crash (bus error),
// so we verify the table header appears rather than asserting no error.
check("devs: shows device table",    contains: "devices max", "devs")
noError("printenv: runs",        "printenv")

// module ops
noError("load+unlink: echo",
    "load \(sdkCmds)/echo", "unlink echo")

// sleep
noError("sleep: zero seconds",   "sleep 0")

// system info — extended
check("events: lists events",    contains: "OS-9",    "events")
check("mfree: shows memory",     contains: "K",       "mfree")
check("tmode: shows settings",   contains: "baud",    "tmode")

// file tools

// binary exchange roundtrip
check("binex+exbin: roundtrip",  contains: "Good CRC",
    "binex \(sdkCmds)/echo /dd/t_echo.x",
    "exbin /dd/t_echo.x /dd/t_echo2",
    "ident /dd/t_echo2",
    "del /dd/t_echo.x", "del /dd/t_echo2")

// build a shell script from a file (stdin redirect avoids interactive stdin conflict)
check("build: creates script file", contains: "t_bscript",
    "echo echo built >/dd/t_bld_in",
    "build /dd/t_bscript </dd/t_bld_in",
    "dir /dd ! grep t_bscript",
    "del /dd/t_bscript", "del /dd/t_bld_in")

// module save/restore
check("save: writes module file", contains: "echo",
    "load \(sdkCmds)/echo",
    "save echo",
    "dir /dd/CMDS ! grep echo",
    "del /dd/echo",
    "unlink echo")

// commands requiring args (usage / graceful failure)
check("tsmon: shows usage",      contains: "tsmon",       "tsmon")
check("os9gen: no device",       contains: "os9gen",      "os9gen")
noError("cfp: shows help",       "cfp")

// attr: show file attribute string
// `save echo` overwrites /dd/CMDS/echo's content in place (the file already
// exists there, so this opens it for update, not a fresh create) -- its
// real host write permission is therefore whatever it happened to inherit
// from however this platform's h0 disk was created/transferred (e.g. can
// come out world-writable on a Windows checkout, unlike a typical Unix
// checkout's rwxr-xr-x), an accident of provenance this test doesn't mean
// to depend on. So both write bits are passed explicitly (-nw -npw) rather
// than left to that ambient state. Both, not just -npw: Windows has no
// per-owner/public write distinction at the host level (a single
// FILE_ATTRIBUTE_READONLY flag covers both, see Set_FileAttr's own
// comment), so leaving owner-write untouched there would keep the merged
// flag "writable" and defeat the point of clearing -npw at all.
check("attr: module attrs",      contains: "--e-r",
    "load \(sdkCmds)/echo", "save echo", "unlink echo",
    "attr -re -nw -npw /dd/echo",
    "del /dd/echo")
noError("attr: data file attrs",                     "attr -re /dd/t_text")
noError("text fixture: cleanup",                     "del /dd/t_text")

// per-command usage: OS-9 has no "help <cmd>"; the convention is "<cmd> -?"
check("dir -?: options listed",   contains: "recursive",  "dir -?")

// merge: line count confirms newlines preserved
check("merge: two files two lines", contains: "2 lines",
    "echo x >/dd/t_mg1", "echo y >/dd/t_mg2",
    "merge /dd/t_mg1 /dd/t_mg2 ! count",
    "del /dd/t_mg1", "del /dd/t_mg2")

// disk save generates a restore script
check("dsave: generates script", contains: "copy",        "dsave /dd")

// module integrity checker
check("fixmod: good CRC",        contains: "CRC matches", "fixmod \(sdkCmds)/echo")

// inline help system
check("help: shows function",    contains: "Function",    "help")


// concurrent execution (&)
// Both background and foreground echo must produce output — tests the scheduler
check("concurrent: fg runs",          contains: "fg_out",  "echo bg_out & echo fg_out")
check("concurrent: bg runs",          contains: "bg_out",  "echo bg_out & echo fg_out")
noError("concurrent: no crash",                            "sleep 0 & echo done")

// chd: directory change persists for subsequent commands
check("chd: changes working dir",     contains: "/dd/CMDS",
    "chd /dd/CMDS", "pd", "chd /dd")

// stderr redirect (>> in OS-9 is stderr, not append)
check("stderr: redirect to file",     contains: "Error",
    "list /dd/no_such_file_xyz >> /dd/t_stderr",
    "list /dd/t_stderr",
    "del /dd/t_stderr")

// paths: list open paths
noError("paths: runs",                "paths")

// what: scan module for embedded strings
noError("what: runs on module",       "what \(sdkCmds)/echo")

// cudo: convert OS-9/68k module to OS-9000 format (test on a copy — cudo modifies in place)
check("cudo: converts module format", contains: "converting",
    "copy \(sdkCmds)/echo /dd/t_cudo",
    "cudo /dd/t_cudo",
    "del /dd/t_cudo")

// editmod: module field editor — shows version when run with no args
check("editmod: shows version",  contains: "module editor",  "editmod")

// chown: change file owner (0.0 is a no-op without super-user, but still prints confirmation)
check("chown: changes ownership", contains: "Changed owner",
    "touch /dd/t_own",
    "chown 0.0 /dd/t_own",
    "del /dd/t_own")

// deiniz / iniz: detach and reattach a device
noError("deiniz: detaches device",  "deiniz /dd")
noError("iniz: reattaches device",  "iniz /dd")

// padrom: pad a file with 0xFF to a target size
noError("padrom: pads file",
    "touch /dd/t_padrom",
    "padrom 512 /dd/t_padrom",
    "del /dd/t_padrom")

// mkdatmod: shows help when run without required args
check("mkdatmod: shows usage",   contains: "OS-9 data module",  "mkdatmod")

// pwrstat: power management utility — shows help when run with no args
check("pwrstat: shows usage",    contains: "Power Management",  "pwrstat")

// tar: create, extract, verify round-trip
check("tar: roundtrip", contains: "tar_test_content",
    "echo tar_test_content >/dd/t_tar_src",
    "tar -cf /dd/t_tar /dd/t_tar_src",
    "del /dd/t_tar_src",
    "tar -xf /dd/t_tar",
    "list /dd/t_tar_src",
    "del /dd/t_tar_src", "del /dd/t_tar")

// ── Path normalization ────────────────────────────────────────────────────────

// dot component in host-native path must resolve cleanly
noError("dir: dot path /dd/.",          "dir /dd/.")
check("dir: dot path lists CMDS",       contains: "CMDS",     "dir /dd/.")

// parent traversal: /dd/CMDS/.. should resolve back to /dd
check("dir: parent traversal",          contains: "CMDS",     "dir /dd/CMDS/..")

// relative listing after chd
check("chd: dir with no args lists dir", contains: "echo",
    "chd \(sdkCmds)", "dir", "chd /dd")

// A device root that itself contains a "/./" (or "/../") component must behave
// exactly like the plain one. The emulator collapses every path lexically
// (CutUp, in AdjustPath) but compares the result against the *configured* device
// root as a literal string prefix; when the root still carried an uncollapsed
// "/./", nothing matched, and the confinement clamp silently rewrote EVERY path
// to the device root itself -- `dir /dd/SYS` listed the root, and every ordinary
// file open failed, while module loading (which never takes that path) kept
// working, so the emulator still booted. Only meaningful for a local run: a
// container mounts its disk at /dd directly, with no OS9DISK path to dot.
if dockerImage == nil, containerImage == nil {
    let dottedDisk = repoRoot.path + "/./h0"

    check("dotted OS9DISK: subdir is not clamped to root", contains: "errmsg",
          disk: dottedDisk, "dir /dd/SYS")

    // Asserted on dump's hex, not the text: the shell echoes every command line
    // back to stdout, so a plaintext needle would match its own `echo` and pass
    // even while the file open was failing.
    check("dotted OS9DISK: ordinary file open works", contains: "6162 630d",
          disk: dottedDisk,
          "echo abc >/dd/t_dotdisk", "dump /dd/t_dotdisk", "del /dd/t_dotdisk")
}

// ── Shell variables and environment ──────────────────────────────────────────

// setenv must persist for subsequent commands in the same shell session
check("setenv: visible in printenv",    contains: "TESTVAR=hello",
    "setenv TESTVAR hello", "printenv")

// three-stage pipe: exercises the pipe scheduler end-to-end
check("pipe: three-stage chain",        contains: "1",
    "echo hello ! tr a-z A-Z ! count")

// ── Expected error paths ──────────────────────────────────────────────────────

// commands referencing nonexistent paths must produce "Error #"
check("error: list nonexistent file",   contains: "Error",    "list /dd/no_such_file_99x")
check("error: del nonexistent file",    contains: "Error",    "del /dd/no_such_file_99x")
check("error: dir nonexistent path",    contains: "Error",    "dir /dd/no_such_dir_99x")

// ── RBF device regression tests ───────────────────────────────────────────────
// Self-contained: create our own scratch RBF image via mount -k, populate
// and verify it with dsave -ive (not just touch), then delete the host
// file -- no pre-existing disk image required.
let scratchDevice   = "h9"
let scratchHostPath = repoRoot.appendingPathComponent(scratchDevice).path
try? FileManager.default.removeItem(atPath: scratchHostPath) // in case a previous run left it behind

// One session, not four: `mount -k` writes its image relative to the emulator's
// own working directory, so the four steps used to depend on that scratch file
// surviving between four separate os9exec processes. A container throws its
// filesystem away at exit (--rm), so the follow-up steps ran against an image
// that no longer existed. Doing the whole mount/dir/free/dcheck sequence in one
// session removes the cross-process dependency and tests exactly the same thing.
run("rbf: mount -k image is dir/free/dcheck clean",
    expectation: "no OS-9 error, and free reports sectors",
    commands: ["mount -k=500K \(scratchDevice)", "dir /h9", "free /h9", "dcheck /h9"]) {
        !$0.contains("Error #") && $0.contains("sectors")
    }
// Each of these mounts its own image, so clear the previous one: locally the
// scratch image persists in the repo root between processes (in a container it
// does not), and `mount -k` would otherwise be handed a file that already exists.
try? FileManager.default.removeItem(atPath: scratchHostPath)

// Mounts its own image (self-contained, so a container's throwaway filesystem is
// fine), and asserts on the DUMPED BYTES of the copied file ("dsav" = 6473 6176)
// rather than on the name "f1": the shell echoes every command line back, so
// `contains: "f1"` matched the echo of `copy ... /f1` and would have passed even
// if dsave had written nothing at all.
check  ("rbf: dsave -ive populates+verifies", contains: "6473 6176",
    "mount -k=500K \(scratchDevice)",
    "echo dsave test content >/dd/t_dsavesrc",
    "makdir /dd/t_dsavedir",
    "copy /dd/t_dsavesrc /dd/t_dsavedir/f1",
    "chd /dd/t_dsavedir", "dsave -ive /h9",
    "chd /dd", "dump /h9/f1",
    "del /dd/t_dsavesrc", "del /dd/t_dsavedir/f1", "deldir -q /dd/t_dsavedir")

try? FileManager.default.removeItem(atPath: scratchHostPath)

// ── RAM disk regression test ──────────────────────────────────────────────────
// mount -r=<size> builds a complete filesystem in memory -- no host file,
// released again via unmount. Also verified with dsave -ive, not just touch.
// Note the leading '/' on /ram9: mount -r=<size> <name> requires an
// absolute device name -- a bare "ram9" fails classification entirely
// (unrelated to this feature; see the plan's Global Constraints note).
noError("ramdisk: mount -r creates disk", "mount -r=200 /ram9", "dir /ram9", "unmount ram9")
check  ("ramdisk: dsave -ive populates+verifies", contains: "f1",
    "echo ramdisk test content >/dd/t_ramsrc",
    "makdir /dd/t_ramdir",
    "copy /dd/t_ramsrc /dd/t_ramdir/f1",
    "chd /dd/t_ramdir", "mount -r=200 /ram9", "dsave -ive /ram9", "dir /ram9", "unmount ram9",
    "chd /dd", "del /dd/t_ramsrc", "del /dd/t_ramdir/f1", "deldir -q /dd/t_ramdir")

// ══════════════════════════════════════════════════════════════════════════════
// FILESYSTEM SELF-TESTS   (name prefix "fs:" — run just these with
//   swift run --package-path test OS9Tests fs:)
// ══════════════════════════════════════════════════════════════════════════════
// Two mental categories of test live in this file:
//   1. COMMAND SMOKE TESTS (everything above) — "does `grep` / `tar` / `dsave`
//      run and produce plausible output" — they depend on which command modules
//      we happen to have working.
//   2. SELF-TESTS (this section, plus the RBF/ramdisk/baud ones above) — they
//      test the emulator's OWN guaranteed behavior, provision everything they
//      need, and assert exact outcomes. Anyone can run them; nothing external
//      is assumed.
// These verify the file system itself: that every legal spelling of a path
// resolves to the SAME right place, that NO path trick escapes a host-native
// device root into the host OS (the confinement the emulator must guarantee —
// see the '..'-past-root regression, git log), and that OS-9 permissions are
// honored on an RBF image. Local-only: they plant fixtures and a canary on the
// host beside the device root, which a container's mounted /dd can't express.
if !containerized {
    let fsHostDir    = diskPath + "/USR/CLAUDE/fsselftest"   // under /dd, host-visible
    let fsSubHost    = fsHostDir + "/SUB"
    let marker       = "FSMARK_\(UUID().uuidString.prefix(8))"
    // the canary lives in the device root's HOST PARENT — it must NEVER be
    // reachable from inside OS-9 by any path trick.
    let canaryName   = "FSCANARY_\(UUID().uuidString.prefix(8))"
    let canaryHost   = URL(fileURLWithPath: diskPath).deletingLastPathComponent()
                          .appendingPathComponent(canaryName).path
    let canarySecret = "CANARYLEAK_\(UUID().uuidString.prefix(8))"

    // provision on the host (deterministic; OS-9 files use CR line endings)
    try? FileManager.default.createDirectory(atPath: fsSubHost, withIntermediateDirectories: true)
    try? (marker + "\r").write(toFile: fsSubHost + "/deep", atomically: true, encoding: .utf8)
    try? (canarySecret + "\r").write(toFile: canaryHost, atomically: true, encoding: .utf8)
    // a host symlink INSIDE the device pointing OUT at the canary — the realpath
    // confinement must refuse to follow it out of the device root.
    try? FileManager.default.createSymbolicLink(atPath: fsSubHost + "/esclink",
                                                withDestinationPath: canaryHost)

    // guard: the whole confinement half is vacuous if the canary wasn't written
    if (try? String(contentsOfFile: canaryHost, encoding: .utf8))?.contains(canarySecret) != true {
        print("FAIL: fs: setup — canary file not planted"); failed += 1
    }

    let sub = "/dd/USR/CLAUDE/fsselftest/SUB"   // OS-9 working dir for these

    // ---- resolution: every legal spelling must read the SAME marker file ----
    // (the marker tests double as the positive control for the confinement
    //  tests below: they prove `list` really does surface a file's contents.)
    func resolves(_ label: String, _ spelling: String) {
        run("fs: resolve \(label)", expectation: "reads the marker via '\(spelling)'",
            commands: ["chd \(sub)", "list \(spelling)"]) { $0.contains(marker) }
    }
    resolves("relative",              "deep")
    resolves("dot-relative",          "./deep")
    resolves("absolute /dd",          "/dd/USR/CLAUDE/fsselftest/SUB/deep")
    resolves("/h0 device alias",      "/h0/USR/CLAUDE/fsselftest/SUB/deep")
    resolves("double slash",          "/dd//USR/CLAUDE/fsselftest/SUB/deep")
    resolves("embedded /./",          "/dd/./USR/CLAUDE/fsselftest/SUB/deep")
    resolves("parent round-trip",     "../SUB/deep")
    resolves("through SYS and back",  "/dd/SYS/../USR/CLAUDE/fsselftest/SUB/deep")
    resolves("case-insensitive",      "/dd/usr/claude/FSSELFTEST/sub/DEEP")
    resolves("multi-dot to root",     "...../USR/CLAUDE/fsselftest/SUB/deep")       // up-4 == /dd, then descend
    resolves("over-walk clamps+keeps","............/USR/CLAUDE/fsselftest/SUB/deep") // '..' past root: clamp, keep tail (regression guard)

    // ---- confinement: the host canary outside the root must be UNREACHABLE ----
    func blocked(_ label: String, _ spelling: String) {
        run("fs: confine \(label)", expectation: "canary NOT leaked via '\(spelling)'",
            commands: ["chd \(sub)", "list \(spelling)"]) { !$0.contains(canarySecret) }
    }
    blocked("/dd/../canary",        "/dd/../\(canaryName)")
    blocked("/dd/../../canary",     "/dd/../../\(canaryName)")
    blocked("deep ../ escape",      "../../../../../\(canaryName)")
    blocked("over-walk escape",     "............/\(canaryName)")
    blocked("through SYS escape",   "/dd/SYS/../../\(canaryName)")
    blocked("/h0 alias escape",     "/h0/../\(canaryName)")
    blocked("symlink out of device","esclink")            // realpath confinement must not follow it out

    try? FileManager.default.removeItem(atPath: fsHostDir)
    try? FileManager.default.removeItem(atPath: canaryHost)

    // ---- permissions: ENFORCED on RBF images (real ownership + attribute bits) ----
    // claude (1.7) and dog (1.3) are blank-password non-super accounts already in
    // this disk's /dd/SYS/password -- see os9-dev skill's REPL notes for how this
    // was live-verified (login really does F$SUser to a distinct Grp.Usr). su (0.0)
    // is just this suite's default top-level session -- no login needed for it.
    let permDev     = "h8"
    let permDevPath = "/\(permDev)"
    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(permDev).path)

    // NOTE: every sequence below that ends still logged in as claude/dog closes
    // with an explicit "logout" before the run/check helpers' implicit final
    // ESC. Confirmed via direct os9exec REPL runs (see task-2-report.md): login
    // forks a nested "claude:"/"dog:" shell, and the harness only sends ONE
    // terminating ESC. If the sequence ends inside that nested shell, the ESC
    // is consumed there and the outer top-level "$" shell hangs forever waiting
    // for more input that will never come -- the process times out and os9()
    // returns the literal string "(timeout)", which trivially fails a
    // `contains: "Error #"` check and trivially PASSES a `!contains("Error #")`
    // check, silently masking the real result either way. This is a harness/
    // login-nesting artifact, unrelated to permission enforcement -- adding the
    // trailing "logout" (already used correctly elsewhere in this block) fixes
    // it and lets the real output flow through to the assertions.
    run("fs: permission — claude creates+owns a file, can read it back",
        expectation: "dump of a freshly created file shows its bytes to its own creator",
        commands: ["mount -k=200K \(permDev)", "chd \(permDevPath)",
                   "login claude", "chd \(permDevPath)",
                   "echo abc >f", "dump f", "logout"]) { $0.contains("6162 63") }

    check("fs: permission — owner locks self out by clearing owner-read",
        contains: "Error #",
        "chd \(permDevPath)", "login claude", "chd \(permDevPath)",
        "attr f -nr", "dump f", "logout")

    check("fs: permission — super-user still bypasses every check",
        contains: "6162 63",
        "chd \(permDevPath)", "dump f")

    check("fs: permission — non-owner (dog) blocked from a file with no public bits",
        contains: "Error #",
        "chd \(permDevPath)", "login dog", "chd \(permDevPath)", "dump f", "logout")

    check("fs: permission — owner restores public-read, non-owner can now read",
        contains: "6162 63",
        "chd \(permDevPath)", "login claude", "chd \(permDevPath)", "attr f -pr", "logout",
        "login dog", "chd \(permDevPath)", "dump f", "logout")

    check("fs: permission — non-owner cannot change attributes on a file they don't own",
        contains: "Error #",
        "chd \(permDevPath)", "login dog", "chd \(permDevPath)", "attr f -nr", "logout")

    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(permDev).path)

    // ---- permissions: file-level write bit (has_open_perm's write path) ----
    // `>` redirection always requests create, so re-running it against a file
    // that already exists hits E_CEF ("creating existing file") before the
    // write-bit check is ever reached -- that would pass trivially regardless
    // of the write bit, which is not what we want to test. `touch` opens an
    // EXISTING file for write without requesting create, so it lands squarely
    // on has_open_perm's write path (live-verified: E_FNA when owner-write is
    // cleared, succeeds when it's set).
    let filePermDev     = "hc"
    let filePermDevPath = "/\(filePermDev)"
    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(filePermDev).path)

    run("fs: permission — owner locks self out of writing own file (write bit via touch)",
        expectation: "clearing only owner-write blocks touch (open-for-write) on the owner's own file",
        commands: ["mount -k=200K \(filePermDev)", "chd \(filePermDevPath)",
                   "login claude", "chd \(filePermDevPath)",
                   "echo abc >f", "attr f -nw", "touch f", "logout"]) { $0.contains("Error #") }

    check("fs: permission — owner can still read that same file (write lockout is write-specific)",
        contains: "6162 63",
        "chd \(filePermDevPath)", "login claude", "chd \(filePermDevPath)", "dump f", "logout")

    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(filePermDev).path)

    // ---- permissions: directories (read gates traversal, write gates create/delete) ----
    let dirPermDev  = "ha"
    let dirPermPath = "/\(dirPermDev)"
    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(dirPermDev).path)

    run("fs: permission dir — dog can create inside claude's dir while public r+w are set",
        expectation: "makdir's default attrs (owner+public rwx) let a non-owner create inside",
        commands: ["mount -k=200K \(dirPermDev)", "chd \(dirPermPath)",
                   "login claude", "chd \(dirPermPath)", "makdir sub", "logout",
                   "login dog", "chd \(dirPermPath)/sub", "echo x >g",
                   "logout"]) { !$0.contains("Error #") }

    check("fs: permission dir — write blocked once public-write is cleared",
        contains: "Error #",
        "chd \(dirPermPath)", "login claude", "chd \(dirPermPath)", "attr sub -npw", "logout",
        "login dog", "chd \(dirPermPath)/sub", "echo x >g2", "logout")

    check("fs: permission dir — directory itself unreachable once public-read is also cleared",
        contains: "Error #",
        "chd \(dirPermPath)", "login claude", "chd \(dirPermPath)", "attr sub -npr", "logout",
        "login dog", "chd \(dirPermPath)/sub", "logout")

    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(dirPermDev).path)

    // ---- permissions: pRdelete's parent-directory write check ----
    // Deletion is gated on the PARENT DIRECTORY's write permission, not on who
    // owns the file being deleted (live-verified below): dog lacks public-write
    // on claude's "sub2", so dog's "del f" is blocked even though dog can still
    // see/traverse into sub2 (public-read stays set). claude, who has owner-write
    // on the directory, deletes the same file with no trouble -- the positive
    // control that proves the negative result above isn't vacuous.
    let delDev     = "hd"
    let delDevPath = "/\(delDev)"
    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(delDev).path)

    run("fs: permission del — dog blocked from deleting a file in claude's dir (no public-write)",
        expectation: "pRdelete's parent-directory write check rejects a non-owner without dir write",
        commands: ["mount -k=200K \(delDev)", "chd \(delDevPath)",
                   "login claude", "chd \(delDevPath)", "makdir sub2", "chd sub2", "echo abc >f",
                   "chd ..", "attr sub2 -npw", "logout",
                   "login dog", "chd \(delDevPath)/sub2", "del f", "logout"]) {
        $0.contains("Error #")
    }

    check("fs: permission del — claude (dir owner, has write) deletes the same file fine",
        absent: "Error #",
        "chd \(delDevPath)/sub2", "login claude", "chd \(delDevPath)/sub2", "del f", "logout")

    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(delDev).path)

    // ---- permissions: RAM disk (mount -r) backed RBF gets identical enforcement ----
    // A RAM disk is still a genuine RBF filesystem (same file_rbf.c path as an
    // on-disk image, just backed by the emulator's own memory arena instead of a
    // host file) -- this proves enforcement isn't accidentally specific to
    // file-backed images. Each test below is fully self-contained (mounts its
    // own fresh /ram7, does its own login(s), unmounts at the end): unlike a
    // `mount -k` image, a RAM disk has no host file backing it, so nothing
    // persists between separate os9exec processes -- each `run()`/`check()`
    // call here is its own process and must build the whole scenario itself.
    // All four scenarios below were first live-verified by hand via
    // tools/os9repl.sh (see the os9-dev skill's REPL notes) before being
    // written here, including the "logout" gotcha noted above.
    run("fs: permission ramdisk — claude creates+owns a file, can read it back",
        expectation: "dump of a freshly created file on a RAM-backed RBF device shows its bytes to its own creator",
        commands: ["mount -r=200 /ram7", "chd /ram7",
                   "login claude", "chd /ram7",
                   "echo abc >f", "dump f", "logout", "unmount ram7"]) { $0.contains("6162 63") }

    check("fs: permission ramdisk — owner locks self out by clearing owner-read",
        contains: "Error #",
        "mount -r=200 /ram7", "chd /ram7", "login claude", "chd /ram7",
        "echo abc >f", "attr f -nr", "dump f", "logout", "unmount ram7")

    check("fs: permission ramdisk — super-user still bypasses even after owner-read is cleared",
        contains: "6162 63",
        "mount -r=200 /ram7", "chd /ram7", "login claude", "chd /ram7",
        "echo abc >f", "attr f -nr", "logout",
        "chd /ram7", "dump f", "unmount ram7")

    check("fs: permission ramdisk — non-owner (dog) blocked from a file with no public bits",
        contains: "Error #",
        "mount -r=200 /ram7", "chd /ram7", "login claude", "chd /ram7",
        "echo abc >f", "logout",
        "login dog", "chd /ram7", "dump f", "logout", "unmount ram7")

    // ---- host-native devices: real host permissions, best-effort per platform ----
    // attr's own F$Open requests neither read nor write (mode==0 -- it only
    // needs a path number for the GetStat/SetStat that follows), so a real
    // host read/write denial on the file's content must not block it, or
    // attr could never be used to restore access once cleared -- mirroring
    // RBF's has_open_perm(), which only checks the bits an open actually
    // requests. dump's own open genuinely requests read, so it stays denied
    // for real until attr grants it back.
    check("fs: permission — host-native device enforces a real read denial",
        contains: "Error #",
        "mount -k=0 hb", "chd /hb", "echo abc >f",
        "attr f -nr -nw -ne -npr -npw -npe", "dump f")
    // hb/f is left write-denied at the real host level by the check above;
    // remove it so the next check's "echo abc >f" isn't trying to overwrite
    // a file it (correctly) no longer has permission to touch.
    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent("hb").path)

    check("fs: permission — host-native: attr can still restore access it just revoked",
        contains: "6162 63",
        "mount -k=0 hb", "chd /hb", "echo abc >f",
        "attr f -nr -nw -ne -npr -npw -npe", "attr f -r -pr", "dump f")
    try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent("hb").path)
}

// ── F$STrap: exception-handler dispatch across a run of vectors ───────────────
// Regression for the BASIC09 REAL/0 crash family.  Installs ONE F$STrap handler
// over vectors 4/5/6/7 and fires illegal / zero-divide / CHK / TRAPV in turn,
// re-entering the handler each time.  Guards the whole set of fixes: the
// init-table byte-swap (little-endian handler install), the handler-offset base
// (itab+2), A7=A5 handler entry, and the handled-exception dump gating.  Before
// those, a caught arithmetic trap crashed or hung the process instead of
// reaching its handler.  Tools are preloaded (memory-resident) so they fork by
// name without a chx into /dd/CMDS.
do {
    let strapAsm = [
        "  use /dd/DEFS/oskdefs.d",
        "",
        "F$Exit   equ  $06",
        "F$STrap  equ  $0E",
        "I$WritLn equ  $8C",
        "",
        "  psect strptst,(Prgrm<<8)+Objct,(ReEnt<<8)+0,1,512,start",
        "",
        "start:",
        "  lea     itab(pc),a1",
        "  suba.l  a0,a0",
        "  OS9     F$STrap",
        "  ori.b   #2,ccr",
        "  trapv",
        "t6:",
        "  moveq   #-1,d0",
        "  chk     #0,d0",
        "t5:",
        "  moveq   #1,d0",
        "  divu    #0,d0",
        "t4:",
        "  dc.w    $4AFC",
        "tdone:",
        "  lea     mdone(pc),a0",
        "  moveq   #mdonel,d1",
        "  moveq   #1,d0",
        "  OS9     I$WritLn",
        "  moveq   #0,d1",
        "  OS9     F$Exit",
        "itab:",
        "  dc.w    $0010",
        "  dc.w    handler-p4",
        "p4:",
        "  dc.w    $0014",
        "  dc.w    handler-p5",
        "p5:",
        "  dc.w    $0018",
        "  dc.w    handler-p6",
        "p6:",
        "  dc.w    $001C",
        "  dc.w    handler-p7",
        "p7:",
        "  dc.w    $FFFF",
        "handler:",
        "  move.l  a1,a7",
        "  move.w  d7,d0",
        "  cmpi.w  #$1C,d0",
        "  beq     h7",
        "  cmpi.w  #$18,d0",
        "  beq     h6",
        "  cmpi.w  #$14,d0",
        "  beq     h5",
        "  cmpi.w  #$10,d0",
        "  beq     h4",
        "  bra     tdone",
        "h7:",
        "  lea     m7(pc),a0",
        "  moveq   #m7l,d1",
        "  bsr     wr",
        "  bra     t6",
        "h6:",
        "  lea     m6(pc),a0",
        "  moveq   #m6l,d1",
        "  bsr     wr",
        "  bra     t5",
        "h5:",
        "  lea     m5(pc),a0",
        "  moveq   #m5l,d1",
        "  bsr     wr",
        "  bra     t4",
        "h4:",
        "  lea     m4(pc),a0",
        "  moveq   #m4l,d1",
        "  bsr     wr",
        "  bra     tdone",
        "wr:",
        "  moveq   #1,d0",
        "  OS9     I$WritLn",
        "  rts",
        "m7:  dc.b  \"vector 7 (TRAPV) handler reached\",$0D",
        "m7l  equ   *-m7",
        "m6:  dc.b  \"vector 6 (CHK) handler reached\",$0D",
        "m6l  equ   *-m6",
        "m5:  dc.b  \"vector 5 (zero divide) handler reached\",$0D",
        "m5l  equ   *-m5",
        "m4:  dc.b  \"vector 4 (illegal) handler reached\",$0D",
        "m4l  equ   *-m4",
        "mdone: dc.b \"ALL FOUR EXCEPTION HANDLERS REACHED\",$0D",
        "mdonel equ  *-mdone",
        "",
        "  ends",
        ""
    ].joined(separator: "\r")

    let asmPath = repoRoot.appendingPathComponent("h0/strptst.a").path
    try? strapAsm.write(toFile: asmPath, atomically: true, encoding: .utf8)

    let name = "f$strap: one handler catches four exceptions in a row (TRAPV/CHK/div0/illegal)"
    if filter.isEmpty || name.localizedCaseInsensitiveContains(filter) {
        let out = os9([
            "load /dd/CMDS/r68 /dd/CMDS/l68",
            "r68 /dd/strptst.a -o=/dd/strptst.r",
            "l68 /dd/strptst.r -o=/dd/strptst",
            "/dd/strptst"
        ], timeout: 30)
        let reached = out.contains("vector 7 (TRAPV) handler reached")
            && out.contains("vector 6 (CHK) handler reached")
            && out.contains("vector 5 (zero divide) handler reached")
            && out.contains("vector 4 (illegal) handler reached")
            && out.contains("ALL FOUR EXCEPTION HANDLERS REACHED")
        if reached {
            print("PASS: \(name)")
            passed += 1
        } else {
            print("FAIL: \(name)")
            print("      [each of the four vectors must reach the handler]")
            let preview = out.split(separator: "\n")
                .filter { !$0.hasPrefix("#") && $0 != "$" && !$0.isEmpty }
                .prefix(8).joined(separator: " | ")
            print("      output: \(preview)")
            failed += 1
        }
    }

    for leftover in ["h0/strptst.a", "h0/strptst.r", "h0/strptst"] {
        try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(leftover).path)
    }
}

// ── F$STrap: a handler that RESUMES the interrupted program (not just diverts) ──
// The sibling test above only exercises handlers that abandon the faulting flow.
// This one exercises the resume-in-place path: the handler restores the saved
// register block and returns to the interrupted code via R$pc, and the program
// runs on to a normal exit.  Regression for the spurious `oldpc+2` that os9exec
// added to R$pc on the UAE path (os9_uae.c): +2 landed R$pc two bytes past the
// real per-exception PC -- mid-instruction -- so any resuming handler ran garbage.
// Covers both PC conventions UAE hands us: TRAPV leaves R$pc at the NEXT
// instruction (the op pre-advances), so the handler resumes directly; DIVU/CHK
// leave R$pc AT the faulting instruction, so the handler must step R$pc past it
// (here +4, the width of `divu #0,dn`) to skip the divide.  The register block is
// D0-D7 / A0-A6 / callers-A7($3C) / SR($40) / PC($42), and the handler resumes in
// USER state (RTE is privileged) by pushing R$pc onto the caller's own stack and
// RTS'ing to it.
do {
    let resumeAsm = [
        "  use /dd/DEFS/oskdefs.d",
        "",
        "F$Exit   equ  $06",
        "F$STrap  equ  $0E",
        "I$WritLn equ  $8C",
        "",
        "  psect rsmtst,(Prgrm<<8)+Objct,(ReEnt<<8)+0,1,512,start",
        "",
        "start:",
        "  lea     itab(pc),a1",
        "  suba.l  a0,a0",
        "  OS9     F$STrap",
        "  ori.b   #2,ccr",
        "  trapv",                          // vector 7: R$pc already = next insn
        "  lea     m7(pc),a0",
        "  moveq   #m7l,d1",
        "  moveq   #1,d0",
        "  OS9     I$WritLn",
        "  moveq   #1,d0",
        "  divu    #0,d0",                  // vector 5: R$pc = this insn; handler steps it
        "  lea     m5(pc),a0",
        "  moveq   #m5l,d1",
        "  moveq   #1,d0",
        "  OS9     I$WritLn",
        "  moveq   #0,d1",
        "  OS9     F$Exit",
        "itab:",
        "  dc.w    $001C",                  // vector 7 (TRAPV)
        "  dc.w    handler-p7",
        "p7:",
        "  dc.w    $0014",                  // vector 5 (zero divide)
        "  dc.w    handler-p5",
        "p5:",
        "  dc.w    $FFFF",
        "handler:",
        "  cmpi.w  #$14,d7",               // zero-divide? R$pc points AT the divu
        "  bne     hgo",
        "  addq.l  #4,$42(a7)",            //   step R$pc past the 4-byte divu
        "hgo:",
        "  move.l  $42(a7),-(a1)",         // push R$pc onto caller's own stack
        "  move.l  a1,$3C(a7)",            // record the new caller SP in the block
        "  movem.l (a7)+,d0-d7/a0-a6",     // restore the interrupted registers
        "  movea.l (a7),a7",               // A7 = caller SP (points at pushed R$pc)
        "  rts",                           // resume the interrupted program
        "m7:  dc.b  \"RESUMED PAST TRAPV\",$0D",
        "m7l  equ   *-m7",
        "m5:  dc.b  \"RESUMED PAST DIVU0\",$0D",
        "m5l  equ   *-m5",
        "",
        "  ends",
        ""
    ].joined(separator: "\r")

    let asmPath = repoRoot.appendingPathComponent("h0/rsmtst.a").path
    try? resumeAsm.write(toFile: asmPath, atomically: true, encoding: .utf8)

    let name = "f$strap: a handler resumes the interrupted program (TRAPV next-pc + div0 step-pc)"
    if filter.isEmpty || name.localizedCaseInsensitiveContains(filter) {
        let out = os9([
            "load /dd/CMDS/r68 /dd/CMDS/l68",
            "r68 /dd/rsmtst.a -o=/dd/rsmtst.r",
            "l68 /dd/rsmtst.r -o=/dd/rsmtst",
            "/dd/rsmtst"
        ], timeout: 30)
        let reached = out.contains("RESUMED PAST TRAPV")
            && out.contains("RESUMED PAST DIVU0")
        if reached {
            print("PASS: \(name)")
            passed += 1
        } else {
            print("FAIL: \(name)")
            print("      [both handlers must resume past the fault, not divert or crash]")
            let preview = out.split(separator: "\n")
                .filter { !$0.hasPrefix("#") && $0 != "$" && !$0.isEmpty }
                .prefix(8).joined(separator: " | ")
            print("      output: \(preview)")
            failed += 1
        }
    }

    for leftover in ["h0/rsmtst.a", "h0/rsmtst.r", "h0/rsmtst"] {
        try? FileManager.default.removeItem(atPath: repoRoot.appendingPathComponent(leftover).path)
    }
}

// ── Results ───────────────────────────────────────────────────────────────────

print("\nResults: \(passed) passed, \(failed) failed")
exit(failed > 0 ? 1 : 0)
